$axure.loadCurrentPage({
  "url":"患者登记.html",
  "generationDate":new Date(1524492033268.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e8502d2e25db4c6594bc365f9ed8b6fc",
    "type":"Axure:Page",
    "name":"患者登记",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"29e75f6cef374b3ca32a140782cc0251",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b2ad06f80f94ea29c6b3c8ebb63080b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"010625f4c36a485daf113e42b0db9126",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"128e9942019e4e869ef821eee2a57c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"a7d9765697694ee9afcc02721e0cc924",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57412ae9447241e982f4657a621e3fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"4c347df95cb444a5bc7a8a962da49e4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64ed498c4a4d457f9b0319bb4f6ff9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"ce7cd74d172a4f4d81ae1efb5dbf5ac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16d427e10b3a496cb57dceede0af2505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"801bf573bb3d4b858a044f854d8300cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"25px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":180},
            "size":{
              "width":775,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e260e9eed1459bb2fdae9dd0545309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"25px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":180},
                "size":{
                  "width":775,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fbcff3095bd466aa82bd19d41d71bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":433,
              "y":266},
            "size":{
              "width":260,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c5162c5dde48fea4229da885015a70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":433,
                  "y":266},
                "size":{
                  "width":260,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3429db9a54b847fb85db94cd5969df42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":778,
              "y":266},
            "size":{
              "width":300,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"317aa7c8db7247b78eaca58a4d1afb77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":778,
                  "y":266},
                "size":{
                  "width":300,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"011b5bb473ef4df9b7c91958722ab1eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":433,
              "y":330},
            "size":{
              "width":502,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81a95a9f3ddb4faa964584caff08d184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":433,
                  "y":330},
                "size":{
                  "width":502,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f29d78788ffa4a51905136f46fd935c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":308},
            "size":{
              "width":720,
              "height":1},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d542d4d49349c6bc7c1e249853798f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":383,
                  "y":308},
                "size":{
                  "width":720,
                  "height":1},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u18.png"}},
{
          "id":"754dee7e08ba48e98a140035ed345066",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":430,
              "y":308},
            "size":{
              "width":244,
              "height":2},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd524ca10fc4523aed86621aa42ba5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":430,
                  "y":308},
                "size":{
                  "width":244,
                  "height":2},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u20.png"}},
{
          "id":"6829a8863c2f4c00a1bc0d57f5c1ab8f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":369},
            "size":{
              "width":274,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2f6cc9356f254580a167f4834a565492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":434,
              "y":369},
            "size":{
              "width":55,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c94c2afd842744048ceaac5627fcbaff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":434,
                  "y":369},
                "size":{
                  "width":55,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7181d3ed5354f18a199a44884a159d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":493,
              "y":372},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"896ba2d26e9446e8b8db60ef45810b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":493,
                  "y":372},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcf3426b48884afbbc0d50caf6d6cf14",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":813,
              "y":368},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在我院进行检查",
                      "target":{
                        "targetType":"page",
                        "url":"在我院进行检查.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"936dbb0f02a544ba8011784144825bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25aefa7c097548afadf62a619ce23152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5487a7e984364b43abf0e92a8719bdc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d35b5b8a042642dbb605a5319232da0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u30.png"}},
{
          "id":"800bf87975914c399c750c54c1947a00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7027be761c9f4e968fbc97bf4d143c99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"a1daad250f9c4866ac38fad3040412c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2ba8ffd88448d8a65e42c88eebcba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33d506b6336a42dbb8331de8122fc66b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c24ffe5412a240779298273d9829a0dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u36.png"}},
{
          "id":"8f50e8737f3f49b495ecb512eeaca78f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0a798ddc0c4a0c8e287461b036ce8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"737f52ea2eed4da69db278e77128e47d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb370b6dbd9412ea01f48d5cd52c60c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"3767157646b34f0d80d3d2bfac407bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5313b588973c40ce8a1cfe325793bf1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c720d7cf3af495d83649315282b60ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":20,
              "y":320},
            "size":{
              "width":230,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66474891efe0400da6a0b3d78ba133f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":20,
                  "y":320},
                "size":{
                  "width":230,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44b7ff726bc3425489c00bbcf1d5b5fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ffb6f2b6daa494fb89b81f68ba4d06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c2891cc0dd84e728efead6e69dc60ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770.5,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccaafd378ecd42b3a5493f5893dabe87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770.5,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54f8a535d7d447c919a57c1b3b237a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac925df7c6d945a9b79cdbec5e603a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "29e75f6cef374b3ca32a140782cc0251":{
      "scriptId":"u0"},
    "0b2ad06f80f94ea29c6b3c8ebb63080b":{
      "scriptId":"u1"},
    "010625f4c36a485daf113e42b0db9126":{
      "scriptId":"u2"},
    "128e9942019e4e869ef821eee2a57c65":{
      "scriptId":"u3"},
    "a7d9765697694ee9afcc02721e0cc924":{
      "scriptId":"u4"},
    "57412ae9447241e982f4657a621e3fde":{
      "scriptId":"u5"},
    "4c347df95cb444a5bc7a8a962da49e4a":{
      "scriptId":"u6"},
    "64ed498c4a4d457f9b0319bb4f6ff9ef":{
      "scriptId":"u7"},
    "ce7cd74d172a4f4d81ae1efb5dbf5ac5":{
      "scriptId":"u8"},
    "16d427e10b3a496cb57dceede0af2505":{
      "scriptId":"u9"},
    "801bf573bb3d4b858a044f854d8300cf":{
      "scriptId":"u10"},
    "15e260e9eed1459bb2fdae9dd0545309":{
      "scriptId":"u11"},
    "5fbcff3095bd466aa82bd19d41d71bd1":{
      "scriptId":"u12"},
    "96c5162c5dde48fea4229da885015a70":{
      "scriptId":"u13"},
    "3429db9a54b847fb85db94cd5969df42":{
      "scriptId":"u14"},
    "317aa7c8db7247b78eaca58a4d1afb77":{
      "scriptId":"u15"},
    "011b5bb473ef4df9b7c91958722ab1eb":{
      "scriptId":"u16"},
    "81a95a9f3ddb4faa964584caff08d184":{
      "scriptId":"u17"},
    "f29d78788ffa4a51905136f46fd935c4":{
      "scriptId":"u18"},
    "50d542d4d49349c6bc7c1e249853798f":{
      "scriptId":"u19"},
    "754dee7e08ba48e98a140035ed345066":{
      "scriptId":"u20"},
    "5bd524ca10fc4523aed86621aa42ba5f":{
      "scriptId":"u21"},
    "6829a8863c2f4c00a1bc0d57f5c1ab8f":{
      "scriptId":"u22"},
    "2f6cc9356f254580a167f4834a565492":{
      "scriptId":"u23"},
    "c94c2afd842744048ceaac5627fcbaff":{
      "scriptId":"u24"},
    "f7181d3ed5354f18a199a44884a159d2":{
      "scriptId":"u25"},
    "896ba2d26e9446e8b8db60ef45810b28":{
      "scriptId":"u26"},
    "dcf3426b48884afbbc0d50caf6d6cf14":{
      "scriptId":"u27"},
    "936dbb0f02a544ba8011784144825bf8":{
      "scriptId":"u28"},
    "25aefa7c097548afadf62a619ce23152":{
      "scriptId":"u29"},
    "5487a7e984364b43abf0e92a8719bdc8":{
      "scriptId":"u30"},
    "d35b5b8a042642dbb605a5319232da0a":{
      "scriptId":"u31"},
    "800bf87975914c399c750c54c1947a00":{
      "scriptId":"u32"},
    "7027be761c9f4e968fbc97bf4d143c99":{
      "scriptId":"u33"},
    "a1daad250f9c4866ac38fad3040412c1":{
      "scriptId":"u34"},
    "6b2ba8ffd88448d8a65e42c88eebcba4":{
      "scriptId":"u35"},
    "33d506b6336a42dbb8331de8122fc66b":{
      "scriptId":"u36"},
    "c24ffe5412a240779298273d9829a0dd":{
      "scriptId":"u37"},
    "8f50e8737f3f49b495ecb512eeaca78f":{
      "scriptId":"u38"},
    "aa0a798ddc0c4a0c8e287461b036ce8f":{
      "scriptId":"u39"},
    "737f52ea2eed4da69db278e77128e47d":{
      "scriptId":"u40"},
    "0fb370b6dbd9412ea01f48d5cd52c60c":{
      "scriptId":"u41"},
    "3767157646b34f0d80d3d2bfac407bf8":{
      "scriptId":"u42"},
    "5313b588973c40ce8a1cfe325793bf1a":{
      "scriptId":"u43"},
    "3c720d7cf3af495d83649315282b60ed":{
      "scriptId":"u44"},
    "66474891efe0400da6a0b3d78ba133f0":{
      "scriptId":"u45"},
    "44b7ff726bc3425489c00bbcf1d5b5fc":{
      "scriptId":"u46"},
    "3ffb6f2b6daa494fb89b81f68ba4d06f":{
      "scriptId":"u47"},
    "5c2891cc0dd84e728efead6e69dc60ab":{
      "scriptId":"u48"},
    "ccaafd378ecd42b3a5493f5893dabe87":{
      "scriptId":"u49"},
    "e54f8a535d7d447c919a57c1b3b237a4":{
      "scriptId":"u50"},
    "ac925df7c6d945a9b79cdbec5e603a7e":{
      "scriptId":"u51"}}});