$axure.loadCurrentPage({
  "url":"测算_1.html",
  "generationDate":new Date(1524492037127.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7812a4d18525472d8879baf1b5f9642e",
    "type":"Axure:Page",
    "name":"测算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cd3e3538a60447f5b69b7b6883203ccb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a7ff09c67a4209b7ab46a2b7b46f90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"d8e2d4ac522f46d88dac8e908506465c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6deb3e6418b5401292e31f2fdfceadc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"f60204a470dd49d582f31451c0090cca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":675}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f9b11a36cf445a86a256ca55c9cebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":675}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算/u4.png"}},
{
          "id":"722cb35139d843e1a6b785b948623da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2585c34613745e49c7e4bf85a355fa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"399a2dd74f624863b49c8dbe346e0dea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":48},
            "size":{
              "width":1020,
              "height":583},
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4857e9501a58498887ffa69a7586f226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":48},
                "size":{
                  "width":1020,
                  "height":583},
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算_1/u8.png"}},
{
          "id":"8e3a38009cec4e79a7a39dcc07ce33dd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":78},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录入",
                      "target":{
                        "targetType":"page",
                        "url":"录入_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5ee513774ca64a909466ea870352417f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":641},
            "size":{
              "width":380,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8806eafba4334fb0807629641781134f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":641},
                "size":{
                  "width":380,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c05db9b711a843d69cdeebd4a9b7a097",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":602,
              "y":641},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2c2b4fb248b4e96ab5ca0c48b08613a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":602,
                  "y":641},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"899e5482ded540f3aaa2bc23a531c6ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":734,
              "y":376},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000dea5fb0b6443ab00f9c3741a33bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":376},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5ec7b55cce14558ad349c78a0d1475e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":628,
              "y":641},
            "size":{
              "width":571,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d182a60fa94aa19f73dabf674e9dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":628,
                  "y":641},
                "size":{
                  "width":571,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73b5298b1d704989897b3e345a954dd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":740,
              "y":290.615539550781},
            "size":{
              "width":50,
              "height":80},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53e30af19393474e859c7e6d2b17a0b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":740,
                  "y":290.615539550781},
                "size":{
                  "width":50,
                  "height":80},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口-1/u8.png"}},
{
          "id":"155295a21f6141d39b8eb0ec1af48a4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":864,
              "y":244},
            "size":{
              "width":136,
              "height":213},
            "rotation":"156",
            "textRotation":"156",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49da8678c4aa42f29b426e8af2e47da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":864,
                  "y":244},
                "size":{
                  "width":136,
                  "height":213},
                "rotation":"156",
                "textRotation":"156",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算_1/u21.png"}},
{
          "id":"2621254dfdbf457e8ba4d71eec2c656e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":925,
              "y":460},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cd170c416a4cf29a9f45b85884e20d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":925,
                  "y":460},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bf7b28026774d53ae55559384bd47c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":672},
            "size":{
              "width":380,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb531f8cf4884a52afd9ceb87b43081a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":672},
                "size":{
                  "width":380,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ccd72726c9d4c61b3f21c3dc21d3568",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":602,
              "y":671},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a3db08381314d279600f7c596d5daed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":602,
                  "y":671},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"573e8dd4b01744738f436229ec1e4ade",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":627,
              "y":672},
            "size":{
              "width":571,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70fb283a1fd74f8ab0bbaec8d409b6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":627,
                  "y":672},
                "size":{
                  "width":571,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cd3e3538a60447f5b69b7b6883203ccb":{
      "scriptId":"u0"},
    "b5a7ff09c67a4209b7ab46a2b7b46f90":{
      "scriptId":"u1"},
    "d8e2d4ac522f46d88dac8e908506465c":{
      "scriptId":"u2"},
    "6deb3e6418b5401292e31f2fdfceadc5":{
      "scriptId":"u3"},
    "f60204a470dd49d582f31451c0090cca":{
      "scriptId":"u4"},
    "43f9b11a36cf445a86a256ca55c9cebb":{
      "scriptId":"u5"},
    "722cb35139d843e1a6b785b948623da8":{
      "scriptId":"u6"},
    "b2585c34613745e49c7e4bf85a355fa0":{
      "scriptId":"u7"},
    "399a2dd74f624863b49c8dbe346e0dea":{
      "scriptId":"u8"},
    "4857e9501a58498887ffa69a7586f226":{
      "scriptId":"u9"},
    "8e3a38009cec4e79a7a39dcc07ce33dd":{
      "scriptId":"u10"},
    "5ee513774ca64a909466ea870352417f":{
      "scriptId":"u11"},
    "8806eafba4334fb0807629641781134f":{
      "scriptId":"u12"},
    "c05db9b711a843d69cdeebd4a9b7a097":{
      "scriptId":"u13"},
    "e2c2b4fb248b4e96ab5ca0c48b08613a":{
      "scriptId":"u14"},
    "899e5482ded540f3aaa2bc23a531c6ab":{
      "scriptId":"u15"},
    "000dea5fb0b6443ab00f9c3741a33bd2":{
      "scriptId":"u16"},
    "f5ec7b55cce14558ad349c78a0d1475e":{
      "scriptId":"u17"},
    "e4d182a60fa94aa19f73dabf674e9dab":{
      "scriptId":"u18"},
    "73b5298b1d704989897b3e345a954dd2":{
      "scriptId":"u19"},
    "53e30af19393474e859c7e6d2b17a0b6":{
      "scriptId":"u20"},
    "155295a21f6141d39b8eb0ec1af48a4a":{
      "scriptId":"u21"},
    "49da8678c4aa42f29b426e8af2e47da6":{
      "scriptId":"u22"},
    "2621254dfdbf457e8ba4d71eec2c656e":{
      "scriptId":"u23"},
    "77cd170c416a4cf29a9f45b85884e20d":{
      "scriptId":"u24"},
    "0bf7b28026774d53ae55559384bd47c8":{
      "scriptId":"u25"},
    "bb531f8cf4884a52afd9ceb87b43081a":{
      "scriptId":"u26"},
    "6ccd72726c9d4c61b3f21c3dc21d3568":{
      "scriptId":"u27"},
    "6a3db08381314d279600f7c596d5daed":{
      "scriptId":"u28"},
    "573e8dd4b01744738f436229ec1e4ade":{
      "scriptId":"u29"},
    "70fb283a1fd74f8ab0bbaec8d409b6e1":{
      "scriptId":"u30"}}});