$axure.loadCurrentPage({
  "url":"多个开放性伤口的缝线伤口.html",
  "generationDate":new Date(1524492039805.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e9fa3e70fccd4e91921e1ecbfa77da89",
    "type":"Axure:Page",
    "name":"多个开放性伤口的缝线伤口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"964c0f7fa8f3483dbe12b243f3a1c9be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a304c7570cbb42b09c3472f9dfead07f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"f74e9b6851fb4ca2addc4c256e90089a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":-72},
            "size":{
              "width":674,
              "height":911},
            "rotation":"270",
            "textRotation":"270",
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b57f46194594c5dab12fc8cdaaa67c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":-72},
                "size":{
                  "width":674,
                  "height":911},
                "rotation":"270",
                "textRotation":"270",
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/多个开放性伤口的缝线伤口/u2.png"}},
{
          "id":"c2a185fbca754b69b8efdfa14b48dfc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":679},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a075ccd975f429796170750861e08a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":679},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u4.png"}},
{
          "id":"d5356c9e0f4a4069917180a845439fc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":359},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ca916b4af94117baffc0355187273e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1190,
                  "y":359},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄后_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/单个开放性伤口/u6.png"}},
{
          "id":"7f456f93250f4cfd815db91ee90472bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":520,
              "y":70},
            "size":{
              "width":390,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea784e17e78142deb5c98b9a677cc976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":520,
                  "y":70},
                "size":{
                  "width":390,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u8.png"}},
{
          "id":"12a9b02b3bae416d988d2b9fb12c2d0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1198,
              "y":679},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef8a787e4464418b0cb313096c3c528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1198,
                  "y":679},
                "size":{
                  "width":60,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a14e6e5610e495fb1eafbaffe805d8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":682},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565d568309cb4e32aa574de7f506740f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":682},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"c6d5fde06f5e4305af66715bc78ab22a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1168,
              "y":673},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f76c2c3e4df41a3a08c0e508333a6bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1168,
                  "y":673},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄与测量清创前伤口",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄与测量清创前伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65cd760065f840a0838db434dc286e1d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":820},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复诊-拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"复诊-拍摄后_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "964c0f7fa8f3483dbe12b243f3a1c9be":{
      "scriptId":"u0"},
    "a304c7570cbb42b09c3472f9dfead07f":{
      "scriptId":"u1"},
    "f74e9b6851fb4ca2addc4c256e90089a":{
      "scriptId":"u2"},
    "6b57f46194594c5dab12fc8cdaaa67c5":{
      "scriptId":"u3"},
    "c2a185fbca754b69b8efdfa14b48dfc7":{
      "scriptId":"u4"},
    "9a075ccd975f429796170750861e08a0":{
      "scriptId":"u5"},
    "d5356c9e0f4a4069917180a845439fc0":{
      "scriptId":"u6"},
    "b7ca916b4af94117baffc0355187273e":{
      "scriptId":"u7"},
    "7f456f93250f4cfd815db91ee90472bc":{
      "scriptId":"u8"},
    "ea784e17e78142deb5c98b9a677cc976":{
      "scriptId":"u9"},
    "12a9b02b3bae416d988d2b9fb12c2d0a":{
      "scriptId":"u10"},
    "0ef8a787e4464418b0cb313096c3c528":{
      "scriptId":"u11"},
    "4a14e6e5610e495fb1eafbaffe805d8a":{
      "scriptId":"u12"},
    "565d568309cb4e32aa574de7f506740f":{
      "scriptId":"u13"},
    "c6d5fde06f5e4305af66715bc78ab22a":{
      "scriptId":"u14"},
    "1f76c2c3e4df41a3a08c0e508333a6bb":{
      "scriptId":"u15"},
    "65cd760065f840a0838db434dc286e1d":{
      "scriptId":"u16"}}});