$axure.loadCurrentPage({
  "url":"不完整病历.html",
  "generationDate":new Date(1524492044940.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05f7daa8e12147a9a90749f9a56e2ec2",
    "type":"Axure:Page",
    "name":"不完整病历",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c680208d36b4b219bd6758697c785f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c4e5bdbb64e4d48a0c5c9f260910443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"1c0fe1af82744062ba4eca9ae976323d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d42ff3bc220457981357b64be9b37be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"b9760b97074644cfacf5a6407c066fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668d02f7fd334e969b6b4a97792af150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"f02987aa227d49998a04b172bf7cc04b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb443360542d4bcfa5a9037c0ab2f423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"4c7c4bfa8db34b5083a4eb3534b1c9f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b0d26c0a9a54ffe9fd2c912c30c9cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"f3ef753bf6cc480d9d991af7bd6aa02a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32dd7795501f4efca8437fa33d083726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"fa0571a4964f4e8986d1215088c106eb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":1024},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"180e4e4e402044a7aa13a80491ed724d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bacb92da971943e8bf06a996446b03c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"b0f997731278439d95bfb94fa6f2c886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7fb72d7286468caa72ec7155912d4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"408942ab7f0e42219aaab328306c3694",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f67107e34a8e447eb6bba79688ca20ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"a6c91a2c3a6741f4afad62348f43cac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"363457bcfd4e4bbaa2866936a4407574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者列表",
                      "target":{
                        "targetType":"page",
                        "url":"患者列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd7ecfbd44004028996a3d319f672cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":873},
            "size":{
              "width":99,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a557f16ff348038f703dc5204de9b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":873},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u91.png"}},
{
          "id":"7d763351ef024e0ca050f07d58d6814b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":909},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73bd94ffa81d48ec9a8a3f2d9e074a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":909},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"a40140e3942d4595a044c723c4357931",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":920},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c1c4d3fe8e482e99dd565eb14a01e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":973,
                  "y":920},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"7eb87378e9334fc0afa86ad503f52e1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":250},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"090617ef349240a18972a47c30da2b66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":250},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"c2ea30627783406ea71eca8d539e9a5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157166c9f77540508f0391b5245cfdcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"d54c564e16704ec5b90cb6e891a85fe6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5086b792b11f438a85b23e449225a372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"54de8527c28d4090a80611a82471ac8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f5ee78685641dfae648dd809127eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"5df4792dacbf41e690fe5f8af144317b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":374},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73233d85e73944b5b77d82a425f5faf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":374},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6feb8df03e67462fa0b1a010f847d2ab",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":364},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"46491d37f2c84f8e95b216cfde6a96f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba4ab3e0dbad479288cfc2acbd368595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40fa4a72401748ca8ca6cecfe3eb1e86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21ddd546f02d4ba2b2a9b48708802e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52211ddb810d44aaa371178577de671e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":468},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b53cb7052ff4e478ca5c8feec36a8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":468},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"7ccc001033464f7aa7e709d5382f0bb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7a2225d5b14abe83773eb24622e7c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"7e209fd26c4247129ed01df207930dce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f84a4d0ded44420ab14824eac37575ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"3239ba85836e401bb7c3e380e74df5d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cadf973cbba84fe2a0d8ead3d07a1ad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"ec091ac5d9f642c2aff15d565a813967",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":592},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd06b9e4caec416bb2a03f7647ad3d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":592},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0955324047c1416f86c4c9f6d1a8ddae",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":582},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"15f1cd113fed43ecae5e2e72b588e7af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae761d4d89f4b52b91ea097a4493654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe152129be245e1a0d6c82124643a12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f317fbd3849470781d94768ffc4068d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4584ae5ea4e848de84683fd1b79be6ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":687},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afeb73e8fde4b47b90613244fcc7cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":687},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"396125baf3994a68a0cd309e23eef379",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cfc5f1ba7bf4b528ccfbaaac1a879cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"6263dbaba8b54f8989d1735fda434bf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"100eb83d04c546f38801a16f59aced59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"201ab53ba0da42d7be20cf2460217ae2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea62568596843fd8972f2624f63fa4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"9c65ddc26371488e8bb9fda1a07b8f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":811},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a04c5a5a2a48aaab1b2e848de995d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":811},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d9e2366cebe408c98277a726e938853",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":801},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"2ac7766e06884d629034da614dfc374b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2903d25bd91a43d0abc40cb4f21b86b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13f6862297a646ee9eba25127a45405b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3970b996cae447e5afdd9bbd7bdac903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e9d4f28dff4404a977a196f9cf304b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":913},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5018614df14ef7a7875f6ec2c1205a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":913},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"ce6be8cbc3c64749883ebab824208e2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f5b8fc9cdc4540985874ba374c44a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d45a5cb41134466fb5cc1dca5e73c634",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ae431d110d453394c4d9f5f0d19750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5b8350a85704670ac2a2edbb9dc2dd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"147a0f032c314d9f9d02fc1b44f05e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"16826086fe5345589783012fb97c5314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d1bdb4d7214b3eb17ad53e4697f939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98125ac554dd438293fbf0d40897fd24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0fbe3308b641b08bef1ec3fa986276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"38591308aaf949c89680fc44429282ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d12bf263e4d74eb3a9b54d61711c95d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"744505bc2c4a442c80684b5c8034d494",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e61618cf7f37473fa204d74a3420e73a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4be9ee2cdf9442fa788f2ca50844602",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b91a48ef0ef4ea38076a479d09c8cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"91f473214951461188b35cf5a002703f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7902e4f64289453795853a953036af6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6fc1f951bbf47a0b383e8cadf7a0227",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6b6fc1966834f62ba557ba77d7c2297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"53ab09d49177483faa9a9c04b1b02005",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce46cfa8cba64248b0f727e0ab34e059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"e3edc9a635f54fb994b47422da3ab9c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8f9f740a3447329e2f9c777aa343df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a97b9b34031c43b09d028b9b3b81ff3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8ec48965834fcc8960a4e5caf3031d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7786a08bb754bc994d6f22c09885143",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54cd3667cd0a40e0acb33394953d698a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9cc9cfcaa574ab5a6af234fcc97c262",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1500776f508743caad13e588652dde21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c680208d36b4b219bd6758697c785f0":{
      "scriptId":"u0"},
    "2c4e5bdbb64e4d48a0c5c9f260910443":{
      "scriptId":"u1"},
    "1c0fe1af82744062ba4eca9ae976323d":{
      "scriptId":"u2"},
    "1d42ff3bc220457981357b64be9b37be":{
      "scriptId":"u3"},
    "b9760b97074644cfacf5a6407c066fbd":{
      "scriptId":"u4"},
    "668d02f7fd334e969b6b4a97792af150":{
      "scriptId":"u5"},
    "f02987aa227d49998a04b172bf7cc04b":{
      "scriptId":"u6"},
    "cb443360542d4bcfa5a9037c0ab2f423":{
      "scriptId":"u7"},
    "4c7c4bfa8db34b5083a4eb3534b1c9f0":{
      "scriptId":"u8"},
    "5b0d26c0a9a54ffe9fd2c912c30c9cda":{
      "scriptId":"u9"},
    "f3ef753bf6cc480d9d991af7bd6aa02a":{
      "scriptId":"u10"},
    "32dd7795501f4efca8437fa33d083726":{
      "scriptId":"u11"},
    "fa0571a4964f4e8986d1215088c106eb":{
      "scriptId":"u12"},
    "180e4e4e402044a7aa13a80491ed724d":{
      "scriptId":"u13"},
    "bacb92da971943e8bf06a996446b03c5":{
      "scriptId":"u14"},
    "b0f997731278439d95bfb94fa6f2c886":{
      "scriptId":"u15"},
    "df7fb72d7286468caa72ec7155912d4c":{
      "scriptId":"u16"},
    "408942ab7f0e42219aaab328306c3694":{
      "scriptId":"u17"},
    "f67107e34a8e447eb6bba79688ca20ec":{
      "scriptId":"u18"},
    "a6c91a2c3a6741f4afad62348f43cac5":{
      "scriptId":"u19"},
    "363457bcfd4e4bbaa2866936a4407574":{
      "scriptId":"u20"},
    "fd7ecfbd44004028996a3d319f672cc1":{
      "scriptId":"u21"},
    "65a557f16ff348038f703dc5204de9b2":{
      "scriptId":"u22"},
    "7d763351ef024e0ca050f07d58d6814b":{
      "scriptId":"u23"},
    "73bd94ffa81d48ec9a8a3f2d9e074a89":{
      "scriptId":"u24"},
    "a40140e3942d4595a044c723c4357931":{
      "scriptId":"u25"},
    "a7c1c4d3fe8e482e99dd565eb14a01e0":{
      "scriptId":"u26"},
    "7eb87378e9334fc0afa86ad503f52e1c":{
      "scriptId":"u27"},
    "090617ef349240a18972a47c30da2b66":{
      "scriptId":"u28"},
    "c2ea30627783406ea71eca8d539e9a5f":{
      "scriptId":"u29"},
    "157166c9f77540508f0391b5245cfdcc":{
      "scriptId":"u30"},
    "d54c564e16704ec5b90cb6e891a85fe6":{
      "scriptId":"u31"},
    "5086b792b11f438a85b23e449225a372":{
      "scriptId":"u32"},
    "54de8527c28d4090a80611a82471ac8d":{
      "scriptId":"u33"},
    "c7f5ee78685641dfae648dd809127eff":{
      "scriptId":"u34"},
    "5df4792dacbf41e690fe5f8af144317b":{
      "scriptId":"u35"},
    "73233d85e73944b5b77d82a425f5faf0":{
      "scriptId":"u36"},
    "6feb8df03e67462fa0b1a010f847d2ab":{
      "scriptId":"u37"},
    "46491d37f2c84f8e95b216cfde6a96f8":{
      "scriptId":"u38"},
    "ba4ab3e0dbad479288cfc2acbd368595":{
      "scriptId":"u39"},
    "40fa4a72401748ca8ca6cecfe3eb1e86":{
      "scriptId":"u40"},
    "21ddd546f02d4ba2b2a9b48708802e87":{
      "scriptId":"u41"},
    "52211ddb810d44aaa371178577de671e":{
      "scriptId":"u42"},
    "4b53cb7052ff4e478ca5c8feec36a8b2":{
      "scriptId":"u43"},
    "7ccc001033464f7aa7e709d5382f0bb1":{
      "scriptId":"u44"},
    "ad7a2225d5b14abe83773eb24622e7c7":{
      "scriptId":"u45"},
    "7e209fd26c4247129ed01df207930dce":{
      "scriptId":"u46"},
    "f84a4d0ded44420ab14824eac37575ab":{
      "scriptId":"u47"},
    "3239ba85836e401bb7c3e380e74df5d1":{
      "scriptId":"u48"},
    "cadf973cbba84fe2a0d8ead3d07a1ad5":{
      "scriptId":"u49"},
    "ec091ac5d9f642c2aff15d565a813967":{
      "scriptId":"u50"},
    "bd06b9e4caec416bb2a03f7647ad3d2c":{
      "scriptId":"u51"},
    "0955324047c1416f86c4c9f6d1a8ddae":{
      "scriptId":"u52"},
    "15f1cd113fed43ecae5e2e72b588e7af":{
      "scriptId":"u53"},
    "2ae761d4d89f4b52b91ea097a4493654":{
      "scriptId":"u54"},
    "abe152129be245e1a0d6c82124643a12":{
      "scriptId":"u55"},
    "6f317fbd3849470781d94768ffc4068d":{
      "scriptId":"u56"},
    "4584ae5ea4e848de84683fd1b79be6ed":{
      "scriptId":"u57"},
    "7afeb73e8fde4b47b90613244fcc7cbb":{
      "scriptId":"u58"},
    "396125baf3994a68a0cd309e23eef379":{
      "scriptId":"u59"},
    "3cfc5f1ba7bf4b528ccfbaaac1a879cd":{
      "scriptId":"u60"},
    "6263dbaba8b54f8989d1735fda434bf3":{
      "scriptId":"u61"},
    "100eb83d04c546f38801a16f59aced59":{
      "scriptId":"u62"},
    "201ab53ba0da42d7be20cf2460217ae2":{
      "scriptId":"u63"},
    "0ea62568596843fd8972f2624f63fa4c":{
      "scriptId":"u64"},
    "9c65ddc26371488e8bb9fda1a07b8f23":{
      "scriptId":"u65"},
    "f5a04c5a5a2a48aaab1b2e848de995d5":{
      "scriptId":"u66"},
    "5d9e2366cebe408c98277a726e938853":{
      "scriptId":"u67"},
    "2ac7766e06884d629034da614dfc374b":{
      "scriptId":"u68"},
    "2903d25bd91a43d0abc40cb4f21b86b0":{
      "scriptId":"u69"},
    "13f6862297a646ee9eba25127a45405b":{
      "scriptId":"u70"},
    "3970b996cae447e5afdd9bbd7bdac903":{
      "scriptId":"u71"},
    "6e9d4f28dff4404a977a196f9cf304b0":{
      "scriptId":"u72"},
    "2f5018614df14ef7a7875f6ec2c1205a":{
      "scriptId":"u73"},
    "ce6be8cbc3c64749883ebab824208e2d":{
      "scriptId":"u74"},
    "f1f5b8fc9cdc4540985874ba374c44a5":{
      "scriptId":"u75"},
    "d45a5cb41134466fb5cc1dca5e73c634":{
      "scriptId":"u76"},
    "79ae431d110d453394c4d9f5f0d19750":{
      "scriptId":"u77"},
    "f5b8350a85704670ac2a2edbb9dc2dd1":{
      "scriptId":"u78"},
    "147a0f032c314d9f9d02fc1b44f05e3e":{
      "scriptId":"u79"},
    "16826086fe5345589783012fb97c5314":{
      "scriptId":"u80"},
    "62d1bdb4d7214b3eb17ad53e4697f939":{
      "scriptId":"u81"},
    "98125ac554dd438293fbf0d40897fd24":{
      "scriptId":"u82"},
    "4f0fbe3308b641b08bef1ec3fa986276":{
      "scriptId":"u83"},
    "38591308aaf949c89680fc44429282ea":{
      "scriptId":"u84"},
    "d12bf263e4d74eb3a9b54d61711c95d4":{
      "scriptId":"u85"},
    "744505bc2c4a442c80684b5c8034d494":{
      "scriptId":"u86"},
    "e61618cf7f37473fa204d74a3420e73a":{
      "scriptId":"u87"},
    "d4be9ee2cdf9442fa788f2ca50844602":{
      "scriptId":"u88"},
    "6b91a48ef0ef4ea38076a479d09c8cbf":{
      "scriptId":"u89"},
    "91f473214951461188b35cf5a002703f":{
      "scriptId":"u90"},
    "7902e4f64289453795853a953036af6d":{
      "scriptId":"u91"},
    "e6fc1f951bbf47a0b383e8cadf7a0227":{
      "scriptId":"u92"},
    "f6b6fc1966834f62ba557ba77d7c2297":{
      "scriptId":"u93"},
    "53ab09d49177483faa9a9c04b1b02005":{
      "scriptId":"u94"},
    "ce46cfa8cba64248b0f727e0ab34e059":{
      "scriptId":"u95"},
    "e3edc9a635f54fb994b47422da3ab9c6":{
      "scriptId":"u96"},
    "ac8f9f740a3447329e2f9c777aa343df":{
      "scriptId":"u97"},
    "a97b9b34031c43b09d028b9b3b81ff3c":{
      "scriptId":"u98"},
    "bf8ec48965834fcc8960a4e5caf3031d":{
      "scriptId":"u99"},
    "b7786a08bb754bc994d6f22c09885143":{
      "scriptId":"u100"},
    "54cd3667cd0a40e0acb33394953d698a":{
      "scriptId":"u101"},
    "e9cc9cfcaa574ab5a6af234fcc97c262":{
      "scriptId":"u102"},
    "1500776f508743caad13e588652dde21":{
      "scriptId":"u103"}}});