$axure.loadCurrentPage({
  "url":"测算_2.html",
  "generationDate":new Date(1524492039697.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"09c76eb3649f48b28ed6a2dc642c1a20",
    "type":"Axure:Page",
    "name":"测算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b3139a549d045ec8742c24e2e0423fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5c1df05cab2434e94b7a9528fd1d3b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"e982229a30f6455b810842fc496c9557",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3930474cf964c918c354da0abe5fd3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"7943f29d99ef49e7a6d86cbe733105f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":675}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026b617366d04507939a1b4c72c2fb26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":675}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算/u4.png"}},
{
          "id":"28a5ce7285974fe0835c190eebec01db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49192ea491be47169a8597cf97b2f1c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"17698759060c4e34894e0c7210520c3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":648},
            "size":{
              "width":380,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fcb911b94444b69b0f701caab2250f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":648},
                "size":{
                  "width":380,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd7c41f51761402d87b4b5ed54db845d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":602,
              "y":641},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd865d744914cb5a52a750581b745ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":602,
                  "y":641},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"221fd45d685d40b7819f8eb368c196aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":628,
              "y":648},
            "size":{
              "width":571,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9ae2191060417d99417d7e42e4b522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":628,
                  "y":648},
                "size":{
                  "width":571,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"380a0a36090d4772801e9e5eb61b0e8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":683},
            "size":{
              "width":380,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ccf71712bf24b8cb96976eabd300cdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":683},
                "size":{
                  "width":380,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb4b16923364398bd50bab6d6a6ddac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":594},
            "rotation":"0",
            "textRotation":"270",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f059371fe7849c8a51eff189dd91d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":594},
                "rotation":"0",
                "textRotation":"270",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算_2/u16.png"}},
{
          "id":"6a76c4e4864543df862812c77d52792f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":699,
              "y":230},
            "size":{
              "width":180,
              "height":21},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0cb9ec343c54e17b8cc4402f32c1201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":699,
                  "y":230},
                "size":{
                  "width":180,
                  "height":21},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算_2/u18.png"}},
{
          "id":"469728084a7d44cdbf2ad9f85d31a028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":763,
              "y":254},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487a007fe14e41a1b1a2a07ad3cfac88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":763,
                  "y":254},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76ee1c76ebcd424dba107b571da82b0e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":237},
            "size":{
              "width":807,
              "height":10},
            "rotation":"1",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测算_2/u22_line.png"}},
{
          "id":"85cbbe0b1f3e4e2d884d0e4eaa65667d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":78},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录入",
                      "target":{
                        "targetType":"page",
                        "url":"录入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "6b3139a549d045ec8742c24e2e0423fe":{
      "scriptId":"u0"},
    "c5c1df05cab2434e94b7a9528fd1d3b0":{
      "scriptId":"u1"},
    "e982229a30f6455b810842fc496c9557":{
      "scriptId":"u2"},
    "c3930474cf964c918c354da0abe5fd3a":{
      "scriptId":"u3"},
    "7943f29d99ef49e7a6d86cbe733105f0":{
      "scriptId":"u4"},
    "026b617366d04507939a1b4c72c2fb26":{
      "scriptId":"u5"},
    "28a5ce7285974fe0835c190eebec01db":{
      "scriptId":"u6"},
    "49192ea491be47169a8597cf97b2f1c1":{
      "scriptId":"u7"},
    "17698759060c4e34894e0c7210520c3f":{
      "scriptId":"u8"},
    "3fcb911b94444b69b0f701caab2250f0":{
      "scriptId":"u9"},
    "dd7c41f51761402d87b4b5ed54db845d":{
      "scriptId":"u10"},
    "8cd865d744914cb5a52a750581b745ad":{
      "scriptId":"u11"},
    "221fd45d685d40b7819f8eb368c196aa":{
      "scriptId":"u12"},
    "2c9ae2191060417d99417d7e42e4b522":{
      "scriptId":"u13"},
    "380a0a36090d4772801e9e5eb61b0e8e":{
      "scriptId":"u14"},
    "2ccf71712bf24b8cb96976eabd300cdc":{
      "scriptId":"u15"},
    "0fb4b16923364398bd50bab6d6a6ddac":{
      "scriptId":"u16"},
    "3f059371fe7849c8a51eff189dd91d1a":{
      "scriptId":"u17"},
    "6a76c4e4864543df862812c77d52792f":{
      "scriptId":"u18"},
    "f0cb9ec343c54e17b8cc4402f32c1201":{
      "scriptId":"u19"},
    "469728084a7d44cdbf2ad9f85d31a028":{
      "scriptId":"u20"},
    "487a007fe14e41a1b1a2a07ad3cfac88":{
      "scriptId":"u21"},
    "76ee1c76ebcd424dba107b571da82b0e":{
      "scriptId":"u22"},
    "85cbbe0b1f3e4e2d884d0e4eaa65667d":{
      "scriptId":"u23"}}});