$axure.loadCurrentPage({
  "url":"复诊-上次比对.html",
  "generationDate":new Date(1524492034620.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e17b5a4b983b4ea8aaf2913bcb8c8b17",
    "type":"Axure:Page",
    "name":"复诊-上次比对",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73342fefb1a746feb17f4c6c0e3eb31b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2b5838f47384ec59e73e6cfffa326ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"3cdb3824b7254de38495a8c6d4bd3b1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":675},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec61a985dfe447c6ae6de06b207eae4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":675},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复诊-圈划伤口",
                      "target":{
                        "targetType":"page",
                        "url":"复诊-圈划伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/复诊-上次比对/u2.png"}},
{
          "id":"9a7ba106031d4524b59b5308aff7722d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a65324a06c524dcd9804bc1282457e5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"0f8df73e8c644f6e894d9123c41b6d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e22be7da8664a6b88759ea52fb9e14c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复诊-上次比对",
                      "target":{
                        "targetType":"page",
                        "url":"复诊-上次比对.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"3e60d2d5334c49e4976a857b2bfbd0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":840,
              "y":280},
            "size":{
              "width":160,
              "height":130},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6257ae14c8714312bbbdb205ccd2d20d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":840,
                  "y":280},
                "size":{
                  "width":160,
                  "height":130},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-上次比对/u8.png"}},
{
          "id":"2a1f04cb085e44d1b7b3441265b69e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":960,
              "y":400},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed8d06c0c9146649623a6fc647111c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":400},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f350d521ccc4ef7a0ae1e3d44d0b472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":1170,
              "y":78},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"230ccdbcfe464f7bb45b792ff1a749a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":1170,
                  "y":78},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/复诊-上次比对/u12.png"}},
{
          "id":"be49964cc4ff432f87179945d0721239",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":454,
              "y":72},
            "size":{
              "width":600,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d49630262d42a0a225c9dd1a3a7b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":454,
                  "y":72},
                "size":{
                  "width":600,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "73342fefb1a746feb17f4c6c0e3eb31b":{
      "scriptId":"u0"},
    "c2b5838f47384ec59e73e6cfffa326ca":{
      "scriptId":"u1"},
    "3cdb3824b7254de38495a8c6d4bd3b1a":{
      "scriptId":"u2"},
    "ec61a985dfe447c6ae6de06b207eae4f":{
      "scriptId":"u3"},
    "9a7ba106031d4524b59b5308aff7722d":{
      "scriptId":"u4"},
    "a65324a06c524dcd9804bc1282457e5d":{
      "scriptId":"u5"},
    "0f8df73e8c644f6e894d9123c41b6d37":{
      "scriptId":"u6"},
    "6e22be7da8664a6b88759ea52fb9e14c":{
      "scriptId":"u7"},
    "3e60d2d5334c49e4976a857b2bfbd0db":{
      "scriptId":"u8"},
    "6257ae14c8714312bbbdb205ccd2d20d":{
      "scriptId":"u9"},
    "2a1f04cb085e44d1b7b3441265b69e2b":{
      "scriptId":"u10"},
    "8ed8d06c0c9146649623a6fc647111c1":{
      "scriptId":"u11"},
    "3f350d521ccc4ef7a0ae1e3d44d0b472":{
      "scriptId":"u12"},
    "230ccdbcfe464f7bb45b792ff1a749a7":{
      "scriptId":"u13"},
    "be49964cc4ff432f87179945d0721239":{
      "scriptId":"u14"},
    "91d49630262d42a0a225c9dd1a3a7b45":{
      "scriptId":"u15"}}});