$axure.loadCurrentPage({
  "url":"圈划缝线_1.html",
  "generationDate":new Date(1524492040716.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c617611ef6e41aeaf67ad33019cf9e4",
    "type":"Axure:Page",
    "name":"圈划缝线",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ea7a8d477c64f7c88da102c6050e0c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747c4005fe92445f98ea10e6f7e17a12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"e83227065ed9461e9123c86dc2118bc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":-126},
            "size":{
              "width":675,
              "height":1022},
            "rotation":"270",
            "textRotation":"270",
            "cornerRadiusTopLeft":"12"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da8412b8a1a4e2c9e15d999ba9cf033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":-126},
                "size":{
                  "width":675,
                  "height":1022},
                "rotation":"270",
                "textRotation":"270",
                "cornerRadiusTopLeft":"12"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口-1_1/u2.png"}},
{
          "id":"84d95bdaa7244906a7900b691392de69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fdf221b18e349a39a500f662d06b2c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"273a1f29afff411cbe6cd4674720e506",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffbf8602dfbc4ca6869c2c8ef3240b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄后_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"3810b83c1f9346319bad75cd585ef493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":590,
              "y":257},
            "size":{
              "width":170,
              "height":24},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f288aff311634605974fd2e3589e0425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":590,
                  "y":257},
                "size":{
                  "width":170,
                  "height":24},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口-1_1/u8.png"}},
{
          "id":"e8a05e4918834738a0d1919517080498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1062,
              "y":268},
            "size":{
              "width":80,
              "height":30},
            "rotation":"15",
            "textRotation":"15",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d575d6828e0a4852b9040341a3678e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1062,
                  "y":268},
                "size":{
                  "width":80,
                  "height":30},
                "rotation":"15",
                "textRotation":"15",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划-2/u10.png"}},
{
          "id":"7aac6e908c5640a4b82aa85b7057e1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":644,
              "y":283},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5bc252a7d50482db3627fe841731741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":644,
                  "y":283},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1266e81d7394715ad4c16627f29d556",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":1070,
              "y":300},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2ad000a2fdd46ef94dacc9f0e8801cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":1070,
                  "y":300},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71d57562257a45158246f8f4c60b3425",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":264},
            "size":{
              "width":733,
              "height":10},
            "rotation":"1",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/复诊-圈划缝线/u16_line.png"}},
{
          "id":"953b0d4747da499497de4de40e438e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":1170,
              "y":78},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f98b8c3d3964313a57a04527a534581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":1170,
                  "y":78},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/复诊-上次比对/u12.png"}},
{
          "id":"0570ef54ed5841b2b8aad3e4f4442c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":530,
              "y":70},
            "size":{
              "width":530,
              "height":50},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"505e320ac6824372b11a182cf29aba78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":530,
                  "y":70},
                "size":{
                  "width":530,
                  "height":50},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后_3/u10.png"}},
{
          "id":"1716da0c283c4a3b8df9dcf67b33ba54",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":90},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拍摄后_1/u12_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ea7a8d477c64f7c88da102c6050e0c1":{
      "scriptId":"u0"},
    "747c4005fe92445f98ea10e6f7e17a12":{
      "scriptId":"u1"},
    "e83227065ed9461e9123c86dc2118bc0":{
      "scriptId":"u2"},
    "5da8412b8a1a4e2c9e15d999ba9cf033":{
      "scriptId":"u3"},
    "84d95bdaa7244906a7900b691392de69":{
      "scriptId":"u4"},
    "8fdf221b18e349a39a500f662d06b2c0":{
      "scriptId":"u5"},
    "273a1f29afff411cbe6cd4674720e506":{
      "scriptId":"u6"},
    "ffbf8602dfbc4ca6869c2c8ef3240b2c":{
      "scriptId":"u7"},
    "3810b83c1f9346319bad75cd585ef493":{
      "scriptId":"u8"},
    "f288aff311634605974fd2e3589e0425":{
      "scriptId":"u9"},
    "e8a05e4918834738a0d1919517080498":{
      "scriptId":"u10"},
    "d575d6828e0a4852b9040341a3678e1d":{
      "scriptId":"u11"},
    "7aac6e908c5640a4b82aa85b7057e1b1":{
      "scriptId":"u12"},
    "f5bc252a7d50482db3627fe841731741":{
      "scriptId":"u13"},
    "b1266e81d7394715ad4c16627f29d556":{
      "scriptId":"u14"},
    "b2ad000a2fdd46ef94dacc9f0e8801cf":{
      "scriptId":"u15"},
    "71d57562257a45158246f8f4c60b3425":{
      "scriptId":"u16"},
    "953b0d4747da499497de4de40e438e23":{
      "scriptId":"u17"},
    "2f98b8c3d3964313a57a04527a534581":{
      "scriptId":"u18"},
    "0570ef54ed5841b2b8aad3e4f4442c6b":{
      "scriptId":"u19"},
    "505e320ac6824372b11a182cf29aba78":{
      "scriptId":"u20"},
    "1716da0c283c4a3b8df9dcf67b33ba54":{
      "scriptId":"u21"}}});