$axure.loadCurrentPage({
  "url":"伤口记录.html",
  "generationDate":new Date(1524492033799.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e11761ef17d74c97af1a767c0f34908b",
    "type":"Axure:Page",
    "name":"伤口记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e015ada2557c4114a15497dea7f823d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eff01cb5c8f49e9986ab8a0b995ce2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"e32ea55bdadf41bb81b724ce19c0cc8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bbdaebd6df64736abb1aac73f3447a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"fee4ceddf1ee461d8727264af0aecbb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eedfc27a9104fbf8c95d6d2371fed11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"bd6bb12ca4e14f7f812de640d4884536",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1707c569a53b4e43bdf89f02c1983343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"974a410a9a4c49da8695c8a50005e14f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1b98bd73c6841c388bb36736fa67118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"0513ddbc8ea84040a45af96d51201d2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6432aaea6c146459cf01c218bdf52e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"071a8edd060a4f17817b94f7060a5a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":291},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac4e6072e3948f5b7e83932ebf2d201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":291},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u16.png"}},
{
          "id":"f7dec6f5deca4cb088af167566f879a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97f55a3846a4bf08de8a9710b3d1eef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3affb2270fe41e28a9803f167b61163",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc103f9a2044a7ca21c61039607b6a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7bf82fe15ef4f90a63848ba96812b89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae36a91e4ab45c5885ffb5b8fca8d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u36.png"}},
{
          "id":"567953ead9a543698f16298b581eae48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebb2e6812b5d4426917c4668a6459d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ceabc410bdc04ef49aeb1a3376345ad2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc883dc26aa94e15ac6a9064fb2a6186",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"79b903e4b03d4e9c8b6e07d8075ca53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27ad2478992440da0fad1d461a711a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f25b6561ce84bbfb012508ff1427553",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"246856f0af4b41cbb4bbca7df7212f61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"a0047820b52e48c0a7bb8f05bba74a74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a09a6176e44158ab27f1f98bebba1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c44b69bca53d436fb622f913b3dbf9b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"19px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":305},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a645c45f7d9b420baff5ceaaf1e3b9b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"19px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":305},
                "size":{
                  "width":157,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1429a1468874894ab6c69a23d038d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":172},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d166f6c4d8de4d5795e3af18b522b4c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":172},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b36f36733de2400f860c702d3de438ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6da1a420020d433eb2ac32d97ed1e65f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"7f04ba3bf4a44fca9d4f8c09a36078c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb4746a5183461ea6de0a83e708819a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u36.png"}},
{
          "id":"f82249b009dd4692af7307d953372060",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":254},
            "size":{
              "width":157,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d37f1bf48d44654a035357b0d955129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":254},
                "size":{
                  "width":157,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ede3b267d5ff45bc9c085faf82999884",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":349},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a014c49ffbf0438491f86df70dc69415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":349},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u16.png"}},
{
          "id":"fa1ba22ee31a4fbd8bb29c50adbbee24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"19px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":363},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7edcdbf59fe3433e874536372f18eb35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"19px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":363},
                "size":{
                  "width":157,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f53312c2daf4d128abec155da82a25d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":303.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba54e7131fd43109195dddb0deb503f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":303.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u44.png"}},
{
          "id":"670d509c997b40f7959ce2e1fa1e83a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":359.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed3ba9a105c4455a3b8ddb66147b4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":359.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u46.png"}},
{
          "id":"d7f87186c17b47a4bfc2cf0c0f4efdfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":417,
              "y":415},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"784a00efc4d747f586249c9738b46a86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":417,
                  "y":415},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"838fdf89accf4abdb04c08fd39bc261b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":415},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4480525ed2c245979a2a068d7aab6519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":415},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d559aab3fb0440faccd39ce89648ce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":928,
              "y":415},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017146234e764d3caa2972e6eb065768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":928,
                  "y":415},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26d16b1a47f64d80a4aba9d5ab41cff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":417,
              "y":450},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2f159165d840efa1df89a0d4e79c0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":417,
                  "y":450},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6eecfd409884696acd73b6be3194b9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":450},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a94b6e6767714bfa9dbfbb6e981e72ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":450},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c570db47b9044ad9cb7569805aaf95a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":928,
              "y":450},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f15166893b423990cee1835085851b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":928,
                  "y":450},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b70d3a32f374184b708a41fa680b787",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":417,
              "y":485},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e668ab4aacf497c85333384e9533ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":417,
                  "y":485},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2be397dfdea24115b4b82a82f2004f1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":485},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1831b04fa74913b1947d8300ad5018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":485},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d191876814d46fdbd0b4c3c38a22032",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":928,
              "y":485},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2bfbdc78224e30877208d49f1b1f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":928,
                  "y":485},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"068009d969e0469ab98eec78e356d740",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":417,
              "y":520},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d09706d742f491ca0076869d4800c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":417,
                  "y":520},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac4ffb1b6b174c258e718ca2c96dd5fa",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":418},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7805b1a1462c44b498b4bd38164cac9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":418},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6dcc42ed78ab41968edffa47bf176ada",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":453},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c520744c18d46f9bc0176f53549d6a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":453},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ee06e10bbc7a41d692bd5967b1436364",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":488},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88f98b5c6f644625a67d208354ad2d66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":488},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"07be2408bfd8443489181a8d91a2ca00",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":523},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4494cc76370642e4bd3d4bc4c1b1a0d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":523},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"555ee8b8e28e4483b7ba320b5be55049",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":637,
              "y":418},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b1d6b34b7f4da69a7675c0f3932e41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":637,
                  "y":418},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1df7e1722b6d44cf92288df04c46f63a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":637,
              "y":453},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"677be93c3d604d22bea26a9c333857b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":637,
                  "y":453},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"71703cbd6e2549bfacc55ebcb4b523a1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":637,
              "y":488},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3ec1a955354b0eb1ec9ab39bb4ede7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":637,
                  "y":488},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f90d8e0ddee640ac8607b9cac94fb000",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":637,
              "y":523},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b5173cbad8e420baa751ee504ecc978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":637,
                  "y":523},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"632649727b044a40afafa9e37a503a1d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":904,
              "y":418},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b6a350b37b4edd93fa0eeb2db09997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":904,
                  "y":418},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6a6265c8f945428198e23e9e11d6aa79",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":904,
              "y":453},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5318b579cac458b8e44611de3eb4a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":904,
                  "y":453},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e86b5cf95a8b401cb1b5482787c299e2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":904,
              "y":488},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45d0aec96b344df86ae8acf39cea122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":904,
                  "y":488},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"df9bb02339824898be433657a435cfe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":557},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa5822d26d2452795b402b8ab90943f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":557},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u16.png"}},
{
          "id":"06fa7505bf0e42f29a9be9dae30dd975",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"19px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":571},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76482581533f43dea0d133d7415d51eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"19px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":571},
                "size":{
                  "width":157,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e00073c6618f4fe7953bb46745a96295",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":570},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c94f15ae1a7a4073983e2e6bc5927e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":570},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u44.png"}},
{
          "id":"d73153bc0aa54678a4899d3710dc2936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":618},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0cc5b6bca824358b2bad4fc8208bd44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":618},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u16.png"}},
{
          "id":"880b334d7a8c494a8a410d171fa59602",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"19px",
            "fontWeight":"700",
            "location":{
              "x":391,
              "y":632},
            "size":{
              "width":302,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b37509d1dba430aaf04fc405731268c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"19px",
                "fontWeight":"700",
                "location":{
                  "x":391,
                  "y":632},
                "size":{
                  "width":302,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73557d6a66e54cadaf1b1d9b94fa70f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":396,
              "y":680},
            "size":{
              "width":164,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0668799e75204458928a748eb6851ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":396,
                  "y":680},
                "size":{
                  "width":164,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cc7fd72da0342a898e29c65aeb86050",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":550,
              "y":682},
            "size":{
              "width":550,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"3a5ac08775194bfdaa7e28b007ab47d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":396,
              "y":717},
            "size":{
              "width":164,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02d181c4dd704021bc9d8081571fcd15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":396,
                  "y":717},
                "size":{
                  "width":164,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6011e1b4236a42b5b22a772bc3bd85d3",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":550,
              "y":720},
            "size":{
              "width":550,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"635c604e2d6b446bbb7e22cb01cc3d45",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":644,
              "y":1005},
            "size":{
              "width":188,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口测量",
                      "target":{
                        "targetType":"page",
                        "url":"伤口测量.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7e1ee2799aab4b83b7385bd139d21ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":80,
              "y":326},
            "size":{
              "width":140,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96cbf22ca9064342b0ea6708250126c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":80,
                  "y":326},
                "size":{
                  "width":140,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db97149899b34197bdca87dc874a8b29",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":517},
            "size":{
              "width":192,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"b306c50fe6974da7b0451753826c1ed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770.5,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2ed4e1dfe648189d741efdf4f050f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770.5,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6889ac15ee424eecb48c4ef6f0924df7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5898a8ca6d4046e2bc1da7cd6e30c7a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ebba258436443599ea0e9dc509e828a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ec3ed8ddd34865a04c9e003aee2ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e015ada2557c4114a15497dea7f823d4":{
      "scriptId":"u0"},
    "7eff01cb5c8f49e9986ab8a0b995ce2b":{
      "scriptId":"u1"},
    "e32ea55bdadf41bb81b724ce19c0cc8c":{
      "scriptId":"u2"},
    "8bbdaebd6df64736abb1aac73f3447a8":{
      "scriptId":"u3"},
    "fee4ceddf1ee461d8727264af0aecbb0":{
      "scriptId":"u4"},
    "5eedfc27a9104fbf8c95d6d2371fed11":{
      "scriptId":"u5"},
    "bd6bb12ca4e14f7f812de640d4884536":{
      "scriptId":"u6"},
    "1707c569a53b4e43bdf89f02c1983343":{
      "scriptId":"u7"},
    "974a410a9a4c49da8695c8a50005e14f":{
      "scriptId":"u8"},
    "a1b98bd73c6841c388bb36736fa67118":{
      "scriptId":"u9"},
    "0513ddbc8ea84040a45af96d51201d2e":{
      "scriptId":"u10"},
    "e6432aaea6c146459cf01c218bdf52e0":{
      "scriptId":"u11"},
    "071a8edd060a4f17817b94f7060a5a9f":{
      "scriptId":"u12"},
    "5ac4e6072e3948f5b7e83932ebf2d201":{
      "scriptId":"u13"},
    "f7dec6f5deca4cb088af167566f879a2":{
      "scriptId":"u14"},
    "c97f55a3846a4bf08de8a9710b3d1eef":{
      "scriptId":"u15"},
    "c3affb2270fe41e28a9803f167b61163":{
      "scriptId":"u16"},
    "4cc103f9a2044a7ca21c61039607b6a1":{
      "scriptId":"u17"},
    "d7bf82fe15ef4f90a63848ba96812b89":{
      "scriptId":"u18"},
    "5ae36a91e4ab45c5885ffb5b8fca8d79":{
      "scriptId":"u19"},
    "567953ead9a543698f16298b581eae48":{
      "scriptId":"u20"},
    "ebb2e6812b5d4426917c4668a6459d20":{
      "scriptId":"u21"},
    "ceabc410bdc04ef49aeb1a3376345ad2":{
      "scriptId":"u22"},
    "cc883dc26aa94e15ac6a9064fb2a6186":{
      "scriptId":"u23"},
    "79b903e4b03d4e9c8b6e07d8075ca53d":{
      "scriptId":"u24"},
    "e27ad2478992440da0fad1d461a711a0":{
      "scriptId":"u25"},
    "6f25b6561ce84bbfb012508ff1427553":{
      "scriptId":"u26"},
    "246856f0af4b41cbb4bbca7df7212f61":{
      "scriptId":"u27"},
    "a0047820b52e48c0a7bb8f05bba74a74":{
      "scriptId":"u28"},
    "23a09a6176e44158ab27f1f98bebba1e":{
      "scriptId":"u29"},
    "c44b69bca53d436fb622f913b3dbf9b2":{
      "scriptId":"u30"},
    "a645c45f7d9b420baff5ceaaf1e3b9b8":{
      "scriptId":"u31"},
    "b1429a1468874894ab6c69a23d038d8a":{
      "scriptId":"u32"},
    "d166f6c4d8de4d5795e3af18b522b4c8":{
      "scriptId":"u33"},
    "b36f36733de2400f860c702d3de438ca":{
      "scriptId":"u34"},
    "6da1a420020d433eb2ac32d97ed1e65f":{
      "scriptId":"u35"},
    "7f04ba3bf4a44fca9d4f8c09a36078c3":{
      "scriptId":"u36"},
    "abb4746a5183461ea6de0a83e708819a":{
      "scriptId":"u37"},
    "f82249b009dd4692af7307d953372060":{
      "scriptId":"u38"},
    "0d37f1bf48d44654a035357b0d955129":{
      "scriptId":"u39"},
    "ede3b267d5ff45bc9c085faf82999884":{
      "scriptId":"u40"},
    "a014c49ffbf0438491f86df70dc69415":{
      "scriptId":"u41"},
    "fa1ba22ee31a4fbd8bb29c50adbbee24":{
      "scriptId":"u42"},
    "7edcdbf59fe3433e874536372f18eb35":{
      "scriptId":"u43"},
    "6f53312c2daf4d128abec155da82a25d":{
      "scriptId":"u44"},
    "5ba54e7131fd43109195dddb0deb503f":{
      "scriptId":"u45"},
    "670d509c997b40f7959ce2e1fa1e83a1":{
      "scriptId":"u46"},
    "8ed3ba9a105c4455a3b8ddb66147b4c7":{
      "scriptId":"u47"},
    "d7f87186c17b47a4bfc2cf0c0f4efdfa":{
      "scriptId":"u48"},
    "784a00efc4d747f586249c9738b46a86":{
      "scriptId":"u49"},
    "838fdf89accf4abdb04c08fd39bc261b":{
      "scriptId":"u50"},
    "4480525ed2c245979a2a068d7aab6519":{
      "scriptId":"u51"},
    "2d559aab3fb0440faccd39ce89648ce7":{
      "scriptId":"u52"},
    "017146234e764d3caa2972e6eb065768":{
      "scriptId":"u53"},
    "26d16b1a47f64d80a4aba9d5ab41cff0":{
      "scriptId":"u54"},
    "8f2f159165d840efa1df89a0d4e79c0e":{
      "scriptId":"u55"},
    "b6eecfd409884696acd73b6be3194b9d":{
      "scriptId":"u56"},
    "a94b6e6767714bfa9dbfbb6e981e72ca":{
      "scriptId":"u57"},
    "9c570db47b9044ad9cb7569805aaf95a":{
      "scriptId":"u58"},
    "c1f15166893b423990cee1835085851b":{
      "scriptId":"u59"},
    "5b70d3a32f374184b708a41fa680b787":{
      "scriptId":"u60"},
    "9e668ab4aacf497c85333384e9533ee9":{
      "scriptId":"u61"},
    "2be397dfdea24115b4b82a82f2004f1a":{
      "scriptId":"u62"},
    "ae1831b04fa74913b1947d8300ad5018":{
      "scriptId":"u63"},
    "9d191876814d46fdbd0b4c3c38a22032":{
      "scriptId":"u64"},
    "3b2bfbdc78224e30877208d49f1b1f18":{
      "scriptId":"u65"},
    "068009d969e0469ab98eec78e356d740":{
      "scriptId":"u66"},
    "3d09706d742f491ca0076869d4800c09":{
      "scriptId":"u67"},
    "ac4ffb1b6b174c258e718ca2c96dd5fa":{
      "scriptId":"u68"},
    "7805b1a1462c44b498b4bd38164cac9d":{
      "scriptId":"u69"},
    "6dcc42ed78ab41968edffa47bf176ada":{
      "scriptId":"u70"},
    "2c520744c18d46f9bc0176f53549d6a2":{
      "scriptId":"u71"},
    "ee06e10bbc7a41d692bd5967b1436364":{
      "scriptId":"u72"},
    "88f98b5c6f644625a67d208354ad2d66":{
      "scriptId":"u73"},
    "07be2408bfd8443489181a8d91a2ca00":{
      "scriptId":"u74"},
    "4494cc76370642e4bd3d4bc4c1b1a0d4":{
      "scriptId":"u75"},
    "555ee8b8e28e4483b7ba320b5be55049":{
      "scriptId":"u76"},
    "e9b1d6b34b7f4da69a7675c0f3932e41":{
      "scriptId":"u77"},
    "1df7e1722b6d44cf92288df04c46f63a":{
      "scriptId":"u78"},
    "677be93c3d604d22bea26a9c333857b7":{
      "scriptId":"u79"},
    "71703cbd6e2549bfacc55ebcb4b523a1":{
      "scriptId":"u80"},
    "3f3ec1a955354b0eb1ec9ab39bb4ede7":{
      "scriptId":"u81"},
    "f90d8e0ddee640ac8607b9cac94fb000":{
      "scriptId":"u82"},
    "4b5173cbad8e420baa751ee504ecc978":{
      "scriptId":"u83"},
    "632649727b044a40afafa9e37a503a1d":{
      "scriptId":"u84"},
    "a3b6a350b37b4edd93fa0eeb2db09997":{
      "scriptId":"u85"},
    "6a6265c8f945428198e23e9e11d6aa79":{
      "scriptId":"u86"},
    "e5318b579cac458b8e44611de3eb4a09":{
      "scriptId":"u87"},
    "e86b5cf95a8b401cb1b5482787c299e2":{
      "scriptId":"u88"},
    "d45d0aec96b344df86ae8acf39cea122":{
      "scriptId":"u89"},
    "df9bb02339824898be433657a435cfe3":{
      "scriptId":"u90"},
    "ffa5822d26d2452795b402b8ab90943f":{
      "scriptId":"u91"},
    "06fa7505bf0e42f29a9be9dae30dd975":{
      "scriptId":"u92"},
    "76482581533f43dea0d133d7415d51eb":{
      "scriptId":"u93"},
    "e00073c6618f4fe7953bb46745a96295":{
      "scriptId":"u94"},
    "c94f15ae1a7a4073983e2e6bc5927e02":{
      "scriptId":"u95"},
    "d73153bc0aa54678a4899d3710dc2936":{
      "scriptId":"u96"},
    "e0cc5b6bca824358b2bad4fc8208bd44":{
      "scriptId":"u97"},
    "880b334d7a8c494a8a410d171fa59602":{
      "scriptId":"u98"},
    "5b37509d1dba430aaf04fc405731268c":{
      "scriptId":"u99"},
    "73557d6a66e54cadaf1b1d9b94fa70f0":{
      "scriptId":"u100"},
    "0668799e75204458928a748eb6851ea0":{
      "scriptId":"u101"},
    "5cc7fd72da0342a898e29c65aeb86050":{
      "scriptId":"u102"},
    "3a5ac08775194bfdaa7e28b007ab47d1":{
      "scriptId":"u103"},
    "02d181c4dd704021bc9d8081571fcd15":{
      "scriptId":"u104"},
    "6011e1b4236a42b5b22a772bc3bd85d3":{
      "scriptId":"u105"},
    "635c604e2d6b446bbb7e22cb01cc3d45":{
      "scriptId":"u106"},
    "7e1ee2799aab4b83b7385bd139d21ea1":{
      "scriptId":"u107"},
    "96cbf22ca9064342b0ea6708250126c9":{
      "scriptId":"u108"},
    "db97149899b34197bdca87dc874a8b29":{
      "scriptId":"u109"},
    "b306c50fe6974da7b0451753826c1ed7":{
      "scriptId":"u110"},
    "cc2ed4e1dfe648189d741efdf4f050f0":{
      "scriptId":"u111"},
    "6889ac15ee424eecb48c4ef6f0924df7":{
      "scriptId":"u112"},
    "5898a8ca6d4046e2bc1da7cd6e30c7a9":{
      "scriptId":"u113"},
    "9ebba258436443599ea0e9dc509e828a":{
      "scriptId":"u114"},
    "17ec3ed8ddd34865a04c9e003aee2ff4":{
      "scriptId":"u115"}}});