$axure.loadCurrentPage({
  "url":"测算.html",
  "generationDate":new Date(1524492035009.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8e1a815e643c43258bf1b215876d8a39",
    "type":"Axure:Page",
    "name":"测算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23f4460a026642a4b96b0f362d7bcd0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e6e69df104545678266f60990abd34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"a42dae3a9c9743f7ac5a585b2a610cd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f8a5f4dd9f49d98fa58d8eb431878f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"26839fac93b74136973e1477b721cd1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":675}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7dbddf4666c4410aeedebf0b132fc69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":675}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算/u4.png"}},
{
          "id":"da6fa502a70245c4b9e410741fddd35c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6996584f69ed483c9572ab78ae1e1865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"5ec61a54e1d54aa492b4f0c0d11abdfe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":48},
            "size":{
              "width":1019,
              "height":583},
            "cornerRadiusTopLeft":"26"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1a2daf7f664c738aeee42df8fc2113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":48},
                "size":{
                  "width":1019,
                  "height":583},
                "cornerRadiusTopLeft":"26"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测算/u8.png"}},
{
          "id":"bfb735b9c77c48fab796bfcc439db193",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":870,
              "y":270},
            "size":{
              "width":110,
              "height":80},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0480be5845b843369a3ca250d30157f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":870,
                  "y":270},
                "size":{
                  "width":110,
                  "height":80},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口/u10.png"}},
{
          "id":"51300d66feae49719d49d755afac97ee",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":78},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录入",
                      "target":{
                        "targetType":"page",
                        "url":"录入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6a293ab735474c58b93acefaa7faa8a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":641},
            "size":{
              "width":380,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e68e443d57a4803849392412b5af875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":641},
                "size":{
                  "width":380,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc6a91dd21b4417289df68af6ed45b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":602,
              "y":641},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c16d71bfdea44d7aac9c60029f7a91bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":602,
                  "y":641},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6db23c903c4e3ba8571d8f7d93ba1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":894,
              "y":241},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08d697a23204f86bb51be8dea8c3c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":894,
                  "y":241},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5eca98628cd45fe86e5e4c613c56565",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":636,
              "y":641},
            "size":{
              "width":571,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35318ef8762746a2bd7555df883d837e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":636,
                  "y":641},
                "size":{
                  "width":571,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "23f4460a026642a4b96b0f362d7bcd0a":{
      "scriptId":"u0"},
    "2e6e69df104545678266f60990abd34a":{
      "scriptId":"u1"},
    "a42dae3a9c9743f7ac5a585b2a610cd6":{
      "scriptId":"u2"},
    "c9f8a5f4dd9f49d98fa58d8eb431878f":{
      "scriptId":"u3"},
    "26839fac93b74136973e1477b721cd1b":{
      "scriptId":"u4"},
    "f7dbddf4666c4410aeedebf0b132fc69":{
      "scriptId":"u5"},
    "da6fa502a70245c4b9e410741fddd35c":{
      "scriptId":"u6"},
    "6996584f69ed483c9572ab78ae1e1865":{
      "scriptId":"u7"},
    "5ec61a54e1d54aa492b4f0c0d11abdfe":{
      "scriptId":"u8"},
    "9d1a2daf7f664c738aeee42df8fc2113":{
      "scriptId":"u9"},
    "bfb735b9c77c48fab796bfcc439db193":{
      "scriptId":"u10"},
    "0480be5845b843369a3ca250d30157f7":{
      "scriptId":"u11"},
    "51300d66feae49719d49d755afac97ee":{
      "scriptId":"u12"},
    "6a293ab735474c58b93acefaa7faa8a6":{
      "scriptId":"u13"},
    "5e68e443d57a4803849392412b5af875":{
      "scriptId":"u14"},
    "fc6a91dd21b4417289df68af6ed45b01":{
      "scriptId":"u15"},
    "c16d71bfdea44d7aac9c60029f7a91bf":{
      "scriptId":"u16"},
    "9a6db23c903c4e3ba8571d8f7d93ba1d":{
      "scriptId":"u17"},
    "b08d697a23204f86bb51be8dea8c3c29":{
      "scriptId":"u18"},
    "b5eca98628cd45fe86e5e4c613c56565":{
      "scriptId":"u19"},
    "35318ef8762746a2bd7555df883d837e":{
      "scriptId":"u20"}}});