$axure.loadCurrentPage({
  "url":"患者伤口信息历史.html",
  "generationDate":new Date(1524492033583.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8f955ec0d76b4863a8c3bade39480c9b",
    "type":"Axure:Page",
    "name":"患者伤口信息历史",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc2b13f5a75c420d9ec3b2268b7daa3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00e0adeeec5409c9a853581ade59797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"9bded517ac4f4eadb3ebfd8e8b11f4d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4b53a8d0d94ee4ad2926e40eb5dd6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"2fd16a39e97f4f43912d847ba541ea36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c2eea94ba2b48a4b4aaca227282f356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"5c9236f7fa5843bd84f329e362cee593",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb59f01f6f3b494a896b692e0dd8bb6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"a48f68b28a4c49d9a00cf295d5eaeb81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fbd4b7f5ede427fa2d544074d2c86ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"8b8e9af5c52c48c9b752c26a17e65869",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451ae05605514277a742cb4848191a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acfbc8f893684e529428c1dc0142f94a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":436,
              "y":266},
            "size":{
              "width":260,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261b2b57964b4604a290c52748cf405f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":266},
                "size":{
                  "width":260,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在我院进行检查",
                      "target":{
                        "targetType":"page",
                        "url":"在我院进行检查.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"661ea851371749e6a4c46e4b8b0c69c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":824,
              "y":266},
            "size":{
              "width":173,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd30c54a3ed4382abf5d56c846d0660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":824,
                  "y":266},
                "size":{
                  "width":173,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5270c569ddf4c53b69f23b56367e5c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":310},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1154bc21444e44ba842bf75e21abad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":310},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"2dd0bdc7520b47a9b8ac721b76a9e428",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":824,
              "y":309},
            "size":{
              "width":161,
              "height":1},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d37cec8ed18144d59dc9edf8d8ae3aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":824,
                  "y":309},
                "size":{
                  "width":161,
                  "height":1},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u18.png"}},
{
          "id":"b5540554ac984463bb4716541fc8ac60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a18fe30ab10481e804ab99b258c409b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56e8ea9eda2147668ac39e5607f075fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140c79d86f03475b9ffb094350f418c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u30.png"}},
{
          "id":"d151ce8f1d40402aab13a18ddc451e21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ab235a42474de08d1a9861234b6cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"c023cf72d9944d7eb1a0b7b8b4940b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"594dc340c15e485dbdee47061832584e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a550cdeda8e4309a8d56fcbe01ad29e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70673cb202df476586b3bcf2d9bcc111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u36.png"}},
{
          "id":"0d5994b38a5d4156b1b86cd3db1c6829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3440b6685545496c961b2fee9835857f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41ca26102ca0499e8f464a3b6b456e9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a365e568790e4e918ce7ccdf62068cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"d86263d573a045cbb69d6ebd9024c766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3713d6013920490db868f3980813dbd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08e32659b015461d9eb2edfb3362ff34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6735d8450e3a45a59fff0a6ee75b6799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"57879b6d29034defb090297a6e008f76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0899129489064fea9f6a8eef184809d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58fee4bbbaaf47b68ab5c9959efe02c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":322},
            "size":{
              "width":110,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"847001f004fe4b8ab9a5d6d4ab165206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":322},
                "size":{
                  "width":110,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80521cb68b464a3fb3e28d6555b5a16d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949892b9d72a4b0f86735f8c3cda80e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df8525eb894e47bebd600b4b8102dab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":363},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3e836f9158433aa821fa12ccfb2f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":363},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"f23f91956d384d32b064e3a244e2dea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":416},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dfb895fd50e45e88f7271fa172e3218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":416},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"e5dcf9f7c6d448f395bbf09e5f9deb3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":374},
            "size":{
              "width":110,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8efbe8a6f7ad425b99ea44f65361b22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":374},
                "size":{
                  "width":110,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"753aaa6760b34791b0b0c5be2d190a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":428},
            "size":{
              "width":110,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ba80cf50ed493ca0fb83de570fcd1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":428},
                "size":{
                  "width":110,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56135bb9967e47a88d478544735c1001",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":475},
            "size":{
              "width":330,
              "height":244}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e43790d9ee44099c9a8fc23883e4cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":475},
                "size":{
                  "width":330,
                  "height":244}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u52.png"}},
{
          "id":"7e6276a36986482b96663a321dc40eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":729},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e829c7bab6bb42c8909da4c751043d9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":729},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"36d220ac1b63417b9f2719901623bcdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":783},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f60caabf6e84394a366c8b9f4f96664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":783},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"f2b48c6b13c04b2b8bb0d8e780ff92e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":838},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c080a870ec6d4a11aec2fc297d556b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":838},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"0c3a44c69a8b484aae287ebfadce10d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":893},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a175fa64055b4503b24e0465f00bf38e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":893},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"5224f7cb55b1474eb3323511fd30d233",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":351,
              "y":948},
            "size":{
              "width":774,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272f2739be3841ba8b80cd74afd54352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":351,
                  "y":948},
                "size":{
                  "width":774,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u16.png"}},
{
          "id":"8987dcaffb5d46bb95c0b3ddb0bddf49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":740},
            "size":{
              "width":270,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0064e6d70442c4af61da9ed6eb93ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":740},
                "size":{
                  "width":270,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a75b8be1b1d43bca370d33dfbfcf19a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":760,
              "y":740},
            "size":{
              "width":320,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"141a921f1dc74bfab6fa60059483b85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":760,
                  "y":740},
                "size":{
                  "width":320,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8f7c6181c6e4e9491ed4cd029297830",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":794},
            "size":{
              "width":310,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e1c46f2e504af895f6f9048ef421e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":794},
                "size":{
                  "width":310,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e47e1b255df42179d39451a039c90f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":760,
              "y":794},
            "size":{
              "width":320,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0e46c5dfd242e583d5fe2ebf1832cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":760,
                  "y":794},
                "size":{
                  "width":320,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d24759b58adb48699d96127fcf975596",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":850},
            "size":{
              "width":270,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4bc11fb26e494bb07c0a48a967969d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":850},
                "size":{
                  "width":270,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"973ed6d86998496f97dfd861a2c42ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":904},
            "size":{
              "width":270,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d723c87fa5d4ffb93d00d189563b489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":904},
                "size":{
                  "width":270,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b00f07ff90e48eeb5f69ccbc189c2b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":760,
              "y":904},
            "size":{
              "width":320,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18fbc33bfb164636b405ef6777cbf035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":760,
                  "y":904},
                "size":{
                  "width":320,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f37a202b3b443caa0e9819f8cc6588d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":960},
            "size":{
              "width":270,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd90a2d9c86d45edbbbbb2d225984fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":960},
                "size":{
                  "width":270,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92bf5d183b50424db1800fde66a543e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":760,
              "y":960},
            "size":{
              "width":320,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43466cf6db8f489aa8ba2e56d94b4983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":760,
                  "y":960},
                "size":{
                  "width":320,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4fb5d4e3ea94d2cbb3c564538c4486f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c7983fa43ad43deb29c564634539aac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a98fc29c0d44adbba1128278467b970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":488,
              "y":322},
            "size":{
              "width":260,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"385b947f47a948b78b8e302cf8f1192a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":322},
                "size":{
                  "width":260,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在我院进行检查",
                      "target":{
                        "targetType":"page",
                        "url":"在我院进行检查.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fdec2b31b0b48509aa324db72328c58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":488,
              "y":374},
            "size":{
              "width":200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6adb8134ad4414f83ffc312c86f28d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":374},
                "size":{
                  "width":200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f50578d20b144e195e4a38180155b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1059},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d2cc59ae5d140889f417b9dd148a4b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1059},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13c31300e98e4f51bfc7a85b2b3f2777",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":927,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4250acb2d6fd436fbb6a4b972a7f62c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":927,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fc2b13f5a75c420d9ec3b2268b7daa3d":{
      "scriptId":"u0"},
    "e00e0adeeec5409c9a853581ade59797":{
      "scriptId":"u1"},
    "9bded517ac4f4eadb3ebfd8e8b11f4d9":{
      "scriptId":"u2"},
    "3a4b53a8d0d94ee4ad2926e40eb5dd6a":{
      "scriptId":"u3"},
    "2fd16a39e97f4f43912d847ba541ea36":{
      "scriptId":"u4"},
    "8c2eea94ba2b48a4b4aaca227282f356":{
      "scriptId":"u5"},
    "5c9236f7fa5843bd84f329e362cee593":{
      "scriptId":"u6"},
    "cb59f01f6f3b494a896b692e0dd8bb6b":{
      "scriptId":"u7"},
    "a48f68b28a4c49d9a00cf295d5eaeb81":{
      "scriptId":"u8"},
    "2fbd4b7f5ede427fa2d544074d2c86ee":{
      "scriptId":"u9"},
    "8b8e9af5c52c48c9b752c26a17e65869":{
      "scriptId":"u10"},
    "451ae05605514277a742cb4848191a78":{
      "scriptId":"u11"},
    "acfbc8f893684e529428c1dc0142f94a":{
      "scriptId":"u12"},
    "261b2b57964b4604a290c52748cf405f":{
      "scriptId":"u13"},
    "661ea851371749e6a4c46e4b8b0c69c4":{
      "scriptId":"u14"},
    "0fd30c54a3ed4382abf5d56c846d0660":{
      "scriptId":"u15"},
    "a5270c569ddf4c53b69f23b56367e5c8":{
      "scriptId":"u16"},
    "cb1154bc21444e44ba842bf75e21abad":{
      "scriptId":"u17"},
    "2dd0bdc7520b47a9b8ac721b76a9e428":{
      "scriptId":"u18"},
    "d37cec8ed18144d59dc9edf8d8ae3aa7":{
      "scriptId":"u19"},
    "b5540554ac984463bb4716541fc8ac60":{
      "scriptId":"u20"},
    "9a18fe30ab10481e804ab99b258c409b":{
      "scriptId":"u21"},
    "56e8ea9eda2147668ac39e5607f075fb":{
      "scriptId":"u22"},
    "140c79d86f03475b9ffb094350f418c2":{
      "scriptId":"u23"},
    "d151ce8f1d40402aab13a18ddc451e21":{
      "scriptId":"u24"},
    "86ab235a42474de08d1a9861234b6cda":{
      "scriptId":"u25"},
    "c023cf72d9944d7eb1a0b7b8b4940b8f":{
      "scriptId":"u26"},
    "594dc340c15e485dbdee47061832584e":{
      "scriptId":"u27"},
    "9a550cdeda8e4309a8d56fcbe01ad29e":{
      "scriptId":"u28"},
    "70673cb202df476586b3bcf2d9bcc111":{
      "scriptId":"u29"},
    "0d5994b38a5d4156b1b86cd3db1c6829":{
      "scriptId":"u30"},
    "3440b6685545496c961b2fee9835857f":{
      "scriptId":"u31"},
    "41ca26102ca0499e8f464a3b6b456e9a":{
      "scriptId":"u32"},
    "a365e568790e4e918ce7ccdf62068cc6":{
      "scriptId":"u33"},
    "d86263d573a045cbb69d6ebd9024c766":{
      "scriptId":"u34"},
    "3713d6013920490db868f3980813dbd3":{
      "scriptId":"u35"},
    "08e32659b015461d9eb2edfb3362ff34":{
      "scriptId":"u36"},
    "6735d8450e3a45a59fff0a6ee75b6799":{
      "scriptId":"u37"},
    "57879b6d29034defb090297a6e008f76":{
      "scriptId":"u38"},
    "0899129489064fea9f6a8eef184809d3":{
      "scriptId":"u39"},
    "58fee4bbbaaf47b68ab5c9959efe02c1":{
      "scriptId":"u40"},
    "847001f004fe4b8ab9a5d6d4ab165206":{
      "scriptId":"u41"},
    "80521cb68b464a3fb3e28d6555b5a16d":{
      "scriptId":"u42"},
    "949892b9d72a4b0f86735f8c3cda80e8":{
      "scriptId":"u43"},
    "df8525eb894e47bebd600b4b8102dab2":{
      "scriptId":"u44"},
    "ed3e836f9158433aa821fa12ccfb2f0a":{
      "scriptId":"u45"},
    "f23f91956d384d32b064e3a244e2dea2":{
      "scriptId":"u46"},
    "9dfb895fd50e45e88f7271fa172e3218":{
      "scriptId":"u47"},
    "e5dcf9f7c6d448f395bbf09e5f9deb3a":{
      "scriptId":"u48"},
    "8efbe8a6f7ad425b99ea44f65361b22b":{
      "scriptId":"u49"},
    "753aaa6760b34791b0b0c5be2d190a45":{
      "scriptId":"u50"},
    "e1ba80cf50ed493ca0fb83de570fcd1f":{
      "scriptId":"u51"},
    "56135bb9967e47a88d478544735c1001":{
      "scriptId":"u52"},
    "f7e43790d9ee44099c9a8fc23883e4cd":{
      "scriptId":"u53"},
    "7e6276a36986482b96663a321dc40eec":{
      "scriptId":"u54"},
    "e829c7bab6bb42c8909da4c751043d9e":{
      "scriptId":"u55"},
    "36d220ac1b63417b9f2719901623bcdf":{
      "scriptId":"u56"},
    "3f60caabf6e84394a366c8b9f4f96664":{
      "scriptId":"u57"},
    "f2b48c6b13c04b2b8bb0d8e780ff92e1":{
      "scriptId":"u58"},
    "c080a870ec6d4a11aec2fc297d556b7c":{
      "scriptId":"u59"},
    "0c3a44c69a8b484aae287ebfadce10d0":{
      "scriptId":"u60"},
    "a175fa64055b4503b24e0465f00bf38e":{
      "scriptId":"u61"},
    "5224f7cb55b1474eb3323511fd30d233":{
      "scriptId":"u62"},
    "272f2739be3841ba8b80cd74afd54352":{
      "scriptId":"u63"},
    "8987dcaffb5d46bb95c0b3ddb0bddf49":{
      "scriptId":"u64"},
    "1b0064e6d70442c4af61da9ed6eb93ae":{
      "scriptId":"u65"},
    "9a75b8be1b1d43bca370d33dfbfcf19a":{
      "scriptId":"u66"},
    "141a921f1dc74bfab6fa60059483b85c":{
      "scriptId":"u67"},
    "d8f7c6181c6e4e9491ed4cd029297830":{
      "scriptId":"u68"},
    "d1e1c46f2e504af895f6f9048ef421e5":{
      "scriptId":"u69"},
    "3e47e1b255df42179d39451a039c90f3":{
      "scriptId":"u70"},
    "1d0e46c5dfd242e583d5fe2ebf1832cb":{
      "scriptId":"u71"},
    "d24759b58adb48699d96127fcf975596":{
      "scriptId":"u72"},
    "0d4bc11fb26e494bb07c0a48a967969d":{
      "scriptId":"u73"},
    "973ed6d86998496f97dfd861a2c42ac8":{
      "scriptId":"u74"},
    "0d723c87fa5d4ffb93d00d189563b489":{
      "scriptId":"u75"},
    "4b00f07ff90e48eeb5f69ccbc189c2b0":{
      "scriptId":"u76"},
    "18fbc33bfb164636b405ef6777cbf035":{
      "scriptId":"u77"},
    "1f37a202b3b443caa0e9819f8cc6588d":{
      "scriptId":"u78"},
    "bd90a2d9c86d45edbbbbb2d225984fe3":{
      "scriptId":"u79"},
    "92bf5d183b50424db1800fde66a543e5":{
      "scriptId":"u80"},
    "43466cf6db8f489aa8ba2e56d94b4983":{
      "scriptId":"u81"},
    "c4fb5d4e3ea94d2cbb3c564538c4486f":{
      "scriptId":"u82"},
    "0c7983fa43ad43deb29c564634539aac":{
      "scriptId":"u83"},
    "6a98fc29c0d44adbba1128278467b970":{
      "scriptId":"u84"},
    "385b947f47a948b78b8e302cf8f1192a":{
      "scriptId":"u85"},
    "9fdec2b31b0b48509aa324db72328c58":{
      "scriptId":"u86"},
    "b6adb8134ad4414f83ffc312c86f28d2":{
      "scriptId":"u87"},
    "1f50578d20b144e195e4a38180155b11":{
      "scriptId":"u88"},
    "4d2cc59ae5d140889f417b9dd148a4b0":{
      "scriptId":"u89"},
    "13c31300e98e4f51bfc7a85b2b3f2777":{
      "scriptId":"u90"},
    "4250acb2d6fd436fbb6a4b972a7f62c9":{
      "scriptId":"u91"}}});