$axure.loadCurrentPage({
  "url":"多个临近开放性伤口.html",
  "generationDate":new Date(1524492036066),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2a3a9ddac1c44ab39867574568be8453",
    "type":"Axure:Page",
    "name":"多个临近开放性伤口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0fe52ae04a494ffcb3eed5cefecc73b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6025566e71148de835a32a33fa6573c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"c25130bca7b7483283e2dd941a201761",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":910,
              "height":675},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa7cafde5c4f40ecb30409ef5d2a0e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":910,
                  "height":675},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/多个临近开放性伤口/u2.png"}},
{
          "id":"2c966e9fba1d4d988ee8bfef265c6c2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":679},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a55a15745f0425389583d4becb307f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":679},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u4.png"}},
{
          "id":"8f7854e9ae524588b0156482bd9e273b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":359},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f8e950675d4557849c6d1844fec0c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1190,
                  "y":359},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄后_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/单个开放性伤口/u6.png"}},
{
          "id":"37d25452a1b148d8aea9cb4c14d425af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":520,
              "y":70},
            "size":{
              "width":390,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2de9b83c7e748dea9d7ab8c39508b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":520,
                  "y":70},
                "size":{
                  "width":390,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u8.png"}},
{
          "id":"e71e9a6570cf4d21b16ab2fa1c751186",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1198,
              "y":679},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e0e235c3c04857a007f646670fdac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1198,
                  "y":679},
                "size":{
                  "width":60,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7275d8ba85de41be9e8203f68fcdf66d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":682},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfaef3f780744bfa585e0c69f2c90cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":682},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"281e0497172349839779574c2911e999",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1168,
              "y":673},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"285279cf8c73426e9a71e3370e5a0bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1168,
                  "y":673},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄与测量清创前伤口",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄与测量清创前伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed6a7207841f4c229b46cc73f0e4ff2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":820},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复诊-拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"复诊-拍摄后.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0fe52ae04a494ffcb3eed5cefecc73b4":{
      "scriptId":"u0"},
    "d6025566e71148de835a32a33fa6573c":{
      "scriptId":"u1"},
    "c25130bca7b7483283e2dd941a201761":{
      "scriptId":"u2"},
    "fa7cafde5c4f40ecb30409ef5d2a0e66":{
      "scriptId":"u3"},
    "2c966e9fba1d4d988ee8bfef265c6c2e":{
      "scriptId":"u4"},
    "7a55a15745f0425389583d4becb307f2":{
      "scriptId":"u5"},
    "8f7854e9ae524588b0156482bd9e273b":{
      "scriptId":"u6"},
    "13f8e950675d4557849c6d1844fec0c0":{
      "scriptId":"u7"},
    "37d25452a1b148d8aea9cb4c14d425af":{
      "scriptId":"u8"},
    "e2de9b83c7e748dea9d7ab8c39508b5a":{
      "scriptId":"u9"},
    "e71e9a6570cf4d21b16ab2fa1c751186":{
      "scriptId":"u10"},
    "e9e0e235c3c04857a007f646670fdac3":{
      "scriptId":"u11"},
    "7275d8ba85de41be9e8203f68fcdf66d":{
      "scriptId":"u12"},
    "4bfaef3f780744bfa585e0c69f2c90cd":{
      "scriptId":"u13"},
    "281e0497172349839779574c2911e999":{
      "scriptId":"u14"},
    "285279cf8c73426e9a71e3370e5a0bbe":{
      "scriptId":"u15"},
    "ed6a7207841f4c229b46cc73f0e4ff2b":{
      "scriptId":"u16"}}});