$axure.loadCurrentPage({
  "url":"查看图片记录.html",
  "generationDate":new Date(1524492043868.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9465579c992c40969fb69745476708fc",
    "type":"Axure:Page",
    "name":"查看图片记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d6b1e2d0ad04e0799a16a091b7fbc03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3661570376e94bb98dc6017ce1c5780c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"92958d8a6a8d4760b3772bdb66d0bfda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ca4e25a8a9b42f88fd8925b6c3efa51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"2312d93cbb844b7bbf9e06f933eb4fd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff86ea6310a490896dac9acdf0435c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"3c438057c5f143bd94ceaa3fe4c8b14b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cdd45a5b84d4755a615b255102e95e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"cd82c61664e44db395707aa8c80f3826",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f6af566f3645c48771c15a1189441f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"72ee0c3ad60844ae89039cf1e76b32c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8defb15f5a0d4d0faab187854af18962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"ac34c2d861e546b59f547cf654738d46",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":1024},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"b29fdc4c76fb485ca8570f12367ff48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64810a852cab4ac6aa2e03be6ae526e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"cc6916072b6e48bfbcb9ecfc5340219b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1042f08a588a4bb8a9f8a73c40e7bbcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba42f72b837d4ef8a7d8cb7643462faa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239ee8cfd5d0458a9775bfab38f01614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"722d8555db314375881298737596a807",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb369a510164bb780da955044cbf3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a06aee15b684010b2782ebc8c0d51cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3758ef2551834bb3ab84e1b04d5d3e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06655701630044e683bc2c2c5bf942b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":873},
            "size":{
              "width":99,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f139db6018be49f68257737ed8c5cfa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":873},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u91.png"}},
{
          "id":"b86e899a40034fc9bd4c8cb221d9cb1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":909},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e1be29525d4ef989017d85e17165a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":909},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"05714c046aba4beb8b78503b76c375f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":920},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b50bf98c5c84495a4201a8bfaaf68e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":973,
                  "y":920},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"a74d4d67809e4a4e9c75399d4d644146",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":250},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96b46c1553c34881b7ee97feacb67505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":250},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"0fc1bcdc52da43969f6af857673ee1a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31fa9fb9c40641b7b76d3088bbf19936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"9ce8043dc88d464593a58fa6ed26e9ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7044feabf744816bc5ccb9b799e3b34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"575007a0e0384687966cd182cd2bf852",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f541c853d99643a2af2f2076d9693ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"2412f4d2722b4ce3a98a98dcae34e468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":374},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f59afb2358540af9ed4cc3eef8fcc28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":374},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c09b6ab83f6a4db188dfb97d5410d3f5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":364},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"914d28c935b948eb82dcf51d08df5eac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5aeceb599d44484bd20a95466da76a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd11111cc04a4553b0172f772f4148ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8caefcc579b743c39f5f2ce4db7ffe1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93fd400deb1543ff99b657e1dafd5f31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":468},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8312a11192a40a886c7c072e40cfd42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":468},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"7e8cc2bf684d4c3b82da5432d41bfac4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b33bde96c986472e9016aebd3ee9b2f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"e91ffc662fb54f9a9fa64c2ec8671f21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d3c268bf654153acb96209354d24b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"5abb7d49969e40638cccbff7a46d5d70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4edea20637d14e68990f92b9a3fe7528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"5c9f94a0f8a74a4183840aa52b9f5da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":592},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d74e36b254c4c0a83834211b4bfe9b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":592},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33bc114a4f414f098e1cd9687448a4e8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":582},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"b8c4b16b38e849b496088f215e182983",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fad315222dc40a9af6681a203c4d420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"247dcf2316c04530be50b211f085ea61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3f2ff137ca47c6a701e9cf3ed159b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"864797c6e13340fa928ec8b5d4d42536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":687},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda240e3c9724227be66f7c6ca1f96fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":687},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"4a95b16d870244509a9559c2cc51c9a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0440d757184aa39dc732eb17589b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"f78d81007f6643d1b987c5d4945fb8d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"566adafc8795479e9c154800f19b56d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"89cc7a70aff845b586eeb2dd048add0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709bc62e604d4e8aadfa2737ac0382cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"859b2a3eb4094c8eaa336c2e3aaf16bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":811},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0f913a43f04fdd9dcf41be5e54c543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":811},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a8fc0d3749d477a98f9cf9a54562825",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":801},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"1be85f54bc77451eaa58dc4726a800c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe060ac3fd37457597319d4bf5ba3374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f89c00910dd46d897e5dd425fb316eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03f2417423f641f6b4b9cf25e97f224c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0cadb270c6a4ad094528334f9c6ef3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":913},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4677ffaf08246abbf0d2f83c8768df9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":913},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"db0a67767db54e778ea42697d856296c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44047b27d0de4fd594f9509c2f06ec93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53193ee573794f2db2a72e049af0cb76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15bca30d524442618bd2c148c749cd3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53c2e5e3f9d1479896207a5ba6ebd153",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e825d8c1a207421e8c74855cc2b179d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"39b73308eabb4a40b191d95f1cd99adc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e7420765254b008345713f4d954ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c04994816d3749f893834fef25a00ee3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d851b46a809c4a2c8016e84109fa21af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"642f1b3d12cd46e8926cb48b5a5018bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02962ad0f85947f986c6a4b0a1cdb54b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efeb011911b84a44a53a21abe65022a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c348a39a1d1412494a3c1025330423a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d794a45db0574c80bc158a51c7aed429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a0d75738bc47699765553603f8d65a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"0c4436e5ecda4a3fb3aa78eb0984b4b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034c9c6b80bd484e97aabc657fce86fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ff9433a396c46d9ac0baa4a6c4962fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c9a7fbd26c45b1bd4c1f2e4b00e6af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"2f0f9691e6e74725afedc9a03c0dd8e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8255f32265ec4af4a8a2da1f42995d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"9c4010cea0264c5091c30552402b9455",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51bfe1c68e194b51a1c6cd3c4f95660c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8a9a277f0854dae80b71c73532cc4be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675dff35ce554edcae9d7ad4b82401ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2429653a3dac4d299ad37a5504e3c6d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d4c909af51451f9a2e04e2e76f8740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9af7d77441ec4c88a86edb6ecbbd2538",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1875e4a2340423bbce2f1e9ec58c441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d6b1e2d0ad04e0799a16a091b7fbc03":{
      "scriptId":"u0"},
    "3661570376e94bb98dc6017ce1c5780c":{
      "scriptId":"u1"},
    "92958d8a6a8d4760b3772bdb66d0bfda":{
      "scriptId":"u2"},
    "5ca4e25a8a9b42f88fd8925b6c3efa51":{
      "scriptId":"u3"},
    "2312d93cbb844b7bbf9e06f933eb4fd7":{
      "scriptId":"u4"},
    "6ff86ea6310a490896dac9acdf0435c7":{
      "scriptId":"u5"},
    "3c438057c5f143bd94ceaa3fe4c8b14b":{
      "scriptId":"u6"},
    "1cdd45a5b84d4755a615b255102e95e4":{
      "scriptId":"u7"},
    "cd82c61664e44db395707aa8c80f3826":{
      "scriptId":"u8"},
    "02f6af566f3645c48771c15a1189441f":{
      "scriptId":"u9"},
    "72ee0c3ad60844ae89039cf1e76b32c8":{
      "scriptId":"u10"},
    "8defb15f5a0d4d0faab187854af18962":{
      "scriptId":"u11"},
    "ac34c2d861e546b59f547cf654738d46":{
      "scriptId":"u12"},
    "b29fdc4c76fb485ca8570f12367ff48e":{
      "scriptId":"u13"},
    "64810a852cab4ac6aa2e03be6ae526e1":{
      "scriptId":"u14"},
    "cc6916072b6e48bfbcb9ecfc5340219b":{
      "scriptId":"u15"},
    "1042f08a588a4bb8a9f8a73c40e7bbcb":{
      "scriptId":"u16"},
    "ba42f72b837d4ef8a7d8cb7643462faa":{
      "scriptId":"u17"},
    "239ee8cfd5d0458a9775bfab38f01614":{
      "scriptId":"u18"},
    "722d8555db314375881298737596a807":{
      "scriptId":"u19"},
    "4bb369a510164bb780da955044cbf3bc":{
      "scriptId":"u20"},
    "7a06aee15b684010b2782ebc8c0d51cb":{
      "scriptId":"u21"},
    "3758ef2551834bb3ab84e1b04d5d3e8c":{
      "scriptId":"u22"},
    "06655701630044e683bc2c2c5bf942b5":{
      "scriptId":"u23"},
    "f139db6018be49f68257737ed8c5cfa2":{
      "scriptId":"u24"},
    "b86e899a40034fc9bd4c8cb221d9cb1c":{
      "scriptId":"u25"},
    "15e1be29525d4ef989017d85e17165a2":{
      "scriptId":"u26"},
    "05714c046aba4beb8b78503b76c375f1":{
      "scriptId":"u27"},
    "1b50bf98c5c84495a4201a8bfaaf68e6":{
      "scriptId":"u28"},
    "a74d4d67809e4a4e9c75399d4d644146":{
      "scriptId":"u29"},
    "96b46c1553c34881b7ee97feacb67505":{
      "scriptId":"u30"},
    "0fc1bcdc52da43969f6af857673ee1a5":{
      "scriptId":"u31"},
    "31fa9fb9c40641b7b76d3088bbf19936":{
      "scriptId":"u32"},
    "9ce8043dc88d464593a58fa6ed26e9ce":{
      "scriptId":"u33"},
    "d7044feabf744816bc5ccb9b799e3b34":{
      "scriptId":"u34"},
    "575007a0e0384687966cd182cd2bf852":{
      "scriptId":"u35"},
    "f541c853d99643a2af2f2076d9693ae9":{
      "scriptId":"u36"},
    "2412f4d2722b4ce3a98a98dcae34e468":{
      "scriptId":"u37"},
    "1f59afb2358540af9ed4cc3eef8fcc28":{
      "scriptId":"u38"},
    "c09b6ab83f6a4db188dfb97d5410d3f5":{
      "scriptId":"u39"},
    "914d28c935b948eb82dcf51d08df5eac":{
      "scriptId":"u40"},
    "d5aeceb599d44484bd20a95466da76a4":{
      "scriptId":"u41"},
    "dd11111cc04a4553b0172f772f4148ac":{
      "scriptId":"u42"},
    "8caefcc579b743c39f5f2ce4db7ffe1e":{
      "scriptId":"u43"},
    "93fd400deb1543ff99b657e1dafd5f31":{
      "scriptId":"u44"},
    "a8312a11192a40a886c7c072e40cfd42":{
      "scriptId":"u45"},
    "7e8cc2bf684d4c3b82da5432d41bfac4":{
      "scriptId":"u46"},
    "b33bde96c986472e9016aebd3ee9b2f6":{
      "scriptId":"u47"},
    "e91ffc662fb54f9a9fa64c2ec8671f21":{
      "scriptId":"u48"},
    "a4d3c268bf654153acb96209354d24b0":{
      "scriptId":"u49"},
    "5abb7d49969e40638cccbff7a46d5d70":{
      "scriptId":"u50"},
    "4edea20637d14e68990f92b9a3fe7528":{
      "scriptId":"u51"},
    "5c9f94a0f8a74a4183840aa52b9f5da8":{
      "scriptId":"u52"},
    "3d74e36b254c4c0a83834211b4bfe9b7":{
      "scriptId":"u53"},
    "33bc114a4f414f098e1cd9687448a4e8":{
      "scriptId":"u54"},
    "b8c4b16b38e849b496088f215e182983":{
      "scriptId":"u55"},
    "0fad315222dc40a9af6681a203c4d420":{
      "scriptId":"u56"},
    "247dcf2316c04530be50b211f085ea61":{
      "scriptId":"u57"},
    "7c3f2ff137ca47c6a701e9cf3ed159b9":{
      "scriptId":"u58"},
    "864797c6e13340fa928ec8b5d4d42536":{
      "scriptId":"u59"},
    "cda240e3c9724227be66f7c6ca1f96fb":{
      "scriptId":"u60"},
    "4a95b16d870244509a9559c2cc51c9a9":{
      "scriptId":"u61"},
    "ee0440d757184aa39dc732eb17589b9d":{
      "scriptId":"u62"},
    "f78d81007f6643d1b987c5d4945fb8d9":{
      "scriptId":"u63"},
    "566adafc8795479e9c154800f19b56d0":{
      "scriptId":"u64"},
    "89cc7a70aff845b586eeb2dd048add0c":{
      "scriptId":"u65"},
    "709bc62e604d4e8aadfa2737ac0382cc":{
      "scriptId":"u66"},
    "859b2a3eb4094c8eaa336c2e3aaf16bc":{
      "scriptId":"u67"},
    "dc0f913a43f04fdd9dcf41be5e54c543":{
      "scriptId":"u68"},
    "5a8fc0d3749d477a98f9cf9a54562825":{
      "scriptId":"u69"},
    "1be85f54bc77451eaa58dc4726a800c2":{
      "scriptId":"u70"},
    "fe060ac3fd37457597319d4bf5ba3374":{
      "scriptId":"u71"},
    "2f89c00910dd46d897e5dd425fb316eb":{
      "scriptId":"u72"},
    "03f2417423f641f6b4b9cf25e97f224c":{
      "scriptId":"u73"},
    "d0cadb270c6a4ad094528334f9c6ef3e":{
      "scriptId":"u74"},
    "f4677ffaf08246abbf0d2f83c8768df9":{
      "scriptId":"u75"},
    "db0a67767db54e778ea42697d856296c":{
      "scriptId":"u76"},
    "44047b27d0de4fd594f9509c2f06ec93":{
      "scriptId":"u77"},
    "53193ee573794f2db2a72e049af0cb76":{
      "scriptId":"u78"},
    "15bca30d524442618bd2c148c749cd3d":{
      "scriptId":"u79"},
    "53c2e5e3f9d1479896207a5ba6ebd153":{
      "scriptId":"u80"},
    "e825d8c1a207421e8c74855cc2b179d9":{
      "scriptId":"u81"},
    "39b73308eabb4a40b191d95f1cd99adc":{
      "scriptId":"u82"},
    "e6e7420765254b008345713f4d954ba8":{
      "scriptId":"u83"},
    "c04994816d3749f893834fef25a00ee3":{
      "scriptId":"u84"},
    "d851b46a809c4a2c8016e84109fa21af":{
      "scriptId":"u85"},
    "642f1b3d12cd46e8926cb48b5a5018bf":{
      "scriptId":"u86"},
    "02962ad0f85947f986c6a4b0a1cdb54b":{
      "scriptId":"u87"},
    "efeb011911b84a44a53a21abe65022a8":{
      "scriptId":"u88"},
    "6c348a39a1d1412494a3c1025330423a":{
      "scriptId":"u89"},
    "d794a45db0574c80bc158a51c7aed429":{
      "scriptId":"u90"},
    "b5a0d75738bc47699765553603f8d65a":{
      "scriptId":"u91"},
    "0c4436e5ecda4a3fb3aa78eb0984b4b8":{
      "scriptId":"u92"},
    "034c9c6b80bd484e97aabc657fce86fa":{
      "scriptId":"u93"},
    "8ff9433a396c46d9ac0baa4a6c4962fe":{
      "scriptId":"u94"},
    "78c9a7fbd26c45b1bd4c1f2e4b00e6af":{
      "scriptId":"u95"},
    "2f0f9691e6e74725afedc9a03c0dd8e2":{
      "scriptId":"u96"},
    "8255f32265ec4af4a8a2da1f42995d8d":{
      "scriptId":"u97"},
    "9c4010cea0264c5091c30552402b9455":{
      "scriptId":"u98"},
    "51bfe1c68e194b51a1c6cd3c4f95660c":{
      "scriptId":"u99"},
    "e8a9a277f0854dae80b71c73532cc4be":{
      "scriptId":"u100"},
    "675dff35ce554edcae9d7ad4b82401ad":{
      "scriptId":"u101"},
    "2429653a3dac4d299ad37a5504e3c6d5":{
      "scriptId":"u102"},
    "a6d4c909af51451f9a2e04e2e76f8740":{
      "scriptId":"u103"},
    "9af7d77441ec4c88a86edb6ecbbd2538":{
      "scriptId":"u104"},
    "e1875e4a2340423bbce2f1e9ec58c441":{
      "scriptId":"u105"}}});