$axure.loadCurrentPage({
  "url":"查看.html",
  "generationDate":new Date(1524492044461.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"147419deac4c4810b7e65395621f10b7",
    "type":"Axure:Page",
    "name":"查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"05caa18c45564c2399926b0288fba365",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"054476ee81e0419db63a8d2612d79f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"e40a3df9f59b47e2b1da386c08640b7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824b570c4f5a4460a2996eecb7b63df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"9aec401fa39b44b7807882b8dfa9c4ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdd5855b29e14ba5891cc185c99513b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"ff9cc11765664058b7ef0e5c32518a74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5627b782fd2348f0a73f2ebb1155a923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"8703c1186b1d406584d01284c10786dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08cdb98263944e14aa424c9d414d6fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"02293619b4e74bc6a634d7f2aed141f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":971},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702ad541c9454fe9a573cef89cfc1497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":971},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"ef2a705e263647fc960f1c47867d69bd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":1024},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"39e96f1e3bd8458f9e321b0425eefc1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed6baa6e22445d784ca990798083a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"ef9d4acf5a4e417ba40d9e70adda93e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2017bf56ec1417aab37147b1c9a015e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6f3c3fea9a24a6bbcabfa995b93fdbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec34cf53b2043bda231103a19d606f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"bfcb089594d04e10a103a72c8e125efc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75b34a3d5a348ac8cf66c24389a2a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 疑难伤口",
                      "target":{
                        "targetType":"page",
                        "url":"疑难伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9aa50e66cd4b40994764dddb9a8cdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":873},
            "size":{
              "width":99,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfd0389f25e40f7a67f4ef79f65bbab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":873},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u91.png"}},
{
          "id":"0dac3b7d25794a79bcfa0e079545721c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":909},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc1555779c4546fd89bcc8ddb7263ce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":909},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"f7a00d5656264becaec72ba0259f9c01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":920},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb130a23aa24004ac120ebdaec493e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":973,
                  "y":920},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"3cb710ce66af4c54b1a0bcf2fb8393cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":250},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a3f760e8ee146148f7b5fdfa22177bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":250},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"ac6c84a7d463496f97c33397209ab396",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509ec8660f934b2eb0f30f4e6ef831a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"41c923e387ac4c1688baf948b9bc838e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7905b99f70d54fb48453d66642c8dc95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"b5fa406e916e43f395c6b19d5fb85cd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":308},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff1de5e0cbf49f3922916ac0497ff04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":308},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"6fed0055c4c54837b117e5efcbaca877",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":374},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a52708207c1747a9b58039c52d56ae73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":374},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5c6cb401ec84d7b8f70215ef609b01e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":364},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"c6ce642d49d34aa6bdc7fbe7206034a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a809a07d54146f3af6e68e32e4b296f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa5e6252e3534e22889ea0eca8e63316",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":282},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"604a599637f7416badd49e0afaadd446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":282},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a1d913696e14665886af2b2de97b8dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":468},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01ed1172d14f44c5ad901af887ad6bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":468},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"9b953f05878045a68887a0ba5349adde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faac212f0dd04087809d08fabcb9dac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"44c97132b07c452692684dbf73708301",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e58e49d5a93549ba9d3bb04bc697f098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"7f2dfee36b844942b5a1656d371e3f50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":526},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27abc50592304c379dd04e6983da3049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":526},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"d5a9b91255d94d758c7f0ef9678f9bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":592},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"054d1053ba2e48f79bbf574e19709efc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":592},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8046b4cd9e8a41eebaf43f25b9cad7d3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":582},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"4726de8114a54aea99c0cf4659d03ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c888ddeb47d14130bd9460e8dcbf9707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eea40fb7665547aca6819624c8faa06c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":500},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7fb8d0d55924ed0b1eeef6dec053d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":500},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a46a4bbf014135809faafd4936a9ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":687},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5946569e317447485fb5eb985ae314d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":687},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"bfb830a449c24195a1eb39d947576885",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e92b5d61ba8e4b8684a91e5c7e924c2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u6.png"}},
{
          "id":"8d6ac2471a204f88b67d66cdef08f0ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41a1549c80e34b5d9a44558c0648774e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u8.png"}},
{
          "id":"28fb9fde16f84121814f7e47c3de1f43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":745},
            "size":{
              "width":210,
              "height":152},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a7ef0634044f709054632398d76090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":791,
                  "y":745},
                "size":{
                  "width":210,
                  "height":152},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u10.png"}},
{
          "id":"2ff40ffb696e4f6ebbb12da8cfca738c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":791,
              "y":811},
            "size":{
              "width":210,
              "height":21},
            "cornerRadiusTopLeft":"17"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c11062152d4211996cdcf88a0ee6a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":791,
                  "y":811},
                "size":{
                  "width":210,
                  "height":21},
                "cornerRadiusTopLeft":"17"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8748f3a678845fcbecadb2d0b1a832d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1011,
              "y":801},
            "size":{
              "width":104,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"387c3d1b8276430195ab2fd3305b3e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d2d2b266ca4fd0a3dd08d6c38a01be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1492ad68f73f436795f6871a239c3ae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":719},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cea51adbf0e49bbba0ab22c8e7fc702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":719},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ceeb7ef4727d4955b6226387f887b763",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":351,
              "y":913},
            "size":{
              "width":775,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a81e60e34971460da1922191196319ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":351,
                  "y":913},
                "size":{
                  "width":775,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看图片记录/u29.png"}},
{
          "id":"2a6765dba384411da345147deee037dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":366,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2e34bee9c940b599dbd380e9dc348c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":366,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6602577fd042d8b84a5022971378dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":577,
              "y":945},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85bf07a69a54185bd7c3632f198c563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":945},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34fda8d7e02242528e39d27606eca049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6b5d8fccfc4b06840b79a45cebe266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"33ba964c85b3486ea10d15c94da15074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76f5bde6b0242bcab0b8db3e9b76438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6caa4b55c666462cb79cadb8180a1f6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"016f2ed745ed48e0bf66846f23c2afc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"9b331ce1d6484dd4b03bafa46176ceff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6241d389e54d43bc8c62baf5e148f688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc8c0d8b02e4b5d8c3e7a923ae34455",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb1edfd8991405496ec7312df4cc124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d79d67313ca4ba8ae286bfb66af25a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eec567fc9e34e68843e0815ede3fe01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"852288abb4014d4fa6fbf58c840dbe2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa55cf3cbdd4e3cab9a07117941c75b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0dcbc047c5d4bed9978a597f1374cfd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7483cbf7ec1e4015a8d2e24fc3c131bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"6724a10d012c4ab9850d835bd8004658",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"855b22c62c504bd7b8c85969e26f9f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"c294059df42545a5b51941e279318305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cf27c9594414b18bd26e095ae17b3a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef8ad3bc5e544379b5e17d4e0134585e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da14cbb17fab45828fcd2423cd9eeef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d008d099080046a699b3ebed649edd1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7c5302287b4996b8237c48c2aa227a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01ee2e97ccb94ce8ae047a02062bb8ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c03c9d8c6d948629c19096daafec9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "05caa18c45564c2399926b0288fba365":{
      "scriptId":"u0"},
    "054476ee81e0419db63a8d2612d79f75":{
      "scriptId":"u1"},
    "e40a3df9f59b47e2b1da386c08640b7e":{
      "scriptId":"u2"},
    "824b570c4f5a4460a2996eecb7b63df7":{
      "scriptId":"u3"},
    "9aec401fa39b44b7807882b8dfa9c4ad":{
      "scriptId":"u4"},
    "cdd5855b29e14ba5891cc185c99513b2":{
      "scriptId":"u5"},
    "ff9cc11765664058b7ef0e5c32518a74":{
      "scriptId":"u6"},
    "5627b782fd2348f0a73f2ebb1155a923":{
      "scriptId":"u7"},
    "8703c1186b1d406584d01284c10786dd":{
      "scriptId":"u8"},
    "08cdb98263944e14aa424c9d414d6fbe":{
      "scriptId":"u9"},
    "02293619b4e74bc6a634d7f2aed141f9":{
      "scriptId":"u10"},
    "702ad541c9454fe9a573cef89cfc1497":{
      "scriptId":"u11"},
    "ef2a705e263647fc960f1c47867d69bd":{
      "scriptId":"u12"},
    "39e96f1e3bd8458f9e321b0425eefc1e":{
      "scriptId":"u13"},
    "8ed6baa6e22445d784ca990798083a89":{
      "scriptId":"u14"},
    "ef9d4acf5a4e417ba40d9e70adda93e2":{
      "scriptId":"u15"},
    "d2017bf56ec1417aab37147b1c9a015e":{
      "scriptId":"u16"},
    "b6f3c3fea9a24a6bbcabfa995b93fdbd":{
      "scriptId":"u17"},
    "cec34cf53b2043bda231103a19d606f7":{
      "scriptId":"u18"},
    "bfcb089594d04e10a103a72c8e125efc":{
      "scriptId":"u19"},
    "a75b34a3d5a348ac8cf66c24389a2a8d":{
      "scriptId":"u20"},
    "3b9aa50e66cd4b40994764dddb9a8cdb":{
      "scriptId":"u21"},
    "4bfd0389f25e40f7a67f4ef79f65bbab":{
      "scriptId":"u22"},
    "0dac3b7d25794a79bcfa0e079545721c":{
      "scriptId":"u23"},
    "dc1555779c4546fd89bcc8ddb7263ce1":{
      "scriptId":"u24"},
    "f7a00d5656264becaec72ba0259f9c01":{
      "scriptId":"u25"},
    "1cb130a23aa24004ac120ebdaec493e3":{
      "scriptId":"u26"},
    "3cb710ce66af4c54b1a0bcf2fb8393cd":{
      "scriptId":"u27"},
    "1a3f760e8ee146148f7b5fdfa22177bd":{
      "scriptId":"u28"},
    "ac6c84a7d463496f97c33397209ab396":{
      "scriptId":"u29"},
    "509ec8660f934b2eb0f30f4e6ef831a7":{
      "scriptId":"u30"},
    "41c923e387ac4c1688baf948b9bc838e":{
      "scriptId":"u31"},
    "7905b99f70d54fb48453d66642c8dc95":{
      "scriptId":"u32"},
    "b5fa406e916e43f395c6b19d5fb85cd0":{
      "scriptId":"u33"},
    "9ff1de5e0cbf49f3922916ac0497ff04":{
      "scriptId":"u34"},
    "6fed0055c4c54837b117e5efcbaca877":{
      "scriptId":"u35"},
    "a52708207c1747a9b58039c52d56ae73":{
      "scriptId":"u36"},
    "d5c6cb401ec84d7b8f70215ef609b01e":{
      "scriptId":"u37"},
    "c6ce642d49d34aa6bdc7fbe7206034a3":{
      "scriptId":"u38"},
    "2a809a07d54146f3af6e68e32e4b296f":{
      "scriptId":"u39"},
    "aa5e6252e3534e22889ea0eca8e63316":{
      "scriptId":"u40"},
    "604a599637f7416badd49e0afaadd446":{
      "scriptId":"u41"},
    "0a1d913696e14665886af2b2de97b8dc":{
      "scriptId":"u42"},
    "01ed1172d14f44c5ad901af887ad6bdf":{
      "scriptId":"u43"},
    "9b953f05878045a68887a0ba5349adde":{
      "scriptId":"u44"},
    "faac212f0dd04087809d08fabcb9dac7":{
      "scriptId":"u45"},
    "44c97132b07c452692684dbf73708301":{
      "scriptId":"u46"},
    "e58e49d5a93549ba9d3bb04bc697f098":{
      "scriptId":"u47"},
    "7f2dfee36b844942b5a1656d371e3f50":{
      "scriptId":"u48"},
    "27abc50592304c379dd04e6983da3049":{
      "scriptId":"u49"},
    "d5a9b91255d94d758c7f0ef9678f9bc3":{
      "scriptId":"u50"},
    "054d1053ba2e48f79bbf574e19709efc":{
      "scriptId":"u51"},
    "8046b4cd9e8a41eebaf43f25b9cad7d3":{
      "scriptId":"u52"},
    "4726de8114a54aea99c0cf4659d03ddf":{
      "scriptId":"u53"},
    "c888ddeb47d14130bd9460e8dcbf9707":{
      "scriptId":"u54"},
    "eea40fb7665547aca6819624c8faa06c":{
      "scriptId":"u55"},
    "a7fb8d0d55924ed0b1eeef6dec053d4f":{
      "scriptId":"u56"},
    "c9a46a4bbf014135809faafd4936a9ba":{
      "scriptId":"u57"},
    "a5946569e317447485fb5eb985ae314d":{
      "scriptId":"u58"},
    "bfb830a449c24195a1eb39d947576885":{
      "scriptId":"u59"},
    "e92b5d61ba8e4b8684a91e5c7e924c2e":{
      "scriptId":"u60"},
    "8d6ac2471a204f88b67d66cdef08f0ba":{
      "scriptId":"u61"},
    "41a1549c80e34b5d9a44558c0648774e":{
      "scriptId":"u62"},
    "28fb9fde16f84121814f7e47c3de1f43":{
      "scriptId":"u63"},
    "b1a7ef0634044f709054632398d76090":{
      "scriptId":"u64"},
    "2ff40ffb696e4f6ebbb12da8cfca738c":{
      "scriptId":"u65"},
    "76c11062152d4211996cdcf88a0ee6a8":{
      "scriptId":"u66"},
    "c8748f3a678845fcbecadb2d0b1a832d":{
      "scriptId":"u67"},
    "387c3d1b8276430195ab2fd3305b3e37":{
      "scriptId":"u68"},
    "c6d2d2b266ca4fd0a3dd08d6c38a01be":{
      "scriptId":"u69"},
    "1492ad68f73f436795f6871a239c3ae1":{
      "scriptId":"u70"},
    "8cea51adbf0e49bbba0ab22c8e7fc702":{
      "scriptId":"u71"},
    "ceeb7ef4727d4955b6226387f887b763":{
      "scriptId":"u72"},
    "a81e60e34971460da1922191196319ec":{
      "scriptId":"u73"},
    "2a6765dba384411da345147deee037dd":{
      "scriptId":"u74"},
    "cf2e34bee9c940b599dbd380e9dc348c":{
      "scriptId":"u75"},
    "0b6602577fd042d8b84a5022971378dc":{
      "scriptId":"u76"},
    "d85bf07a69a54185bd7c3632f198c563":{
      "scriptId":"u77"},
    "34fda8d7e02242528e39d27606eca049":{
      "scriptId":"u78"},
    "de6b5d8fccfc4b06840b79a45cebe266":{
      "scriptId":"u79"},
    "33ba964c85b3486ea10d15c94da15074":{
      "scriptId":"u80"},
    "c76f5bde6b0242bcab0b8db3e9b76438":{
      "scriptId":"u81"},
    "6caa4b55c666462cb79cadb8180a1f6f":{
      "scriptId":"u82"},
    "016f2ed745ed48e0bf66846f23c2afc4":{
      "scriptId":"u83"},
    "9b331ce1d6484dd4b03bafa46176ceff":{
      "scriptId":"u84"},
    "6241d389e54d43bc8c62baf5e148f688":{
      "scriptId":"u85"},
    "7dc8c0d8b02e4b5d8c3e7a923ae34455":{
      "scriptId":"u86"},
    "bfb1edfd8991405496ec7312df4cc124":{
      "scriptId":"u87"},
    "3d79d67313ca4ba8ae286bfb66af25a5":{
      "scriptId":"u88"},
    "6eec567fc9e34e68843e0815ede3fe01":{
      "scriptId":"u89"},
    "852288abb4014d4fa6fbf58c840dbe2e":{
      "scriptId":"u90"},
    "ffa55cf3cbdd4e3cab9a07117941c75b":{
      "scriptId":"u91"},
    "a0dcbc047c5d4bed9978a597f1374cfd":{
      "scriptId":"u92"},
    "7483cbf7ec1e4015a8d2e24fc3c131bf":{
      "scriptId":"u93"},
    "6724a10d012c4ab9850d835bd8004658":{
      "scriptId":"u94"},
    "855b22c62c504bd7b8c85969e26f9f71":{
      "scriptId":"u95"},
    "c294059df42545a5b51941e279318305":{
      "scriptId":"u96"},
    "1cf27c9594414b18bd26e095ae17b3a4":{
      "scriptId":"u97"},
    "ef8ad3bc5e544379b5e17d4e0134585e":{
      "scriptId":"u98"},
    "da14cbb17fab45828fcd2423cd9eeef1":{
      "scriptId":"u99"},
    "d008d099080046a699b3ebed649edd1b":{
      "scriptId":"u100"},
    "db7c5302287b4996b8237c48c2aa227a":{
      "scriptId":"u101"},
    "01ee2e97ccb94ce8ae047a02062bb8ab":{
      "scriptId":"u102"},
    "5c03c9d8c6d948629c19096daafec9bb":{
      "scriptId":"u103"}}});