$axure.loadCurrentPage({
  "url":"疑难伤口.html",
  "generationDate":new Date(1524492044251),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fab2b68aed641edadfa206320b336b5",
    "type":"Axure:Page",
    "name":"疑难伤口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0361cd221d5c4da7ba71316b8bf57000",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"077c96bce038457ba6bde7e1c85afee6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"0ffbdec0094543e99fdb851ae5f706d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd7155c920ee4f5e9d0074f7da29f2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"f1338b10b0db40bf8aec57998a67cd18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d14cc216254e8aa4dae50926f795d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"12aa36f7c26240e79ff450709bdc34f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2886180a143640898b632d30880a98da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"6fccebcebc4041f5b121a5b63fe9e258",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e253d8e8de1d499aa4c22cbdb51eeb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"3f8217a10c4b4680afe184444621c1b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":349,
              "y":290},
            "size":{
              "width":778,
              "height":757},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6437ce8b9f5543bc9f862e793d2d3bb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":349,
                  "y":290},
                "size":{
                  "width":778,
                  "height":757},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u10.png"}},
{
          "id":"f2596819b05f41639c9ac30c748a65fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"640c7255f0194d409e691b73267d1878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8664427316949ff9074b2f549852d00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f888896d204a4c169470d785e4bb3e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u30.png"}},
{
          "id":"76092b23153048d084611b74af524b1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a14524dd0ef4310bfedc9862412957c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"a6447ae50de14e3d9160628a44332b69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01c366e70fe24ab5a4b2eea7c10cad02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c243fb9f016140bea6ff55ba08455e59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e3f823c8b746e48758d04ac0a1cd84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u36.png"}},
{
          "id":"31e6c2e50ded4d3f96b062a1bb88d9e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c10ee7735ae940a2a8740dcfc9c422ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a0ed22d28e740beae2b85368c758e75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76090ddf245748dd808d89b6bb2268cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"03c70cf014964257b2632131ed7c7c5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f613d925f48742cba39420b30dfd3dc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8473554ce3c452b81bb65be2e451fcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":776,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d6f6c2f12b6451a9e0ebff44c2baef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":776,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23ef75ffdeff44c5ace1729c9b478b96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":350,
              "y":256},
            "size":{
              "width":386,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c14472bbc0d4b9d852772d868eca447",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":256},
                "size":{
                  "width":386,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0540af2940a04a19b3a0f99a9049ebff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":736,
              "y":256},
            "size":{
              "width":390,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2dc5642ff5d4e49be63a187cfac4ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":736,
                  "y":256},
                "size":{
                  "width":390,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9d3d39b21ac40afa568dfd102cb4a11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":467,
              "y":290},
            "size":{
              "width":161,
              "height":1},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1902f075e9d94e9bbb52b2a621ffc2a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":467,
                  "y":290},
                "size":{
                  "width":161,
                  "height":1},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u18.png"}},
{
          "id":"e4d1e899ea7740aba5a30766763138c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":304},
            "size":{
              "width":740,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"882dc9e82491439b95c1ef2c66322339",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":370,
              "y":309},
            "size":{
              "width":739,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd6bb73cb9b47d3a750c1453e385223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":309},
                "size":{
                  "width":739,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff1f678434f43f486a865e99632d484",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":308},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e21ffe5e0c4bf891c0ad3bc840a3aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":308},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u39.png"}},
{
          "id":"7927f14fcc0b425989bd7921be19ce5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":303},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcfb639e09645038ad71a795f65a39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":303},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u41.png"}},
{
          "id":"ee5734cd230040c08eb6a5b55041e78f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":376},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0668ff9d6c044f4ba13d4d6a06f1b704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":376},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"896a9e9a4ea5409daa85919210d23145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":468},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a2901a2445a4ca1b7a9cb785ac4a57a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":468},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"b653f8df01c94d90b38b0bef9b843e3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":561},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da9a500036ed453280a3f3057fbcfd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":561},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"1dc20dad8a0442f2a63e82a59aa85e13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":384},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57502d08b5334a46a151c336b0c6dca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":384},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"1d136616694d4041a8724cd2b45aa02a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":478.5},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc71682ff6b43e39e71205ca7098d30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":478.5},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"cf9ba2b74a8c4e8b8eb83329d1dc6022",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":572},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c70d20fa42d9458fb6d3757419449cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":572},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"fd80707a8c8b4473b4970d97de408ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e41abc0ba71844a09f834c880a4c9c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cce20e1413fe439fbc6db50d0965cc9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":184},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7098727ecf784054b322f30158082129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":184},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"e82bd50222e24188a4ecffdeca36fbf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":370,
              "y":175},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"579b542a248d40bca2223cdc67c9cb90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":370,
                  "y":175},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75922ad72815446ab63aabc0595efe98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736201bf02d64432ba38709a2eb443a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"5f2db14f77524d67a4567c09197843a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d1bd2f18fe4e9a8e368729a8e0de02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"877b2f8883f94251a1c8324b2c4d48dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f59a4f4cec84b97aa174393dbcbfead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"396859ec48314da5b8c6ca5732555823",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9148fb93db4cd296417b89e1144134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eefdcdb66ee47a99bc1c40790dfd9d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":370,
              "y":347},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6556c8f62c37417689cde5d8cf4a56be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":370,
                  "y":347},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"364d6dadb19a4b44b04d495061627f82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":370,
              "y":437},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8002170b29491e9b74a04a30c23b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":370,
                  "y":437},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3380d826cf39411aabe3543229d251c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":370,
              "y":529},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09496f6849dc4e7989846a0e541db6a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":370,
                  "y":529},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc69b644c4ca47db9007d46759a76dbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":571.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bde74c244445b5af3db2ac724c036d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":571.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/疑难伤口/u75.png"}},
{
          "id":"c215cc895cfb49459a587c880e1cf476",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":478.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55ac9bfb557649329b585d6ec4374684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":478.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/疑难伤口/u77.png"}},
{
          "id":"beec18db5e5b4c48a68babaf3430b0d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":386.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9c94e323c040b299ce17ebb970e2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":386.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/疑难伤口/u77.png"}},
{
          "id":"e683a178966d4988952b3aed0275b2d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1060,
              "y":378},
            "size":{
              "width":65,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d957f53373694af1828b40d3e5e2715a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1060,
                  "y":378},
                "size":{
                  "width":65,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看",
                      "target":{
                        "targetType":"page",
                        "url":"查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d25470398dd417f8c85496016626dbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1060,
              "y":469.5},
            "size":{
              "width":65,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ccf399f1404edabaabc19d6e719097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1060,
                  "y":469.5},
                "size":{
                  "width":65,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看",
                      "target":{
                        "targetType":"page",
                        "url":"查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba9dfba1473341c7b4807c7d225351ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1057.5,
              "y":563.5},
            "size":{
              "width":65,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03903d6930e64e54a9f6d5a7b578fe2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1057.5,
                  "y":563.5},
                "size":{
                  "width":65,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看",
                      "target":{
                        "targetType":"page",
                        "url":"查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0361cd221d5c4da7ba71316b8bf57000":{
      "scriptId":"u0"},
    "077c96bce038457ba6bde7e1c85afee6":{
      "scriptId":"u1"},
    "0ffbdec0094543e99fdb851ae5f706d8":{
      "scriptId":"u2"},
    "bd7155c920ee4f5e9d0074f7da29f2b7":{
      "scriptId":"u3"},
    "f1338b10b0db40bf8aec57998a67cd18":{
      "scriptId":"u4"},
    "d7d14cc216254e8aa4dae50926f795d4":{
      "scriptId":"u5"},
    "12aa36f7c26240e79ff450709bdc34f0":{
      "scriptId":"u6"},
    "2886180a143640898b632d30880a98da":{
      "scriptId":"u7"},
    "6fccebcebc4041f5b121a5b63fe9e258":{
      "scriptId":"u8"},
    "e253d8e8de1d499aa4c22cbdb51eeb85":{
      "scriptId":"u9"},
    "3f8217a10c4b4680afe184444621c1b4":{
      "scriptId":"u10"},
    "6437ce8b9f5543bc9f862e793d2d3bb3":{
      "scriptId":"u11"},
    "f2596819b05f41639c9ac30c748a65fa":{
      "scriptId":"u12"},
    "640c7255f0194d409e691b73267d1878":{
      "scriptId":"u13"},
    "e8664427316949ff9074b2f549852d00":{
      "scriptId":"u14"},
    "f888896d204a4c169470d785e4bb3e79":{
      "scriptId":"u15"},
    "76092b23153048d084611b74af524b1e":{
      "scriptId":"u16"},
    "5a14524dd0ef4310bfedc9862412957c":{
      "scriptId":"u17"},
    "a6447ae50de14e3d9160628a44332b69":{
      "scriptId":"u18"},
    "01c366e70fe24ab5a4b2eea7c10cad02":{
      "scriptId":"u19"},
    "c243fb9f016140bea6ff55ba08455e59":{
      "scriptId":"u20"},
    "09e3f823c8b746e48758d04ac0a1cd84":{
      "scriptId":"u21"},
    "31e6c2e50ded4d3f96b062a1bb88d9e5":{
      "scriptId":"u22"},
    "c10ee7735ae940a2a8740dcfc9c422ca":{
      "scriptId":"u23"},
    "5a0ed22d28e740beae2b85368c758e75":{
      "scriptId":"u24"},
    "76090ddf245748dd808d89b6bb2268cd":{
      "scriptId":"u25"},
    "03c70cf014964257b2632131ed7c7c5c":{
      "scriptId":"u26"},
    "f613d925f48742cba39420b30dfd3dc1":{
      "scriptId":"u27"},
    "f8473554ce3c452b81bb65be2e451fcc":{
      "scriptId":"u28"},
    "7d6f6c2f12b6451a9e0ebff44c2baef1":{
      "scriptId":"u29"},
    "23ef75ffdeff44c5ace1729c9b478b96":{
      "scriptId":"u30"},
    "8c14472bbc0d4b9d852772d868eca447":{
      "scriptId":"u31"},
    "0540af2940a04a19b3a0f99a9049ebff":{
      "scriptId":"u32"},
    "f2dc5642ff5d4e49be63a187cfac4ba8":{
      "scriptId":"u33"},
    "b9d3d39b21ac40afa568dfd102cb4a11":{
      "scriptId":"u34"},
    "1902f075e9d94e9bbb52b2a621ffc2a8":{
      "scriptId":"u35"},
    "e4d1e899ea7740aba5a30766763138c2":{
      "scriptId":"u36"},
    "882dc9e82491439b95c1ef2c66322339":{
      "scriptId":"u37"},
    "6cd6bb73cb9b47d3a750c1453e385223":{
      "scriptId":"u38"},
    "5ff1f678434f43f486a865e99632d484":{
      "scriptId":"u39"},
    "76e21ffe5e0c4bf891c0ad3bc840a3aa":{
      "scriptId":"u40"},
    "7927f14fcc0b425989bd7921be19ce5e":{
      "scriptId":"u41"},
    "6dcfb639e09645038ad71a795f65a39c":{
      "scriptId":"u42"},
    "ee5734cd230040c08eb6a5b55041e78f":{
      "scriptId":"u43"},
    "0668ff9d6c044f4ba13d4d6a06f1b704":{
      "scriptId":"u44"},
    "896a9e9a4ea5409daa85919210d23145":{
      "scriptId":"u45"},
    "9a2901a2445a4ca1b7a9cb785ac4a57a":{
      "scriptId":"u46"},
    "b653f8df01c94d90b38b0bef9b843e3a":{
      "scriptId":"u47"},
    "da9a500036ed453280a3f3057fbcfd70":{
      "scriptId":"u48"},
    "1dc20dad8a0442f2a63e82a59aa85e13":{
      "scriptId":"u49"},
    "57502d08b5334a46a151c336b0c6dca8":{
      "scriptId":"u50"},
    "1d136616694d4041a8724cd2b45aa02a":{
      "scriptId":"u51"},
    "abc71682ff6b43e39e71205ca7098d30":{
      "scriptId":"u52"},
    "cf9ba2b74a8c4e8b8eb83329d1dc6022":{
      "scriptId":"u53"},
    "c70d20fa42d9458fb6d3757419449cec":{
      "scriptId":"u54"},
    "fd80707a8c8b4473b4970d97de408ef2":{
      "scriptId":"u55"},
    "e41abc0ba71844a09f834c880a4c9c7f":{
      "scriptId":"u56"},
    "cce20e1413fe439fbc6db50d0965cc9d":{
      "scriptId":"u57"},
    "7098727ecf784054b322f30158082129":{
      "scriptId":"u58"},
    "e82bd50222e24188a4ecffdeca36fbf1":{
      "scriptId":"u59"},
    "579b542a248d40bca2223cdc67c9cb90":{
      "scriptId":"u60"},
    "75922ad72815446ab63aabc0595efe98":{
      "scriptId":"u61"},
    "736201bf02d64432ba38709a2eb443a8":{
      "scriptId":"u62"},
    "5f2db14f77524d67a4567c09197843a7":{
      "scriptId":"u63"},
    "72d1bd2f18fe4e9a8e368729a8e0de02":{
      "scriptId":"u64"},
    "877b2f8883f94251a1c8324b2c4d48dc":{
      "scriptId":"u65"},
    "1f59a4f4cec84b97aa174393dbcbfead":{
      "scriptId":"u66"},
    "396859ec48314da5b8c6ca5732555823":{
      "scriptId":"u67"},
    "6c9148fb93db4cd296417b89e1144134":{
      "scriptId":"u68"},
    "6eefdcdb66ee47a99bc1c40790dfd9d9":{
      "scriptId":"u69"},
    "6556c8f62c37417689cde5d8cf4a56be":{
      "scriptId":"u70"},
    "364d6dadb19a4b44b04d495061627f82":{
      "scriptId":"u71"},
    "6a8002170b29491e9b74a04a30c23b5a":{
      "scriptId":"u72"},
    "3380d826cf39411aabe3543229d251c3":{
      "scriptId":"u73"},
    "09496f6849dc4e7989846a0e541db6a6":{
      "scriptId":"u74"},
    "dc69b644c4ca47db9007d46759a76dbd":{
      "scriptId":"u75"},
    "a9bde74c244445b5af3db2ac724c036d":{
      "scriptId":"u76"},
    "c215cc895cfb49459a587c880e1cf476":{
      "scriptId":"u77"},
    "55ac9bfb557649329b585d6ec4374684":{
      "scriptId":"u78"},
    "beec18db5e5b4c48a68babaf3430b0d3":{
      "scriptId":"u79"},
    "ee9c94e323c040b299ce17ebb970e2dd":{
      "scriptId":"u80"},
    "e683a178966d4988952b3aed0275b2d3":{
      "scriptId":"u81"},
    "d957f53373694af1828b40d3e5e2715a":{
      "scriptId":"u82"},
    "2d25470398dd417f8c85496016626dbd":{
      "scriptId":"u83"},
    "37ccf399f1404edabaabc19d6e719097":{
      "scriptId":"u84"},
    "ba9dfba1473341c7b4807c7d225351ad":{
      "scriptId":"u85"},
    "03903d6930e64e54a9f6d5a7b578fe2d":{
      "scriptId":"u86"}}});