$axure.loadCurrentPage({
  "url":"圈画排序.html",
  "generationDate":new Date(1524492036271.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2136281829dc414a8ae7f5a1a8327e27",
    "type":"Axure:Page",
    "name":"圈画排序",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86633a52ba88437b94222357d844af3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-254},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0769fbf21564dcb823a61452dd082a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-254},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"57e077d806b047f78b4dcabdecc74c0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":50},
            "size":{
              "width":1024,
              "height":676},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b75bf1af3c4c45c59118b1799dcf5f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":50},
                "size":{
                  "width":1024,
                  "height":676},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后_1/u2.png"}},
{
          "id":"83593e073c4745cfb523a4bd3686847c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":490,
              "y":72},
            "size":{
              "width":580,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68cd57d56734932ac4aaa15eb42b870",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":490,
                  "y":72},
                "size":{
                  "width":580,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后_1/u4.png"}},
{
          "id":"61d3e5f11c5e44ca8c513255ccf2d206",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":368},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b75af8093de439e803fd2ca80bd457c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":368},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"72ff7af9fc984e1ba3090e0514d76e89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":682},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a9e626e8774be2b6ea5abf7ffd8a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":682},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多个临近开放性伤口",
                      "target":{
                        "targetType":"page",
                        "url":"多个临近开放性伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"dc50fddd25f44dcbb832887d4d7b52a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":1170,
              "y":80},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a293c7289b4d1c85343bdb5939ca0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":1170,
                  "y":80},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后/u8.png"}},
{
          "id":"43fa1ff8717b482b8b743ee29ef09e10",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":102},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拍摄后_1/u12_line.png"}},
{
          "id":"8d7067d3f1634a828544541eac08709e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":490,
              "y":130},
            "size":{
              "width":230,
              "height":80},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4377049aa2d04b808b29854c4580374f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":490,
                  "y":130},
                "size":{
                  "width":230,
                  "height":80},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/圈画排序/u13.png"}},
{
          "id":"b76cc1ee8a7b474bab48173ad8631858",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":660,
              "y":180},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e8b6c66d45b438682c99bd2403bbe03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":660,
                  "y":180},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 圈划伤口-1",
                      "target":{
                        "targetType":"page",
                        "url":"圈划伤口-1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "86633a52ba88437b94222357d844af3d":{
      "scriptId":"u0"},
    "b0769fbf21564dcb823a61452dd082a1":{
      "scriptId":"u1"},
    "57e077d806b047f78b4dcabdecc74c0c":{
      "scriptId":"u2"},
    "b75bf1af3c4c45c59118b1799dcf5f41":{
      "scriptId":"u3"},
    "83593e073c4745cfb523a4bd3686847c":{
      "scriptId":"u4"},
    "a68cd57d56734932ac4aaa15eb42b870":{
      "scriptId":"u5"},
    "61d3e5f11c5e44ca8c513255ccf2d206":{
      "scriptId":"u6"},
    "4b75af8093de439e803fd2ca80bd457c":{
      "scriptId":"u7"},
    "72ff7af9fc984e1ba3090e0514d76e89":{
      "scriptId":"u8"},
    "76a9e626e8774be2b6ea5abf7ffd8a6c":{
      "scriptId":"u9"},
    "dc50fddd25f44dcbb832887d4d7b52a6":{
      "scriptId":"u10"},
    "31a293c7289b4d1c85343bdb5939ca0e":{
      "scriptId":"u11"},
    "43fa1ff8717b482b8b743ee29ef09e10":{
      "scriptId":"u12"},
    "8d7067d3f1634a828544541eac08709e":{
      "scriptId":"u13"},
    "4377049aa2d04b808b29854c4580374f":{
      "scriptId":"u14"},
    "b76cc1ee8a7b474bab48173ad8631858":{
      "scriptId":"u15"},
    "3e8b6c66d45b438682c99bd2403bbe03":{
      "scriptId":"u16"}}});