$axure.loadCurrentPage({
  "url":"渗液量.html",
  "generationDate":new Date(1524492043432.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6a37c980b5dd439188b9bf18466be74d",
    "type":"Axure:Page",
    "name":"渗液量",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da9026cc4cd747afb8fab2af780dd8a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a883c4a1e1a24b169b72bd47ba93a2b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"54022f96c8d84674af28a671d36404ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1472a2a0c4d417da0a3d4d31b2c45a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"c2d8f1c55e5d4270acb0bd22aa717273",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac997956289e4b439cde985db4fcea3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"845d62d8cb8f491893ca0cebcbf3d4be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f9270d66b14caa8882ad46f6522aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"ba7d1da6be0d40efab700279af8ee7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"162c816d06b54d1d8e16ee008e91aa5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"d09cd710287544ee836aec0fa0073ad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e597230b3b6455789691873709e4a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"576f7610c9674d518320f4cd8357a228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":374,
              "y":260},
            "size":{
              "width":776,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5675ab12ec44161980fe7a6a2e81a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":260},
                "size":{
                  "width":776,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40aafbcddc3c4f39a55e5a08a7619084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b48150749ce4b44adf0d7358d2d0e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a98c1f387fb4dbfb7103653bf2163b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30d50ef5232405ba4d529540552fc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"e8391527a46849f0ae329ad9eee26019",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e483a1483df94ebeb46ea4fa3432c7e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5b6c53f98c4096a39b6613427b2832",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d071d6d94b440bf9ad7dc5ff1324ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29c94422371e4b5a90bef22f4ef96ae6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac319ca9d38742c5a4f78b61701edd04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"7aa160cefe8a41f7ab5d1427ae798645",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e4d4482256489c84fbe1d88b820667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"452e4bf1e63645ccbf4d30230141f765",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c2bbc375664b20b2046d79624f0477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"56e909b885dc42d09dc4e1c544885784",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071fef4f42f14357bda6fbb511b77a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13c39983f30b47c79162c95564626205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b363eff74c4d3188e0c7d045ab339f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b84728004154afb87eaca815332f051",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5ae37ae0a142ebac3917cabbdfad03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"6c7cda71313249018d455b2bd4a9cc28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a62f3bc13e14ba9a3ef3e2ac6f9968d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"cd90248c36f7432ba315390e7cf7773c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":370,
              "y":396},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4df5af4da50340d1a593802282acf6c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":396},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"003532c5b2f2482c813ecf518edd0b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0fe7275aa6f4feab8a696392e7a1a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u60.png"}},
{
          "id":"07099295d416443b8f1d91cb7044b10d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd1d1721f634dad8a15fcdffe376ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bef951387cc4f13a11822972cfc232c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0074c337404448ebfc97077fc1351e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d166374bc50f4eabb433f4649c560bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e338f8ed0b584174ab3b6937978ce760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"623e0b215b41475488d17d4e26d4f7f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3fe0f1180524242a5b7400795f59ca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a9450c5eef54c3ca05c996330212f1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":570},
            "size":{
              "width":754,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68c23eeefc54e2fa8ebffc3072aa5af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":570},
                "size":{
                  "width":754,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渗液量/u48.png"}},
{
          "id":"e1592cf47f374049aada4cdbc6381d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":520},
            "size":{
              "width":14,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e646dacfe44ec6a76de63acf116824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":356,
                  "y":520},
                "size":{
                  "width":14,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u34.png"}},
{
          "id":"949f3cc25d28442ead7716049b059739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":1010},
            "size":{
              "width":745,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8ac1bbbec24b94854f97be02cea99f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":1010},
                "size":{
                  "width":745,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u40.png"}},
{
          "id":"bbc14590a5f2451196a80e24d7f20dbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":530},
            "size":{
              "width":10,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16edb5442d7f4bb099efc11b7bc68417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1110,
                  "y":530},
                "size":{
                  "width":10,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u38.png"}},
{
          "id":"e844165bf4be4d56a2ad894d659b3e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":540},
            "size":{
              "width":745,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6afdd46761c24d8fae2bb01dd9366ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":540},
                "size":{
                  "width":745,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u36.png"}},
{
          "id":"b4266d962df3454eb70863736a59b788",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":970,
              "y":452},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198755e202fa4acca2554b5dec8dda2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":970,
                  "y":452},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u44.png"}},
{
          "id":"a97d202d669f49ec9d1f9fbc66596894",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":1020,
              "y":451},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35210bea251c4e16845765b32b69b56a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":451},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"011fe8a8b3f84d06ac90296af2238662",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC33},
            "location":{
              "x":970,
              "y":499},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7778a5b5117a47ceb9f9af4addd14e37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC33},
                "location":{
                  "x":970,
                  "y":499},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u48.png"}},
{
          "id":"112b61670da842ada9903d5d7d88f141",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":1020,
              "y":498},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fee41f1f3614d58bcaf98763f4cec41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":498},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dd49c2e36a94a31a0459ece87715765",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":970,
              "y":543},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5afcf0fdd6a54bac91f549b15f56e551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":970,
                  "y":543},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u52.png"}},
{
          "id":"fd6753399dc54402b3e359c9ee368462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1020,
              "y":542},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af5eadecb6b4f129f2d846cfb56bdb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":542},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78300f5c4d51489ba363c73660a2b056",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF9900CC},
            "location":{
              "x":970,
              "y":588},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9900CC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b17eb3f8e743309b66190951c3c051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9900CC},
                "location":{
                  "x":970,
                  "y":588},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u56.png"}},
{
          "id":"fba7e914953a41d8814103aef4191c2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":1020,
              "y":587},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8a2ddf22c74716abd20577af891539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":587},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"830ed72dc1aa426588397cffc1abdf4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":450},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d162571461fb43a4926e287332e79501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":450},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 总体",
                      "target":{
                        "targetType":"page",
                        "url":"总体.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb22eae84a284d1393f20e9e08331661",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":497},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6597a3603a1c4b0d98f2cc2c0e746b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":497},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 面积",
                      "target":{
                        "targetType":"page",
                        "url":"面积.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a92d73b594764cc1a55eea9298f1b712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":542},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fd49c84df04a7ba6c95cc11b6ffa34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":542},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渗液量",
                      "target":{
                        "targetType":"page",
                        "url":"渗液量.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e26b74410e7464a9dd5c907b1790cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":587},
            "size":{
              "width":150,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f10bbb3b404f0c819b4f3b5d4bf385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":587},
                "size":{
                  "width":150,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创面组织类型",
                      "target":{
                        "targetType":"page",
                        "url":"创面组织类型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c05931d0a549495198429241f4cd9ba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":750,
              "y":620},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331e9e6993b046af91ec0c136c2089b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":750,
                  "y":620},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54f3ba9891341f68f5f7ab5087030fe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":440},
            "size":{
              "width":10,
              "height":560},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/愈合变化/u76_line.png"}},
{
          "id":"9e64025836f74753be1eed14515ed8c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":30,
              "height":547}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc50e8df4e745109af1284effb36b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":30,
                  "height":547}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u42.png"}},
{
          "id":"9461c48fcdd446bd987c39a1df53ece1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":620},
            "size":{
              "width":323,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63478203c4ca49f7a4672dbaf016cf41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":620},
                "size":{
                  "width":323,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渗液量/u87.png"}},
{
          "id":"52a99932dd39451084ad45458bf03cd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":690},
            "size":{
              "width":323,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c999df2ce16a4045987e7cddf937b375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":690},
                "size":{
                  "width":323,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渗液量/u87.png"}},
{
          "id":"af02e5f801b84ac9af566ef41713fdc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":975,
              "y":904},
            "size":{
              "width":48,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"603f38e7b9884d8a8ea7d4e88a6ca816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":975,
                  "y":904},
                "size":{
                  "width":48,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渗液量/u91.png"}},
{
          "id":"02475f8e25e34c078e63199a3ae869a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ca1df62d9d411baffc4f7704cf4552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看图片记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看图片记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"930b8a1b140c4a6eb73807adb8f0491b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":440,
              "y":883},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d9ce15e549448886962c7bc40ecf50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":883},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc6a21b42ce246d887114a65cdc9d4bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":580,
              "y":910},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef6cee847242472a83eede1b511034c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":910},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"695f0eda10294032b3afb7015fe12df0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":720,
              "y":943},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb5fa8660a84ef2b73950933eb532a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":720,
                  "y":943},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d847e66e25d940dba50e50c80fdfc145",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":871,
              "y":943},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bd02026be54ef780008db431b11d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":871,
                  "y":943},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d007a7c8ef848c68644d7cfbcf9519b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1015,
              "y":944},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30fb9edfb9f04b7c900502ea95b23331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1015,
                  "y":944},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da9026cc4cd747afb8fab2af780dd8a4":{
      "scriptId":"u0"},
    "a883c4a1e1a24b169b72bd47ba93a2b8":{
      "scriptId":"u1"},
    "54022f96c8d84674af28a671d36404ed":{
      "scriptId":"u2"},
    "e1472a2a0c4d417da0a3d4d31b2c45a1":{
      "scriptId":"u3"},
    "c2d8f1c55e5d4270acb0bd22aa717273":{
      "scriptId":"u4"},
    "ac997956289e4b439cde985db4fcea3b":{
      "scriptId":"u5"},
    "845d62d8cb8f491893ca0cebcbf3d4be":{
      "scriptId":"u6"},
    "70f9270d66b14caa8882ad46f6522aaa":{
      "scriptId":"u7"},
    "ba7d1da6be0d40efab700279af8ee7dd":{
      "scriptId":"u8"},
    "162c816d06b54d1d8e16ee008e91aa5b":{
      "scriptId":"u9"},
    "d09cd710287544ee836aec0fa0073ad2":{
      "scriptId":"u10"},
    "9e597230b3b6455789691873709e4a0f":{
      "scriptId":"u11"},
    "576f7610c9674d518320f4cd8357a228":{
      "scriptId":"u12"},
    "f5675ab12ec44161980fe7a6a2e81a11":{
      "scriptId":"u13"},
    "40aafbcddc3c4f39a55e5a08a7619084":{
      "scriptId":"u14"},
    "2b48150749ce4b44adf0d7358d2d0e14":{
      "scriptId":"u15"},
    "5a98c1f387fb4dbfb7103653bf2163b2":{
      "scriptId":"u16"},
    "d30d50ef5232405ba4d529540552fc25":{
      "scriptId":"u17"},
    "e8391527a46849f0ae329ad9eee26019":{
      "scriptId":"u18"},
    "e483a1483df94ebeb46ea4fa3432c7e9":{
      "scriptId":"u19"},
    "3a5b6c53f98c4096a39b6613427b2832":{
      "scriptId":"u20"},
    "7d071d6d94b440bf9ad7dc5ff1324ee2":{
      "scriptId":"u21"},
    "29c94422371e4b5a90bef22f4ef96ae6":{
      "scriptId":"u22"},
    "ac319ca9d38742c5a4f78b61701edd04":{
      "scriptId":"u23"},
    "7aa160cefe8a41f7ab5d1427ae798645":{
      "scriptId":"u24"},
    "09e4d4482256489c84fbe1d88b820667":{
      "scriptId":"u25"},
    "452e4bf1e63645ccbf4d30230141f765":{
      "scriptId":"u26"},
    "b2c2bbc375664b20b2046d79624f0477":{
      "scriptId":"u27"},
    "56e909b885dc42d09dc4e1c544885784":{
      "scriptId":"u28"},
    "071fef4f42f14357bda6fbb511b77a0b":{
      "scriptId":"u29"},
    "13c39983f30b47c79162c95564626205":{
      "scriptId":"u30"},
    "00b363eff74c4d3188e0c7d045ab339f":{
      "scriptId":"u31"},
    "6b84728004154afb87eaca815332f051":{
      "scriptId":"u32"},
    "5c5ae37ae0a142ebac3917cabbdfad03":{
      "scriptId":"u33"},
    "6c7cda71313249018d455b2bd4a9cc28":{
      "scriptId":"u34"},
    "4a62f3bc13e14ba9a3ef3e2ac6f9968d":{
      "scriptId":"u35"},
    "cd90248c36f7432ba315390e7cf7773c":{
      "scriptId":"u36"},
    "4df5af4da50340d1a593802282acf6c7":{
      "scriptId":"u37"},
    "003532c5b2f2482c813ecf518edd0b83":{
      "scriptId":"u38"},
    "c0fe7275aa6f4feab8a696392e7a1a34":{
      "scriptId":"u39"},
    "07099295d416443b8f1d91cb7044b10d":{
      "scriptId":"u40"},
    "6cd1d1721f634dad8a15fcdffe376ec9":{
      "scriptId":"u41"},
    "2bef951387cc4f13a11822972cfc232c":{
      "scriptId":"u42"},
    "a0074c337404448ebfc97077fc1351e1":{
      "scriptId":"u43"},
    "d166374bc50f4eabb433f4649c560bb7":{
      "scriptId":"u44"},
    "e338f8ed0b584174ab3b6937978ce760":{
      "scriptId":"u45"},
    "623e0b215b41475488d17d4e26d4f7f6":{
      "scriptId":"u46"},
    "b3fe0f1180524242a5b7400795f59ca8":{
      "scriptId":"u47"},
    "8a9450c5eef54c3ca05c996330212f1c":{
      "scriptId":"u48"},
    "b68c23eeefc54e2fa8ebffc3072aa5af":{
      "scriptId":"u49"},
    "e1592cf47f374049aada4cdbc6381d21":{
      "scriptId":"u50"},
    "58e646dacfe44ec6a76de63acf116824":{
      "scriptId":"u51"},
    "949f3cc25d28442ead7716049b059739":{
      "scriptId":"u52"},
    "8d8ac1bbbec24b94854f97be02cea99f":{
      "scriptId":"u53"},
    "bbc14590a5f2451196a80e24d7f20dbf":{
      "scriptId":"u54"},
    "16edb5442d7f4bb099efc11b7bc68417":{
      "scriptId":"u55"},
    "e844165bf4be4d56a2ad894d659b3e23":{
      "scriptId":"u56"},
    "6afdd46761c24d8fae2bb01dd9366ad3":{
      "scriptId":"u57"},
    "b4266d962df3454eb70863736a59b788":{
      "scriptId":"u58"},
    "198755e202fa4acca2554b5dec8dda2e":{
      "scriptId":"u59"},
    "a97d202d669f49ec9d1f9fbc66596894":{
      "scriptId":"u60"},
    "35210bea251c4e16845765b32b69b56a":{
      "scriptId":"u61"},
    "011fe8a8b3f84d06ac90296af2238662":{
      "scriptId":"u62"},
    "7778a5b5117a47ceb9f9af4addd14e37":{
      "scriptId":"u63"},
    "112b61670da842ada9903d5d7d88f141":{
      "scriptId":"u64"},
    "1fee41f1f3614d58bcaf98763f4cec41":{
      "scriptId":"u65"},
    "9dd49c2e36a94a31a0459ece87715765":{
      "scriptId":"u66"},
    "5afcf0fdd6a54bac91f549b15f56e551":{
      "scriptId":"u67"},
    "fd6753399dc54402b3e359c9ee368462":{
      "scriptId":"u68"},
    "0af5eadecb6b4f129f2d846cfb56bdb7":{
      "scriptId":"u69"},
    "78300f5c4d51489ba363c73660a2b056":{
      "scriptId":"u70"},
    "55b17eb3f8e743309b66190951c3c051":{
      "scriptId":"u71"},
    "fba7e914953a41d8814103aef4191c2a":{
      "scriptId":"u72"},
    "6b8a2ddf22c74716abd20577af891539":{
      "scriptId":"u73"},
    "830ed72dc1aa426588397cffc1abdf4f":{
      "scriptId":"u74"},
    "d162571461fb43a4926e287332e79501":{
      "scriptId":"u75"},
    "cb22eae84a284d1393f20e9e08331661":{
      "scriptId":"u76"},
    "6597a3603a1c4b0d98f2cc2c0e746b52":{
      "scriptId":"u77"},
    "a92d73b594764cc1a55eea9298f1b712":{
      "scriptId":"u78"},
    "a4fd49c84df04a7ba6c95cc11b6ffa34":{
      "scriptId":"u79"},
    "7e26b74410e7464a9dd5c907b1790cc3":{
      "scriptId":"u80"},
    "57f10bbb3b404f0c819b4f3b5d4bf385":{
      "scriptId":"u81"},
    "c05931d0a549495198429241f4cd9ba8":{
      "scriptId":"u82"},
    "331e9e6993b046af91ec0c136c2089b5":{
      "scriptId":"u83"},
    "e54f3ba9891341f68f5f7ab5087030fe":{
      "scriptId":"u84"},
    "9e64025836f74753be1eed14515ed8c8":{
      "scriptId":"u85"},
    "2fc50e8df4e745109af1284effb36b59":{
      "scriptId":"u86"},
    "9461c48fcdd446bd987c39a1df53ece1":{
      "scriptId":"u87"},
    "63478203c4ca49f7a4672dbaf016cf41":{
      "scriptId":"u88"},
    "52a99932dd39451084ad45458bf03cd4":{
      "scriptId":"u89"},
    "c999df2ce16a4045987e7cddf937b375":{
      "scriptId":"u90"},
    "af02e5f801b84ac9af566ef41713fdc4":{
      "scriptId":"u91"},
    "603f38e7b9884d8a8ea7d4e88a6ca816":{
      "scriptId":"u92"},
    "02475f8e25e34c078e63199a3ae869a1":{
      "scriptId":"u93"},
    "e1ca1df62d9d411baffc4f7704cf4552":{
      "scriptId":"u94"},
    "930b8a1b140c4a6eb73807adb8f0491b":{
      "scriptId":"u95"},
    "95d9ce15e549448886962c7bc40ecf50":{
      "scriptId":"u96"},
    "cc6a21b42ce246d887114a65cdc9d4bc":{
      "scriptId":"u97"},
    "ef6cee847242472a83eede1b511034c0":{
      "scriptId":"u98"},
    "695f0eda10294032b3afb7015fe12df0":{
      "scriptId":"u99"},
    "8eb5fa8660a84ef2b73950933eb532a4":{
      "scriptId":"u100"},
    "d847e66e25d940dba50e50c80fdfc145":{
      "scriptId":"u101"},
    "78bd02026be54ef780008db431b11d8d":{
      "scriptId":"u102"},
    "2d007a7c8ef848c68644d7cfbcf9519b":{
      "scriptId":"u103"},
    "30fb9edfb9f04b7c900502ea95b23331":{
      "scriptId":"u104"}}});