$axure.loadCurrentPage({
  "url":"圈划伤口-2.html",
  "generationDate":new Date(1524492036976.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd68cefc3e2a400195ada1cc5384f3ea",
    "type":"Axure:Page",
    "name":"圈划伤口-2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f7b0b11c4e9c419b9b316081d49ffa4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ae82faabc24443b4cee0d678255958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"610df0479dee4723940f19ff34d6880a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1024,
              "height":678},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78dc27b2e1be4cab9cd90b9950db9594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1024,
                  "height":678},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-拍摄后/u2.png"}},
{
          "id":"b8512350df20479783939f5a6f084044",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e41f7fa569421e92408293e86e8f86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"09905e70b5e14b56b558c457291af703",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c2aca2ea9948ba96fba43c5e8044b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄后_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"2d9b8f932a7a4c3985aad9b303cbddd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":740,
              "y":330},
            "size":{
              "width":50,
              "height":80},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2611a93a410947d392a8a54368383895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":740,
                  "y":330},
                "size":{
                  "width":50,
                  "height":80},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口-1/u8.png"}},
{
          "id":"413d461e1d214f36b67d524efcc43b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":858,
              "y":280},
            "size":{
              "width":150,
              "height":241},
            "rotation":"160",
            "textRotation":"160",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3366FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1269fafc1d214eec94513b1a25a90647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":858,
                  "y":280},
                "size":{
                  "width":150,
                  "height":241},
                "rotation":"160",
                "textRotation":"160",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/复诊-圈划伤口-2/u16.png"}},
{
          "id":"54ed696fa3aa4cc880d4585a74f8bb3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":734,
              "y":416},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e8e257967e4b53a97b698cf5cb7499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":416},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b299a1d28ccd46bc8369e0cd1d57588c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":925,
              "y":523},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bdd2d17391c441199111b0c848aa9c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":925,
                  "y":523},
                "size":{
                  "width":60,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69024a7e0eab433b888bfef9359e360e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":1170,
              "y":78},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4464e634e54eb88c8a397119fda9c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":1170,
                  "y":78},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测算",
                      "target":{
                        "targetType":"page",
                        "url":"测算_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/复诊-上次比对/u12.png"}},
{
          "id":"cc136f3dcfa24cba994ad1c6de3fc7b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":490,
              "y":72},
            "size":{
              "width":580,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5806cdea81453dbfab59d223db1c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":490,
                  "y":72},
                "size":{
                  "width":580,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后_1/u4.png"}},
{
          "id":"39150b48eaf449d1b0c26257929de54a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":102},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拍摄后_1/u12_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f7b0b11c4e9c419b9b316081d49ffa4d":{
      "scriptId":"u0"},
    "36ae82faabc24443b4cee0d678255958":{
      "scriptId":"u1"},
    "610df0479dee4723940f19ff34d6880a":{
      "scriptId":"u2"},
    "78dc27b2e1be4cab9cd90b9950db9594":{
      "scriptId":"u3"},
    "b8512350df20479783939f5a6f084044":{
      "scriptId":"u4"},
    "28e41f7fa569421e92408293e86e8f86":{
      "scriptId":"u5"},
    "09905e70b5e14b56b558c457291af703":{
      "scriptId":"u6"},
    "28c2aca2ea9948ba96fba43c5e8044b4":{
      "scriptId":"u7"},
    "2d9b8f932a7a4c3985aad9b303cbddd0":{
      "scriptId":"u8"},
    "2611a93a410947d392a8a54368383895":{
      "scriptId":"u9"},
    "413d461e1d214f36b67d524efcc43b4b":{
      "scriptId":"u10"},
    "1269fafc1d214eec94513b1a25a90647":{
      "scriptId":"u11"},
    "54ed696fa3aa4cc880d4585a74f8bb3e":{
      "scriptId":"u12"},
    "e1e8e257967e4b53a97b698cf5cb7499":{
      "scriptId":"u13"},
    "b299a1d28ccd46bc8369e0cd1d57588c":{
      "scriptId":"u14"},
    "5bdd2d17391c441199111b0c848aa9c7":{
      "scriptId":"u15"},
    "69024a7e0eab433b888bfef9359e360e":{
      "scriptId":"u16"},
    "cc4464e634e54eb88c8a397119fda9c5":{
      "scriptId":"u17"},
    "cc136f3dcfa24cba994ad1c6de3fc7b5":{
      "scriptId":"u18"},
    "0e5806cdea81453dbfab59d223db1c92":{
      "scriptId":"u19"},
    "39150b48eaf449d1b0c26257929de54a":{
      "scriptId":"u20"}}});