$axure.loadCurrentPage({
  "url":"面积.html",
  "generationDate":new Date(1524492043275.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"853c6f7ead9647408f7121632989e113",
    "type":"Axure:Page",
    "name":"面积",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d8ad82ca98a461f8dfc1c4d6d8580e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b5a22cbdec4f47bc4e742e59b956ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"82715bf837e8463282ac92385be3169f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f765306cf5b4776b24214d843b39f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"b1cf4906a3124fd99d9a30df4406976c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e08ce061bf443c8a1b980c30bf8695f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"2e8b388414d04b1d91e1ab9fbd17e6b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2364297f51fa4873a987b47718a4719e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"4c9051725ccb4eaba44a0580c676fc2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516ad05e968b4b9a82470f1759d56d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"6616baef46934745938f1ee7026219ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"652202b8b59947f786b8c99cbd60ecf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ae63d23162a48a1afbe681229b1b56b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":374,
              "y":260},
            "size":{
              "width":776,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad433bbcc2742b79c7fcb6ce67dd523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":260},
                "size":{
                  "width":776,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc163c2ea8b341d3912983a7bde87c60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd45cc1c587478c84753fa3ad98db2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74ac79480c6546419c0381b63b4f22be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ebf9667a9e4e95ac624a1b6ab41ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"55b0bbaae6374126b858d08a284dde7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44511ef97f4a44d296cd3c14b495cb9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51a014247ca441b5acb2268930451c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6148360ef1a4d339b66bc86dc591cf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1870325a2a4db5b60d6fb7d27b316b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02aac61a921248a1b880caf895f78551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"3e053a2000a24b639b058f6d8d587650",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e611c2ccd03d46be8fd326f37f46779a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d78a502d02aa47bd9d813aa0467f025b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1447e3a0e8ab4c428844fe3716b73b8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"f9dc9b770446420dbc1d72e37809886c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265f5cfff04b40f5b808c9f9039f2738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"312fc5698f564526b38faaf3e12f9348",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41f871a5ee94647a9e9095b0f8da299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f467b65986cf46b799f42996e0579f27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e753795db7c4c4391b624697e6736f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"f1a8659d191145ea8ba3fd1c4eae288b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb04fa5f3b0447a28908ccd82f7d81dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"7f6fd22232f342fc97fe9133cf8d1463",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":370,
              "y":396},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7be1175edb944d6d9fa7d3a5170fb8b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":396},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47778aa5402944fc88dd2522b6f0c43e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":570},
            "size":{
              "width":754,
              "height":460},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b46a31c2c740e7b3980541c6752f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":570},
                "size":{
                  "width":754,
                  "height":460},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u32.png"}},
{
          "id":"82a38270e87a4cab992e97524df182bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":520},
            "size":{
              "width":14,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb0221802f64e0da678eaa62819231c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":356,
                  "y":520},
                "size":{
                  "width":14,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u34.png"}},
{
          "id":"a6b504d3d6f5472bb8450737f7fdeb8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":540},
            "size":{
              "width":745,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f836871b12264205925a9ffe98d61fd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":540},
                "size":{
                  "width":745,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u36.png"}},
{
          "id":"93edd714afcf4cf1a7e48239fa20c601",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":530},
            "size":{
              "width":10,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee6a9ee8cb347dcac087a7b822fde7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1110,
                  "y":530},
                "size":{
                  "width":10,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u38.png"}},
{
          "id":"e430053a08b043b28e3e4bf93720aa16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":1010},
            "size":{
              "width":745,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0464161fce854b0aa55d693c480679cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":1010},
                "size":{
                  "width":745,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u40.png"}},
{
          "id":"0251058545a543d8ad65495621ff8012",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":440},
            "size":{
              "width":10,
              "height":560},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/愈合变化/u76_line.png"}},
{
          "id":"7e0abdaeda2b4c65b3db7c5c089359f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":30,
              "height":547}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"102db369f1834546a82510c10ad1b274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":30,
                  "height":547}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u42.png"}},
{
          "id":"e486c44cf3d64623886302e1c96ce137",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":970,
              "y":452},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19fcae28ad1f4b79b239c832517d0902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":970,
                  "y":452},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u44.png"}},
{
          "id":"c22ac6724c83453db95290ac58b36706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":1020,
              "y":451},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498addf16d534c1a9c5733beb9590135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":451},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b355ccd8fe547159fcb8bc8d5dec64f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC33},
            "location":{
              "x":970,
              "y":499},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58ee8524eb954810a2e44e05ffa92369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC33},
                "location":{
                  "x":970,
                  "y":499},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u48.png"}},
{
          "id":"af58f7d6276b4a4499bdbbabad41ed24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":1020,
              "y":498},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0b09ee67c34b478a1c917f1c429fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":498},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74234b72442b4773a83e4f66ed642a4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":970,
              "y":543},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4ae99b0294042d2a658e93290ee7dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":970,
                  "y":543},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u52.png"}},
{
          "id":"a6e3854749864e1c973c17c47f7dac6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1020,
              "y":542},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a16a2133a3d4c18a034907bd28d8984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":542},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edc5518cd6ae409a888163cc8a459edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF9900CC},
            "location":{
              "x":970,
              "y":588},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9900CC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f419682549834250ae8b58aab3810c0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9900CC},
                "location":{
                  "x":970,
                  "y":588},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u56.png"}},
{
          "id":"50b9850f196e43adb56926b8e024fecc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":1020,
              "y":587},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d802b8283b14501bcd71ac74da61625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":587},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"326c20c29aa94fe98a5af970cef201c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451dc3feec0b47d7b7aac3f032cf5649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u60.png"}},
{
          "id":"aa8f2d4984c74381a79cf4202e8620aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2b80e1916143e98a918e00d4661d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71a0c750f3d049ca8f9aec3326f3aeda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d24824d5678a430ab09da9f1102aa3a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41429f28686549f5a84b38ebd107b255",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142a2d84d3ef40b5925c9080a910dfcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3db0a9b311f47b9a7c1fa5952082e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":450},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490ebce485494543acaa60adc7e0ea9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":450},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 总体",
                      "target":{
                        "targetType":"page",
                        "url":"总体.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0b2db0a907e4288a2ccd2f676658581",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":497},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295c5ca9ce8c4c969bec2019cb9f4993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":497},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 面积",
                      "target":{
                        "targetType":"page",
                        "url":"面积.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0027c8791ac849b9a1fae770413ad768",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":542},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef2314a9726c49409df5798568f17a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":542},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渗液量",
                      "target":{
                        "targetType":"page",
                        "url":"渗液量.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c614c935e0314c339e9098494df25aa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":587},
            "size":{
              "width":150,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a006b9831b584a029de9e7ca4b9c7f9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":587},
                "size":{
                  "width":150,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创面组织类型",
                      "target":{
                        "targetType":"page",
                        "url":"创面组织类型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8494895a93744e13b6a304b155b144fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":750,
              "y":620},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"324abe4f36394ca78dc4f5807a133db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":750,
                  "y":620},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aecca1c41cbe47faae8fcc8d8b48666b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":900},
            "size":{
              "width":536,
              "height":77},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef61edea1844f1c91bd0d32fe2ae63a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":404,
                  "y":900},
                "size":{
                  "width":536,
                  "height":77},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u85.png"}},
{
          "id":"12b44e484c3447d19267a32b63ec0ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":840},
            "size":{
              "width":183,
              "height":77},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d642b7b63048a398c8a64bdcc551d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":840},
                "size":{
                  "width":183,
                  "height":77},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u87.png"}},
{
          "id":"518b11f111944836a272301c6ad24691",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":862,
              "y":936},
            "size":{
              "width":159,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ad41c916ebf4f48a225abcf1ba17cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":862,
                  "y":936},
                "size":{
                  "width":159,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u89.png"}},
{
          "id":"55cdc311200f4bc08226aaee9d9e7561",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":946,
              "y":953},
            "size":{
              "width":159,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae75bb60ed124f1da0daa4a11ca6af9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":946,
                  "y":953},
                "size":{
                  "width":159,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u91.png"}},
{
          "id":"cc831a65dd3643ebae1868780f7a4e6e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":628},
            "size":{
              "width":10,
              "height":680},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/面积/u93_line.png"}},
{
          "id":"e644bce1c43047619d7a62bc82ac7c34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":620},
            "size":{
              "width":240,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8111cc21b1694d3d91919eba04b1d0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":620},
                "size":{
                  "width":240,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u94.png"}},
{
          "id":"a21558d8e1c1476eb7c61ef0384fabde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":730},
            "size":{
              "width":90,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a244ebb27204a62b402c23b7c5f5dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":730},
                "size":{
                  "width":90,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u96.png"}},
{
          "id":"2d62ad1c5cdf42ffb9509405c84df9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":760},
            "size":{
              "width":100,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df695d8760224af88caf4d29202663c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":760},
                "size":{
                  "width":100,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u98.png"}},
{
          "id":"c597fc87600143a6bdad289f85e18192",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":783},
            "size":{
              "width":100,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32d7f17885044049aa5e285366e9516d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":783},
                "size":{
                  "width":100,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u98.png"}},
{
          "id":"dcc8adb048b74891bbec4ad088216046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":810},
            "size":{
              "width":100,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475cd806738941f3b2438f76012ea6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":810},
                "size":{
                  "width":100,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u98.png"}},
{
          "id":"6d406d8799e74a30afb4dbfe2700cc07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":830},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f57aef8184a44b2abd07b1ec4034c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":830},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u104.png"}},
{
          "id":"6cd9998786944ae9b4c65ed403bf8c75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":843.5},
            "size":{
              "width":70,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479716fd690346fe984cda7c3a33e1ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":843.5},
                "size":{
                  "width":70,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面积/u104.png"}},
{
          "id":"0482e94c31f34da99650e15222e9a55b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9eea7094f18496b9c205affc3551204",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看图片记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看图片记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f98c7e39b14f4ab7a166b2d8b28bcb13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":434,
              "y":764},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ba525df0384de1bc867d33cc3f61be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":764},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae045b725a65486582959dd08c894585",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":580,
              "y":786},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4143aae688e64010a8b8db29bf8fe28a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":786},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ecc44f6666743ed8a30988fb4c5c328",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":727,
              "y":844},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77c6783a8da84310b15e56d52c244b0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":727,
                  "y":844},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aad6604e0b146d9981c7b604066bc34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":870,
              "y":875},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d74886ad0e242bfb341298ccf43d0f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":870,
                  "y":875},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14f3f62c2c42415c98247a23012e3505",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":1034,
              "y":929},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd18024258784cc793ea1a0b64402fdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":1034,
                  "y":929},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2d8ad82ca98a461f8dfc1c4d6d8580e3":{
      "scriptId":"u0"},
    "35b5a22cbdec4f47bc4e742e59b956ad":{
      "scriptId":"u1"},
    "82715bf837e8463282ac92385be3169f":{
      "scriptId":"u2"},
    "4f765306cf5b4776b24214d843b39f4a":{
      "scriptId":"u3"},
    "b1cf4906a3124fd99d9a30df4406976c":{
      "scriptId":"u4"},
    "5e08ce061bf443c8a1b980c30bf8695f":{
      "scriptId":"u5"},
    "2e8b388414d04b1d91e1ab9fbd17e6b3":{
      "scriptId":"u6"},
    "2364297f51fa4873a987b47718a4719e":{
      "scriptId":"u7"},
    "4c9051725ccb4eaba44a0580c676fc2b":{
      "scriptId":"u8"},
    "516ad05e968b4b9a82470f1759d56d2c":{
      "scriptId":"u9"},
    "6616baef46934745938f1ee7026219ce":{
      "scriptId":"u10"},
    "652202b8b59947f786b8c99cbd60ecf3":{
      "scriptId":"u11"},
    "8ae63d23162a48a1afbe681229b1b56b":{
      "scriptId":"u12"},
    "9ad433bbcc2742b79c7fcb6ce67dd523":{
      "scriptId":"u13"},
    "fc163c2ea8b341d3912983a7bde87c60":{
      "scriptId":"u14"},
    "6bd45cc1c587478c84753fa3ad98db2b":{
      "scriptId":"u15"},
    "74ac79480c6546419c0381b63b4f22be":{
      "scriptId":"u16"},
    "49ebf9667a9e4e95ac624a1b6ab41ee4":{
      "scriptId":"u17"},
    "55b0bbaae6374126b858d08a284dde7c":{
      "scriptId":"u18"},
    "44511ef97f4a44d296cd3c14b495cb9c":{
      "scriptId":"u19"},
    "51a014247ca441b5acb2268930451c91":{
      "scriptId":"u20"},
    "b6148360ef1a4d339b66bc86dc591cf7":{
      "scriptId":"u21"},
    "9c1870325a2a4db5b60d6fb7d27b316b":{
      "scriptId":"u22"},
    "02aac61a921248a1b880caf895f78551":{
      "scriptId":"u23"},
    "3e053a2000a24b639b058f6d8d587650":{
      "scriptId":"u24"},
    "e611c2ccd03d46be8fd326f37f46779a":{
      "scriptId":"u25"},
    "d78a502d02aa47bd9d813aa0467f025b":{
      "scriptId":"u26"},
    "1447e3a0e8ab4c428844fe3716b73b8a":{
      "scriptId":"u27"},
    "f9dc9b770446420dbc1d72e37809886c":{
      "scriptId":"u28"},
    "265f5cfff04b40f5b808c9f9039f2738":{
      "scriptId":"u29"},
    "312fc5698f564526b38faaf3e12f9348":{
      "scriptId":"u30"},
    "d41f871a5ee94647a9e9095b0f8da299":{
      "scriptId":"u31"},
    "f467b65986cf46b799f42996e0579f27":{
      "scriptId":"u32"},
    "4e753795db7c4c4391b624697e6736f0":{
      "scriptId":"u33"},
    "f1a8659d191145ea8ba3fd1c4eae288b":{
      "scriptId":"u34"},
    "bb04fa5f3b0447a28908ccd82f7d81dc":{
      "scriptId":"u35"},
    "7f6fd22232f342fc97fe9133cf8d1463":{
      "scriptId":"u36"},
    "7be1175edb944d6d9fa7d3a5170fb8b5":{
      "scriptId":"u37"},
    "47778aa5402944fc88dd2522b6f0c43e":{
      "scriptId":"u38"},
    "07b46a31c2c740e7b3980541c6752f41":{
      "scriptId":"u39"},
    "82a38270e87a4cab992e97524df182bf":{
      "scriptId":"u40"},
    "0fb0221802f64e0da678eaa62819231c":{
      "scriptId":"u41"},
    "a6b504d3d6f5472bb8450737f7fdeb8c":{
      "scriptId":"u42"},
    "f836871b12264205925a9ffe98d61fd8":{
      "scriptId":"u43"},
    "93edd714afcf4cf1a7e48239fa20c601":{
      "scriptId":"u44"},
    "7ee6a9ee8cb347dcac087a7b822fde7b":{
      "scriptId":"u45"},
    "e430053a08b043b28e3e4bf93720aa16":{
      "scriptId":"u46"},
    "0464161fce854b0aa55d693c480679cd":{
      "scriptId":"u47"},
    "0251058545a543d8ad65495621ff8012":{
      "scriptId":"u48"},
    "7e0abdaeda2b4c65b3db7c5c089359f9":{
      "scriptId":"u49"},
    "102db369f1834546a82510c10ad1b274":{
      "scriptId":"u50"},
    "e486c44cf3d64623886302e1c96ce137":{
      "scriptId":"u51"},
    "19fcae28ad1f4b79b239c832517d0902":{
      "scriptId":"u52"},
    "c22ac6724c83453db95290ac58b36706":{
      "scriptId":"u53"},
    "498addf16d534c1a9c5733beb9590135":{
      "scriptId":"u54"},
    "9b355ccd8fe547159fcb8bc8d5dec64f":{
      "scriptId":"u55"},
    "58ee8524eb954810a2e44e05ffa92369":{
      "scriptId":"u56"},
    "af58f7d6276b4a4499bdbbabad41ed24":{
      "scriptId":"u57"},
    "9e0b09ee67c34b478a1c917f1c429fbb":{
      "scriptId":"u58"},
    "74234b72442b4773a83e4f66ed642a4c":{
      "scriptId":"u59"},
    "c4ae99b0294042d2a658e93290ee7dd7":{
      "scriptId":"u60"},
    "a6e3854749864e1c973c17c47f7dac6d":{
      "scriptId":"u61"},
    "0a16a2133a3d4c18a034907bd28d8984":{
      "scriptId":"u62"},
    "edc5518cd6ae409a888163cc8a459edb":{
      "scriptId":"u63"},
    "f419682549834250ae8b58aab3810c0b":{
      "scriptId":"u64"},
    "50b9850f196e43adb56926b8e024fecc":{
      "scriptId":"u65"},
    "5d802b8283b14501bcd71ac74da61625":{
      "scriptId":"u66"},
    "326c20c29aa94fe98a5af970cef201c4":{
      "scriptId":"u67"},
    "451dc3feec0b47d7b7aac3f032cf5649":{
      "scriptId":"u68"},
    "aa8f2d4984c74381a79cf4202e8620aa":{
      "scriptId":"u69"},
    "bc2b80e1916143e98a918e00d4661d8a":{
      "scriptId":"u70"},
    "71a0c750f3d049ca8f9aec3326f3aeda":{
      "scriptId":"u71"},
    "d24824d5678a430ab09da9f1102aa3a4":{
      "scriptId":"u72"},
    "41429f28686549f5a84b38ebd107b255":{
      "scriptId":"u73"},
    "142a2d84d3ef40b5925c9080a910dfcb":{
      "scriptId":"u74"},
    "b3db0a9b311f47b9a7c1fa5952082e85":{
      "scriptId":"u75"},
    "490ebce485494543acaa60adc7e0ea9b":{
      "scriptId":"u76"},
    "d0b2db0a907e4288a2ccd2f676658581":{
      "scriptId":"u77"},
    "295c5ca9ce8c4c969bec2019cb9f4993":{
      "scriptId":"u78"},
    "0027c8791ac849b9a1fae770413ad768":{
      "scriptId":"u79"},
    "ef2314a9726c49409df5798568f17a88":{
      "scriptId":"u80"},
    "c614c935e0314c339e9098494df25aa2":{
      "scriptId":"u81"},
    "a006b9831b584a029de9e7ca4b9c7f9b":{
      "scriptId":"u82"},
    "8494895a93744e13b6a304b155b144fc":{
      "scriptId":"u83"},
    "324abe4f36394ca78dc4f5807a133db5":{
      "scriptId":"u84"},
    "aecca1c41cbe47faae8fcc8d8b48666b":{
      "scriptId":"u85"},
    "5ef61edea1844f1c91bd0d32fe2ae63a":{
      "scriptId":"u86"},
    "12b44e484c3447d19267a32b63ec0ffe":{
      "scriptId":"u87"},
    "68d642b7b63048a398c8a64bdcc551d2":{
      "scriptId":"u88"},
    "518b11f111944836a272301c6ad24691":{
      "scriptId":"u89"},
    "1ad41c916ebf4f48a225abcf1ba17cbf":{
      "scriptId":"u90"},
    "55cdc311200f4bc08226aaee9d9e7561":{
      "scriptId":"u91"},
    "ae75bb60ed124f1da0daa4a11ca6af9a":{
      "scriptId":"u92"},
    "cc831a65dd3643ebae1868780f7a4e6e":{
      "scriptId":"u93"},
    "e644bce1c43047619d7a62bc82ac7c34":{
      "scriptId":"u94"},
    "8111cc21b1694d3d91919eba04b1d0b1":{
      "scriptId":"u95"},
    "a21558d8e1c1476eb7c61ef0384fabde":{
      "scriptId":"u96"},
    "2a244ebb27204a62b402c23b7c5f5dd8":{
      "scriptId":"u97"},
    "2d62ad1c5cdf42ffb9509405c84df9e3":{
      "scriptId":"u98"},
    "df695d8760224af88caf4d29202663c8":{
      "scriptId":"u99"},
    "c597fc87600143a6bdad289f85e18192":{
      "scriptId":"u100"},
    "32d7f17885044049aa5e285366e9516d":{
      "scriptId":"u101"},
    "dcc8adb048b74891bbec4ad088216046":{
      "scriptId":"u102"},
    "475cd806738941f3b2438f76012ea6f5":{
      "scriptId":"u103"},
    "6d406d8799e74a30afb4dbfe2700cc07":{
      "scriptId":"u104"},
    "8f57aef8184a44b2abd07b1ec4034c1d":{
      "scriptId":"u105"},
    "6cd9998786944ae9b4c65ed403bf8c75":{
      "scriptId":"u106"},
    "479716fd690346fe984cda7c3a33e1ba":{
      "scriptId":"u107"},
    "0482e94c31f34da99650e15222e9a55b":{
      "scriptId":"u108"},
    "a9eea7094f18496b9c205affc3551204":{
      "scriptId":"u109"},
    "f98c7e39b14f4ab7a166b2d8b28bcb13":{
      "scriptId":"u110"},
    "d1ba525df0384de1bc867d33cc3f61be":{
      "scriptId":"u111"},
    "ae045b725a65486582959dd08c894585":{
      "scriptId":"u112"},
    "4143aae688e64010a8b8db29bf8fe28a":{
      "scriptId":"u113"},
    "9ecc44f6666743ed8a30988fb4c5c328":{
      "scriptId":"u114"},
    "77c6783a8da84310b15e56d52c244b0c":{
      "scriptId":"u115"},
    "0aad6604e0b146d9981c7b604066bc34":{
      "scriptId":"u116"},
    "4d74886ad0e242bfb341298ccf43d0f0":{
      "scriptId":"u117"},
    "14f3f62c2c42415c98247a23012e3505":{
      "scriptId":"u118"},
    "cd18024258784cc793ea1a0b64402fdb":{
      "scriptId":"u119"}}});