$axure.loadCurrentPage({
  "url":"同步归档.html",
  "generationDate":new Date(1524492044023.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"548de34129cf40ad83fc70930935bdb7",
    "type":"Axure:Page",
    "name":"同步归档",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"de7c5c331584491bbfddb7529c8a159e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb030bd04144074b25b48558bae1aae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"4a2df15261994385aed06b75753b7546",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f3bca261a04dd296ca1cf9e2877cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"01d0ab566b7a431c8cbb8f2e5c68c5ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3dbc86d289047d6884a3a919a927b7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"eaa9b84b933842b88f3cc2f128bb6b16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99c925d73a44ee5aecdbd1b0fe79673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"8aaecc8018654da2ba03ab42909ed434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96fafc0b05c54eafb1330d97faf6277a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"59816175013f4388af4b0933b7362c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":349,
              "y":290},
            "size":{
              "width":778,
              "height":757},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055cb829899c4ad499c0543dfe92b9dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":349,
                  "y":290},
                "size":{
                  "width":778,
                  "height":757},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u10.png"}},
{
          "id":"9649c1c2511b403582804953e2f848e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15078520f53f43b69964df8fe033d377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8438e423e69546d49377391afbb4de17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1816fccbe8744218bf86cc13b298221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u30.png"}},
{
          "id":"b738364d4b4942998879313fccf4d5cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2fce5829ee04b8ba28c458f21ca2782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"78c4f3b96c6e4e2bbbd4efc73ac73771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9c6481fcf04e47a6400393a000f4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3681e21a7f234a87ad5ace5005dd4c3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9b853454b7c40d685bb20c25ca6f55a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u36.png"}},
{
          "id":"6960ebd416dd4b88ae85e63c94081269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ca27265b774f31a84d98a1a43fbe0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a754c3edd34e17b432ce593ee8c4c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeaa59a1b80411184a6ec0e55d2fde4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"006355e0adaa46849389e76343273bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c534dbfdf134492af5bc05b3c0c8d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf009a35ea464690ad1cbdd1c14f6f3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":776,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fb3561afa5478784ac2b5754362086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":776,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c05e00ae024abfb325611cebc1b503",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":350,
              "y":256},
            "size":{
              "width":386,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fed27f2a740945e0a3e206356d593105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":256},
                "size":{
                  "width":386,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fa589349d2243fda540be52ea76da0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":736,
              "y":256},
            "size":{
              "width":390,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b140182e294647e1b33c07563c116729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":736,
                  "y":256},
                "size":{
                  "width":390,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa878796c6ff4b6aa3f04243cc042149",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":467,
              "y":290},
            "size":{
              "width":161,
              "height":1},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be11a0c550d944d5b4810ba6f472f4b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":467,
                  "y":290},
                "size":{
                  "width":161,
                  "height":1},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者伤口信息历史/u18.png"}},
{
          "id":"2636ec7d30f34612a9fa0697207db89c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":304},
            "size":{
              "width":740,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"63ba3cb5901c4271bef98d79d41a907d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":370,
              "y":309},
            "size":{
              "width":739,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ce6b5e412d46f1900f66bc7e61ceb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":309},
                "size":{
                  "width":739,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ea28619692c4f2c819b357096b8f71a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":307.5},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40f9bb867bed4673b3d8c8864e05189f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":307.5},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u39.png"}},
{
          "id":"5904f5d8a79849b7a7bbe913c89107a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":303},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31947c1f12e445609b6a7da538fc79a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":303},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u41.png"}},
{
          "id":"63a5274320db4fe9844970c18ef2e14f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":343},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fd18a1eee894876b5d28a352271de37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":343},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"fd9f1d3074a14cc5a83ac882265c9c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":396},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6bb1a6af0242daab7617bf118377b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":396},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"5571106d15d64efe98b2278fa1a5f614",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":449},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ece5f3ce674fd3989078f1f4f0810d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":449},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"fc0df86bf5fb42f3ae4f3e8c89d10276",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":502},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b68935cd8a40058f081b4e2095ff18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":502},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"51acbaa726bf4ebb916d96a987e19f61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":555},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e6c711c50ab4e3bb0a0793c621bb9b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":555},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"dbf5ca9067594d1bbdd35788239434f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":608},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36ffe8791ff4c85aba137ce64385af3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":608},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"ba7a5bd2eea14da49f51e4156719ac10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":351,
              "y":661},
            "size":{
              "width":774,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c2d4390adda4f8189870c8c1d81fc08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":351,
                  "y":661},
                "size":{
                  "width":774,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/同步归档/u43.png"}},
{
          "id":"17d9783e7bfe4940930e3cdcdfdf6c96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":353.5},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e162a03d0b745978f99b7b877e1a7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":353.5},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"ac7ac4c5697f4661b24a2babee0e98d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":404},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7aa0276ecd1426188a6e31e2ba2e06b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":404},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"db00532a4d514fc2b361a94dcc34cead",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":460},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2d3df8061874b27bece401ea2e84430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":460},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"dcaab87d686d400e9c29315511760df2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":510},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d526ad726ea04addb4956fbf7f689ad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":510},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"34baaf5cbaa84f919ff20440d3b7ac9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":565.5},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc8952018de24dbeab8df06d2851eba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":565.5},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"66227ae490f244e38d2ad4c70c905668",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":620},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950a90b6e9854114a0f944ac183ca4c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":620},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"1528ccc7c3fc41e29dd6532d172c7849",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":670},
            "size":{
              "width":30,
              "height":30},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066ffebdf67c4f19b4ea5c2725165481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":670},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/录入_1/u359.png"}},
{
          "id":"d3679f0539354e1083fc0a8a3c07ba51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1050,
              "y":346},
            "size":{
              "width":70,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10374b3c0f1f4e5fb54eafb4f9224113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1050,
                  "y":346},
                "size":{
                  "width":70,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 疑难伤口",
                      "target":{
                        "targetType":"page",
                        "url":"疑难伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0acaaab067854e198064776fda9d21b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1055,
              "y":451.5},
            "size":{
              "width":70,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d197b355f6da4805be9f30a4f16aa745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1055,
                  "y":451.5},
                "size":{
                  "width":70,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者列表",
                      "target":{
                        "targetType":"page",
                        "url":"患者列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfd5c528cb3247838ed108ceee225065",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1055,
              "y":611.5},
            "size":{
              "width":70,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51103791ce22459b8169cdf144c07d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1055,
                  "y":611.5},
                "size":{
                  "width":70,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 完整病历",
                      "target":{
                        "targetType":"page",
                        "url":"完整病历.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a2e7055bb7a45ffa93d84647d87cb17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1055,
              "y":663},
            "size":{
              "width":70,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c20730480b84604b9b07c017b2f3df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1055,
                  "y":663},
                "size":{
                  "width":70,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 不完整病历",
                      "target":{
                        "targetType":"page",
                        "url":"不完整病历_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cca50a852e244c380f4deef5475f50a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be55dd2af3594b888f996fb40398b302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"d65ac8c2616e43a58bf7253ad71f0c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b52d1c8716488ab70555e6500ec9d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a96d99e74374dc8b6d28da97ccb848a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b99b51b8b5d84e1791dc83cc96d8fb6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32c673949be84e79bfcbadd680c8f983",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411b6eb7f7954785ba95df2fab18418c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5afcc39b76844de59a6d3f9ef83652a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":840,
              "y":247},
            "size":{
              "width":190,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09bb3332182042e7bc4dd918cb72b940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":840,
                  "y":247},
                "size":{
                  "width":190,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 一键同步云端",
                      "target":{
                        "targetType":"page",
                        "url":"一键同步云端.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "de7c5c331584491bbfddb7529c8a159e":{
      "scriptId":"u0"},
    "4fb030bd04144074b25b48558bae1aae":{
      "scriptId":"u1"},
    "4a2df15261994385aed06b75753b7546":{
      "scriptId":"u2"},
    "36f3bca261a04dd296ca1cf9e2877cbf":{
      "scriptId":"u3"},
    "01d0ab566b7a431c8cbb8f2e5c68c5ef":{
      "scriptId":"u4"},
    "a3dbc86d289047d6884a3a919a927b7f":{
      "scriptId":"u5"},
    "eaa9b84b933842b88f3cc2f128bb6b16":{
      "scriptId":"u6"},
    "d99c925d73a44ee5aecdbd1b0fe79673":{
      "scriptId":"u7"},
    "8aaecc8018654da2ba03ab42909ed434":{
      "scriptId":"u8"},
    "96fafc0b05c54eafb1330d97faf6277a":{
      "scriptId":"u9"},
    "59816175013f4388af4b0933b7362c92":{
      "scriptId":"u10"},
    "055cb829899c4ad499c0543dfe92b9dc":{
      "scriptId":"u11"},
    "9649c1c2511b403582804953e2f848e1":{
      "scriptId":"u12"},
    "15078520f53f43b69964df8fe033d377":{
      "scriptId":"u13"},
    "8438e423e69546d49377391afbb4de17":{
      "scriptId":"u14"},
    "c1816fccbe8744218bf86cc13b298221":{
      "scriptId":"u15"},
    "b738364d4b4942998879313fccf4d5cd":{
      "scriptId":"u16"},
    "e2fce5829ee04b8ba28c458f21ca2782":{
      "scriptId":"u17"},
    "78c4f3b96c6e4e2bbbd4efc73ac73771":{
      "scriptId":"u18"},
    "bb9c6481fcf04e47a6400393a000f4f3":{
      "scriptId":"u19"},
    "3681e21a7f234a87ad5ace5005dd4c3a":{
      "scriptId":"u20"},
    "a9b853454b7c40d685bb20c25ca6f55a":{
      "scriptId":"u21"},
    "6960ebd416dd4b88ae85e63c94081269":{
      "scriptId":"u22"},
    "85ca27265b774f31a84d98a1a43fbe0e":{
      "scriptId":"u23"},
    "31a754c3edd34e17b432ce593ee8c4c0":{
      "scriptId":"u24"},
    "fbeaa59a1b80411184a6ec0e55d2fde4":{
      "scriptId":"u25"},
    "006355e0adaa46849389e76343273bc1":{
      "scriptId":"u26"},
    "9c534dbfdf134492af5bc05b3c0c8d99":{
      "scriptId":"u27"},
    "cf009a35ea464690ad1cbdd1c14f6f3a":{
      "scriptId":"u28"},
    "f5fb3561afa5478784ac2b5754362086":{
      "scriptId":"u29"},
    "98c05e00ae024abfb325611cebc1b503":{
      "scriptId":"u30"},
    "fed27f2a740945e0a3e206356d593105":{
      "scriptId":"u31"},
    "6fa589349d2243fda540be52ea76da0f":{
      "scriptId":"u32"},
    "b140182e294647e1b33c07563c116729":{
      "scriptId":"u33"},
    "fa878796c6ff4b6aa3f04243cc042149":{
      "scriptId":"u34"},
    "be11a0c550d944d5b4810ba6f472f4b1":{
      "scriptId":"u35"},
    "2636ec7d30f34612a9fa0697207db89c":{
      "scriptId":"u36"},
    "63ba3cb5901c4271bef98d79d41a907d":{
      "scriptId":"u37"},
    "09ce6b5e412d46f1900f66bc7e61ceb4":{
      "scriptId":"u38"},
    "0ea28619692c4f2c819b357096b8f71a":{
      "scriptId":"u39"},
    "40f9bb867bed4673b3d8c8864e05189f":{
      "scriptId":"u40"},
    "5904f5d8a79849b7a7bbe913c89107a2":{
      "scriptId":"u41"},
    "31947c1f12e445609b6a7da538fc79a4":{
      "scriptId":"u42"},
    "63a5274320db4fe9844970c18ef2e14f":{
      "scriptId":"u43"},
    "1fd18a1eee894876b5d28a352271de37":{
      "scriptId":"u44"},
    "fd9f1d3074a14cc5a83ac882265c9c45":{
      "scriptId":"u45"},
    "fb6bb1a6af0242daab7617bf118377b8":{
      "scriptId":"u46"},
    "5571106d15d64efe98b2278fa1a5f614":{
      "scriptId":"u47"},
    "b3ece5f3ce674fd3989078f1f4f0810d":{
      "scriptId":"u48"},
    "fc0df86bf5fb42f3ae4f3e8c89d10276":{
      "scriptId":"u49"},
    "76b68935cd8a40058f081b4e2095ff18":{
      "scriptId":"u50"},
    "51acbaa726bf4ebb916d96a987e19f61":{
      "scriptId":"u51"},
    "7e6c711c50ab4e3bb0a0793c621bb9b4":{
      "scriptId":"u52"},
    "dbf5ca9067594d1bbdd35788239434f4":{
      "scriptId":"u53"},
    "d36ffe8791ff4c85aba137ce64385af3":{
      "scriptId":"u54"},
    "ba7a5bd2eea14da49f51e4156719ac10":{
      "scriptId":"u55"},
    "1c2d4390adda4f8189870c8c1d81fc08":{
      "scriptId":"u56"},
    "17d9783e7bfe4940930e3cdcdfdf6c96":{
      "scriptId":"u57"},
    "2e162a03d0b745978f99b7b877e1a7b6":{
      "scriptId":"u58"},
    "ac7ac4c5697f4661b24a2babee0e98d7":{
      "scriptId":"u59"},
    "a7aa0276ecd1426188a6e31e2ba2e06b":{
      "scriptId":"u60"},
    "db00532a4d514fc2b361a94dcc34cead":{
      "scriptId":"u61"},
    "a2d3df8061874b27bece401ea2e84430":{
      "scriptId":"u62"},
    "dcaab87d686d400e9c29315511760df2":{
      "scriptId":"u63"},
    "d526ad726ea04addb4956fbf7f689ad4":{
      "scriptId":"u64"},
    "34baaf5cbaa84f919ff20440d3b7ac9c":{
      "scriptId":"u65"},
    "cc8952018de24dbeab8df06d2851eba8":{
      "scriptId":"u66"},
    "66227ae490f244e38d2ad4c70c905668":{
      "scriptId":"u67"},
    "950a90b6e9854114a0f944ac183ca4c0":{
      "scriptId":"u68"},
    "1528ccc7c3fc41e29dd6532d172c7849":{
      "scriptId":"u69"},
    "066ffebdf67c4f19b4ea5c2725165481":{
      "scriptId":"u70"},
    "d3679f0539354e1083fc0a8a3c07ba51":{
      "scriptId":"u71"},
    "10374b3c0f1f4e5fb54eafb4f9224113":{
      "scriptId":"u72"},
    "0acaaab067854e198064776fda9d21b7":{
      "scriptId":"u73"},
    "d197b355f6da4805be9f30a4f16aa745":{
      "scriptId":"u74"},
    "cfd5c528cb3247838ed108ceee225065":{
      "scriptId":"u75"},
    "51103791ce22459b8169cdf144c07d19":{
      "scriptId":"u76"},
    "7a2e7055bb7a45ffa93d84647d87cb17":{
      "scriptId":"u77"},
    "7c20730480b84604b9b07c017b2f3df1":{
      "scriptId":"u78"},
    "0cca50a852e244c380f4deef5475f50a":{
      "scriptId":"u79"},
    "be55dd2af3594b888f996fb40398b302":{
      "scriptId":"u80"},
    "d65ac8c2616e43a58bf7253ad71f0c9b":{
      "scriptId":"u81"},
    "f4b52d1c8716488ab70555e6500ec9d0":{
      "scriptId":"u82"},
    "0a96d99e74374dc8b6d28da97ccb848a":{
      "scriptId":"u83"},
    "b99b51b8b5d84e1791dc83cc96d8fb6f":{
      "scriptId":"u84"},
    "32c673949be84e79bfcbadd680c8f983":{
      "scriptId":"u85"},
    "411b6eb7f7954785ba95df2fab18418c":{
      "scriptId":"u86"},
    "5afcc39b76844de59a6d3f9ef83652a7":{
      "scriptId":"u87"},
    "09bb3332182042e7bc4dd918cb72b940":{
      "scriptId":"u88"}}});