$axure.loadCurrentPage({
  "url":"单个开放性伤口的缝线伤口.html",
  "generationDate":new Date(1524492039197.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8874ded7a0224c53928bb19329c5a327",
    "type":"Axure:Page",
    "name":"单个开放性伤口的缝线伤口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"37f7f51fcd8a433dba5665a03738a0ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37f31eda62b46ddb2c01feed48cc66d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"5f1bea8e68764e5d89e888d899a86c9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":47},
            "size":{
              "width":880,
              "height":676},
            "rotation":"0",
            "textRotation":"270",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efd85f9babbe4d04b9ef59160b40f8a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":47},
                "size":{
                  "width":880,
                  "height":676},
                "rotation":"0",
                "textRotation":"270",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口的缝线伤口/u2.png"}},
{
          "id":"dc237d37a5ab4aaa8f394cd343d0c319",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":679},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45d5cc62b2c4675ba3fd4cef4e8f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":679},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u4.png"}},
{
          "id":"f5b28ddf8c464ff09efe36663a94580f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":359},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85d973c5caa447fbaa439633e97d060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1190,
                  "y":359},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄后",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄后_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/单个开放性伤口/u6.png"}},
{
          "id":"caeb5621e5a9406288c96ab10a0ea66d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":520,
              "y":70},
            "size":{
              "width":390,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9775ddee38c04333b5805a1f0ac7267d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":520,
                  "y":70},
                "size":{
                  "width":390,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单个开放性伤口/u8.png"}},
{
          "id":"9775e6e923084e2ca1e8a878db687d2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1198,
              "y":679},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e180999e5c1f4887be202cfb900b3616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1198,
                  "y":679},
                "size":{
                  "width":60,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb996345c33544ef80bb183e00b8589d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":682},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582c6c90680d479bbc9e5d1a7c423309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":682},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"6de1c3ae6fc44231a9fd3d5c93426863",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":1168,
              "y":673},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b34e8f0d9241f888cfaab3b91f724a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":1168,
                  "y":673},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 拍摄与测量清创前伤口",
                      "target":{
                        "targetType":"page",
                        "url":"拍摄与测量清创前伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88fbed6c78f941c6aafb155ffd25a9df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":820},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 复诊-上次比对",
                      "target":{
                        "targetType":"page",
                        "url":"复诊-上次比对.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "37f7f51fcd8a433dba5665a03738a0ac":{
      "scriptId":"u0"},
    "e37f31eda62b46ddb2c01feed48cc66d":{
      "scriptId":"u1"},
    "5f1bea8e68764e5d89e888d899a86c9c":{
      "scriptId":"u2"},
    "efd85f9babbe4d04b9ef59160b40f8a1":{
      "scriptId":"u3"},
    "dc237d37a5ab4aaa8f394cd343d0c319":{
      "scriptId":"u4"},
    "d45d5cc62b2c4675ba3fd4cef4e8f87f":{
      "scriptId":"u5"},
    "f5b28ddf8c464ff09efe36663a94580f":{
      "scriptId":"u6"},
    "d85d973c5caa447fbaa439633e97d060":{
      "scriptId":"u7"},
    "caeb5621e5a9406288c96ab10a0ea66d":{
      "scriptId":"u8"},
    "9775ddee38c04333b5805a1f0ac7267d":{
      "scriptId":"u9"},
    "9775e6e923084e2ca1e8a878db687d2e":{
      "scriptId":"u10"},
    "e180999e5c1f4887be202cfb900b3616":{
      "scriptId":"u11"},
    "eb996345c33544ef80bb183e00b8589d":{
      "scriptId":"u12"},
    "582c6c90680d479bbc9e5d1a7c423309":{
      "scriptId":"u13"},
    "6de1c3ae6fc44231a9fd3d5c93426863":{
      "scriptId":"u14"},
    "e9b34e8f0d9241f888cfaab3b91f724a":{
      "scriptId":"u15"},
    "88fbed6c78f941c6aafb155ffd25a9df":{
      "scriptId":"u16"}}});