$axure.loadCurrentPage({
  "url":"拍摄后_2.html",
  "generationDate":new Date(1524492039302.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5311bf88004e4a3d8d7f2169f24e21db",
    "type":"Axure:Page",
    "name":"拍摄后",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d79bf2c1073a47ee9fca80cf6232dc32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":-256},
            "size":{
              "width":774,
              "height":1281},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"903f9bdd4d3843878432ef28b5ffa134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":-256},
                "size":{
                  "width":774,
                  "height":1281},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"dde79fd78b8b492dadedb024223674d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":47},
            "size":{
              "width":1020,
              "height":676},
            "rotation":"0",
            "textRotation":"270",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fbbbd77fc544bc2bcfcf0b251fee5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":47},
                "size":{
                  "width":1020,
                  "height":676},
                "rotation":"0",
                "textRotation":"270",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 圈画伤口",
                      "target":{
                        "targetType":"page",
                        "url":"圈画伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后_2/u2.png"}},
{
          "id":"07f5dbedaad8410bb1d11cdbe3955765",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-108,
              "y":366},
            "size":{
              "width":677,
              "height":40},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118ae2ab9914465dbf95500964582646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-108,
                  "y":366},
                "size":{
                  "width":677,
                  "height":40},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"ba8c429af43744fa86b75f10d3b9402c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":1170,
              "y":680},
            "size":{
              "width":90,
              "height":30},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1de10cc91ee243799a953e94c3545888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":1170,
                  "y":680},
                "size":{
                  "width":90,
                  "height":30},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个开放性伤口",
                      "target":{
                        "targetType":"page",
                        "url":"单个开放性伤口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/拍摄后/u6.png"}},
{
          "id":"25017dd490e64cfa9b004b869c726159",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":1170,
              "y":78},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037665bf7d08421cbed82bac013c35fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":1170,
                  "y":78},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后/u8.png"}},
{
          "id":"c093669168024fbdab045800be4d4a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":634,
              "y":70.5},
            "size":{
              "width":214,
              "height":40},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b71478a8661342fa8082653a0f51e7d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":634,
                  "y":70.5},
                "size":{
                  "width":214,
                  "height":40},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拍摄后_2/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d79bf2c1073a47ee9fca80cf6232dc32":{
      "scriptId":"u0"},
    "903f9bdd4d3843878432ef28b5ffa134":{
      "scriptId":"u1"},
    "dde79fd78b8b492dadedb024223674d4":{
      "scriptId":"u2"},
    "9fbbbd77fc544bc2bcfcf0b251fee5d0":{
      "scriptId":"u3"},
    "07f5dbedaad8410bb1d11cdbe3955765":{
      "scriptId":"u4"},
    "118ae2ab9914465dbf95500964582646":{
      "scriptId":"u5"},
    "ba8c429af43744fa86b75f10d3b9402c":{
      "scriptId":"u6"},
    "1de10cc91ee243799a953e94c3545888":{
      "scriptId":"u7"},
    "25017dd490e64cfa9b004b869c726159":{
      "scriptId":"u8"},
    "037665bf7d08421cbed82bac013c35fc":{
      "scriptId":"u9"},
    "c093669168024fbdab045800be4d4a29":{
      "scriptId":"u10"},
    "b71478a8661342fa8082653a0f51e7d8":{
      "scriptId":"u11"}}});