$axure.loadCurrentPage({
  "url":"创面组织类型.html",
  "generationDate":new Date(1524492043597.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ad8b3f8524b46a69e1dded09279ada2",
    "type":"Axure:Page",
    "name":"创面组织类型",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1f26d687a6e84017904af433113d6b22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":0},
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8079ca770d324f1e86a0224f6e8864db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u0.png"}},
{
          "id":"90ac738207384441a56af45037c76911",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":110},
            "size":{
              "width":777,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccabde0a953a4861ab3b80bfda1a5d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":110},
                "size":{
                  "width":777,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u2.png"}},
{
          "id":"11cb363e1a80482693c0ae41b876f18f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "location":{
              "x":351,
              "y":1040},
            "size":{
              "width":774,
              "height":101},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEFEFF4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb06d8ac51844e2e8a0dd4b820eae3e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "location":{
                  "x":351,
                  "y":1040},
                "size":{
                  "width":774,
                  "height":101},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEFEFF4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u4.png"}},
{
          "id":"647f32df6ea44b198a3686426bde748b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdbde86ecc4a4e34be53062e5b80436a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u6.png"}},
{
          "id":"a8d8b41090d142188873ff61e99253b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":150},
            "size":{
              "width":776,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e7c41c6c78c4455bc7b6fbc2c2b38ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":150},
                "size":{
                  "width":776,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u8.png"}},
{
          "id":"9d3b0b140cf642cca075f5a2b45956c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":178},
            "size":{
              "width":139,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9987b30691804f6886cc32db7f55e1b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":178},
                "size":{
                  "width":139,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34528248bfe5488aa16cb1f1489f7e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":374,
              "y":260},
            "size":{
              "width":776,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4220144e41024a358185e981836a205c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":260},
                "size":{
                  "width":776,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54d9a06ddf834e1f86021935af088550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":456,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb33f6d08bc4b9f88f734cd94fcb685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a9363848716472799ce56b0a8490aa7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"551115bb8f2745c08e1cbdfeee70e23b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u32.png"}},
{
          "id":"f54ed51ee55647dca82ddee10bbec561",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":620,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d6dd041a7e46d399577962ad39e8ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3773599e0f8c41938ec79cabe515b1f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60D410,
              "opacity":1},
            "location":{
              "x":779,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9eb4c3261874bec94bb8ff895e44afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60D410,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee0e574f0b5f45d2967fedcee5bf7543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"685ceb2a83654768b710ff60238eb095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者登记/u40.png"}},
{
          "id":"afdbde27a25b4e04a9d6cadd659420fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":938,
              "y":1111},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b063bdcc2b574be1a48ad5e6050f6ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":938,
                  "y":1111},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ae69a3c42b401781a8bf9647f8cb17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3551485b51e24bb9800e8776b2d08672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在我院进行检查/u39.png"}},
{
          "id":"63887e849116485382e910ab9fc43277",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"26px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":398,
              "y":178},
            "size":{
              "width":728,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"402bedb239bc414893b04c797034b716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"26px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":178},
                "size":{
                  "width":728,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4828b385ede749bfac9e485811e351d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":360,
              "y":171},
            "size":{
              "width":90,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18db17562d0045c8ba481845addaf941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":360,
                  "y":171},
                "size":{
                  "width":90,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"103ce4d0b95b45efa63dd0068d39af61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be27756f7b7a459d9e8ea206e499a0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u26.png"}},
{
          "id":"9df20f452e5b4403974cc039d46ee39b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":1059},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61af83a27f9b4b94b993af40bc47bf66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":1059},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/伤口记录/u34.png"}},
{
          "id":"21137d8bf7ba4b3ba6cccfc64a72d5a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":370,
              "y":396},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c6963a7c46848dc8b84b895b96f976b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":396},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e312ee57b7e745908e8642ffdd1352f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":570},
            "size":{
              "width":754,
              "height":460},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a34e0bcb51f47579f487f96bb122d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":570},
                "size":{
                  "width":754,
                  "height":460},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u32.png"}},
{
          "id":"3d5b691690e54ca78c7449d285427fa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":520},
            "size":{
              "width":14,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75cffcaca72d42d9837ba717f8f54cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":356,
                  "y":520},
                "size":{
                  "width":14,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u34.png"}},
{
          "id":"24e9e61be89041f5aae13af317cd9753",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":540},
            "size":{
              "width":745,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6fb3cfe32541eca4c2e17226ef5840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":540},
                "size":{
                  "width":745,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u36.png"}},
{
          "id":"dcabab001c5c4035a919c8efde33c242",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":530},
            "size":{
              "width":10,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fba7f3bfed745a192f24427676488a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1110,
                  "y":530},
                "size":{
                  "width":10,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u38.png"}},
{
          "id":"edd2bdf92b064ecebb2bf0f830252c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":1010},
            "size":{
              "width":745,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87906c22fa564ab1a192473638d834f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":1010},
                "size":{
                  "width":745,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u40.png"}},
{
          "id":"ee9b1461f7be458d85ea9f60cab077fe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":440},
            "size":{
              "width":10,
              "height":560},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/愈合变化/u76_line.png"}},
{
          "id":"c879fc0facab48aab05db2e3b3aeb2b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":30,
              "height":547}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a96929a5545409c84031e79021f53b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":30,
                  "height":547}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u42.png"}},
{
          "id":"3c1acb5f984e4a6cbdd946c4d7d2d5eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":970,
              "y":452},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80526a1766e2428983b182d7c08e2069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":970,
                  "y":452},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u44.png"}},
{
          "id":"67c841c9d5db4c58a0cd6cba6614bed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":1020,
              "y":451},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a61ccc162644440ad7bb85d0daee497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":451},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7871fa9feaa440ca92d91d7db5fabb44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC33},
            "location":{
              "x":970,
              "y":499},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73790375829e40f7a3d9385fe79109f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC33},
                "location":{
                  "x":970,
                  "y":499},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u48.png"}},
{
          "id":"3f17df19e6024370b8b1eeb4af2c4802",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC33,
              "opacity":1},
            "location":{
              "x":1020,
              "y":498},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88589d67ddc94c9dbed9e8b9b66e5785",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":498},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f79c1d6319544ee78913ef13f33b8c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":970,
              "y":543},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75b3481639134ddb9e2c48a216613957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":970,
                  "y":543},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u52.png"}},
{
          "id":"14232443434b4c3fbcd287fff41b7d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":1020,
              "y":542},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036a199e69d04ea191a14ca1e33753a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":542},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02b5297507ec46b18b34114397ac2f7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF9900CC},
            "location":{
              "x":970,
              "y":588},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9900CC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de1e1aa8d0934103a946c92376f977c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9900CC},
                "location":{
                  "x":970,
                  "y":588},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u56.png"}},
{
          "id":"b93a8637ac824663bcbd79754748258b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":1020,
              "y":587},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0a24d6d45d4752bc6f7e689c736352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":587},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"199555105ff44b2ea0e13d2c321f79a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2f27212e4540a7a5ee1c72f07ac10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/愈合变化/u60.png"}},
{
          "id":"fb1824c29fa54a25b533a79655581cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":612,
              "y":1056},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c6999f2333646c8a41aedae2950834a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":612,
                  "y":1056},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 伤口记录",
                      "target":{
                        "targetType":"page",
                        "url":"伤口记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc4413e603fe4733bd5b0c1fc466ebfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":770,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8758b07eb7bb431283b6773e498b98bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":770,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 愈合变化",
                      "target":{
                        "targetType":"page",
                        "url":"愈合变化.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5afee2197a724454acfd37c39e3dc86d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":929,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0321e02214848a6a33144117e109b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":929,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 同步归档",
                      "target":{
                        "targetType":"page",
                        "url":"同步归档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53ffd55461ce4a82a22f6f87493cdf68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":447,
              "y":1054},
            "size":{
              "width":90,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f89b4d4eb5464b858267af6c37a91b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":447,
                  "y":1054},
                "size":{
                  "width":90,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者登记",
                      "target":{
                        "targetType":"page",
                        "url":"患者登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"707969828a4745d699c99bcc5291dfa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":450},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e845230690a248c5802a9514036f6e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":450},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 总体",
                      "target":{
                        "targetType":"page",
                        "url":"总体.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b640d11df7fd46a996aebc37a48132ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":497},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f47fa034690438990ddc28a1fe28571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":497},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 面积",
                      "target":{
                        "targetType":"page",
                        "url":"面积.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23fc17b72a874433a84fe7055ba5df7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":542},
            "size":{
              "width":110,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f7f46a67384c5c82a27425cca6a2fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":542},
                "size":{
                  "width":110,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渗液量",
                      "target":{
                        "targetType":"page",
                        "url":"渗液量.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d98d4ac12cb34c4db469e4f4ca1bdc72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":970,
              "y":587},
            "size":{
              "width":150,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e6f4381c96b4befa25d1f7839b2e5db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":970,
                  "y":587},
                "size":{
                  "width":150,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创面组织类型",
                      "target":{
                        "targetType":"page",
                        "url":"创面组织类型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dd6f412b2e14b139a2626662ad1b57f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":680,
              "y":620},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bfe02431da6477395896a63c0d0ce6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":680,
                  "y":620},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"159a965c36c84e1baaf7b6ed695df12f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":620},
            "size":{
              "width":250,
              "height":270},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f61939acdb1d41c7be79306d3ac4a37e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":620},
                "size":{
                  "width":250,
                  "height":270},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u87.png"}},
{
          "id":"23f11942a66c4b22a657eca284b097e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":760},
            "size":{
              "width":390,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02fcd41471c49c28b2e1c3b54397532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":760},
                "size":{
                  "width":390,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u89.png"}},
{
          "id":"51ef5228f912494e9da5ee66d6cb67f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":873},
            "size":{
              "width":99,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"effd7d18fbc14bf291de5c1ed06a5b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":873},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u91.png"}},
{
          "id":"d2346711eb414db1a8020a27897421d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":909},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44eca76bd6e4df39d6def3cde1a1123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":909},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"3ec08dba69274a099bb80faf70f35882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":920},
            "size":{
              "width":117,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a28c3ccb70540ca9b0ed6efe8bce528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":973,
                  "y":920},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创面组织类型/u93.png"}},
{
          "id":"b24dd9ecfeba4fedb0e4cf3b8b191a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0000},
            "location":{
              "x":990,
              "y":257},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f9e4bf9396d470e90ba1e509234c707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000},
                "location":{
                  "x":990,
                  "y":257},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看图片记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看图片记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf092734daba453e8076c67183208b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":440,
              "y":913},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca16514a2c2423e99b8be7415c0a444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":913},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a61d10973fcb4829b17274c627db8193",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":580,
              "y":913},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58d1ff63791c49269bb114f8aec0f128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":913},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b33488ed68d4d5db824b01720fb76e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":730,
              "y":942},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9553e83f75054fcd8330865360ef2035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":730,
                  "y":942},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"844ec409ddcb407a870d926866926800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":877,
              "y":942},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c8ce2440a54c9982949da8c7df7e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":877,
                  "y":942},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13bd425a77ff4cac9d9d5ebda9a60f02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900CC,
              "opacity":1},
            "location":{
              "x":1035,
              "y":960},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d3bec8cc504cc0b6de34f234febdd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC,
                  "opacity":1},
                "location":{
                  "x":1035,
                  "y":960},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1f26d687a6e84017904af433113d6b22":{
      "scriptId":"u0"},
    "8079ca770d324f1e86a0224f6e8864db":{
      "scriptId":"u1"},
    "90ac738207384441a56af45037c76911":{
      "scriptId":"u2"},
    "ccabde0a953a4861ab3b80bfda1a5d79":{
      "scriptId":"u3"},
    "11cb363e1a80482693c0ae41b876f18f":{
      "scriptId":"u4"},
    "fb06d8ac51844e2e8a0dd4b820eae3e0":{
      "scriptId":"u5"},
    "647f32df6ea44b198a3686426bde748b":{
      "scriptId":"u6"},
    "bdbde86ecc4a4e34be53062e5b80436a":{
      "scriptId":"u7"},
    "a8d8b41090d142188873ff61e99253b9":{
      "scriptId":"u8"},
    "6e7c41c6c78c4455bc7b6fbc2c2b38ed":{
      "scriptId":"u9"},
    "9d3b0b140cf642cca075f5a2b45956c2":{
      "scriptId":"u10"},
    "9987b30691804f6886cc32db7f55e1b1":{
      "scriptId":"u11"},
    "34528248bfe5488aa16cb1f1489f7e08":{
      "scriptId":"u12"},
    "4220144e41024a358185e981836a205c":{
      "scriptId":"u13"},
    "54d9a06ddf834e1f86021935af088550":{
      "scriptId":"u14"},
    "7eb33f6d08bc4b9f88f734cd94fcb685":{
      "scriptId":"u15"},
    "5a9363848716472799ce56b0a8490aa7":{
      "scriptId":"u16"},
    "551115bb8f2745c08e1cbdfeee70e23b":{
      "scriptId":"u17"},
    "f54ed51ee55647dca82ddee10bbec561":{
      "scriptId":"u18"},
    "17d6dd041a7e46d399577962ad39e8ba":{
      "scriptId":"u19"},
    "3773599e0f8c41938ec79cabe515b1f2":{
      "scriptId":"u20"},
    "c9eb4c3261874bec94bb8ff895e44afa":{
      "scriptId":"u21"},
    "ee0e574f0b5f45d2967fedcee5bf7543":{
      "scriptId":"u22"},
    "685ceb2a83654768b710ff60238eb095":{
      "scriptId":"u23"},
    "afdbde27a25b4e04a9d6cadd659420fa":{
      "scriptId":"u24"},
    "b063bdcc2b574be1a48ad5e6050f6ba3":{
      "scriptId":"u25"},
    "81ae69a3c42b401781a8bf9647f8cb17":{
      "scriptId":"u26"},
    "3551485b51e24bb9800e8776b2d08672":{
      "scriptId":"u27"},
    "63887e849116485382e910ab9fc43277":{
      "scriptId":"u28"},
    "402bedb239bc414893b04c797034b716":{
      "scriptId":"u29"},
    "4828b385ede749bfac9e485811e351d9":{
      "scriptId":"u30"},
    "18db17562d0045c8ba481845addaf941":{
      "scriptId":"u31"},
    "103ce4d0b95b45efa63dd0068d39af61":{
      "scriptId":"u32"},
    "be27756f7b7a459d9e8ea206e499a0cd":{
      "scriptId":"u33"},
    "9df20f452e5b4403974cc039d46ee39b":{
      "scriptId":"u34"},
    "61af83a27f9b4b94b993af40bc47bf66":{
      "scriptId":"u35"},
    "21137d8bf7ba4b3ba6cccfc64a72d5a7":{
      "scriptId":"u36"},
    "9c6963a7c46848dc8b84b895b96f976b":{
      "scriptId":"u37"},
    "e312ee57b7e745908e8642ffdd1352f8":{
      "scriptId":"u38"},
    "1a34e0bcb51f47579f487f96bb122d96":{
      "scriptId":"u39"},
    "3d5b691690e54ca78c7449d285427fa9":{
      "scriptId":"u40"},
    "75cffcaca72d42d9837ba717f8f54cf8":{
      "scriptId":"u41"},
    "24e9e61be89041f5aae13af317cd9753":{
      "scriptId":"u42"},
    "9d6fb3cfe32541eca4c2e17226ef5840":{
      "scriptId":"u43"},
    "dcabab001c5c4035a919c8efde33c242":{
      "scriptId":"u44"},
    "6fba7f3bfed745a192f24427676488a6":{
      "scriptId":"u45"},
    "edd2bdf92b064ecebb2bf0f830252c19":{
      "scriptId":"u46"},
    "87906c22fa564ab1a192473638d834f1":{
      "scriptId":"u47"},
    "ee9b1461f7be458d85ea9f60cab077fe":{
      "scriptId":"u48"},
    "c879fc0facab48aab05db2e3b3aeb2b7":{
      "scriptId":"u49"},
    "4a96929a5545409c84031e79021f53b6":{
      "scriptId":"u50"},
    "3c1acb5f984e4a6cbdd946c4d7d2d5eb":{
      "scriptId":"u51"},
    "80526a1766e2428983b182d7c08e2069":{
      "scriptId":"u52"},
    "67c841c9d5db4c58a0cd6cba6614bed7":{
      "scriptId":"u53"},
    "8a61ccc162644440ad7bb85d0daee497":{
      "scriptId":"u54"},
    "7871fa9feaa440ca92d91d7db5fabb44":{
      "scriptId":"u55"},
    "73790375829e40f7a3d9385fe79109f7":{
      "scriptId":"u56"},
    "3f17df19e6024370b8b1eeb4af2c4802":{
      "scriptId":"u57"},
    "88589d67ddc94c9dbed9e8b9b66e5785":{
      "scriptId":"u58"},
    "f79c1d6319544ee78913ef13f33b8c30":{
      "scriptId":"u59"},
    "75b3481639134ddb9e2c48a216613957":{
      "scriptId":"u60"},
    "14232443434b4c3fbcd287fff41b7d8f":{
      "scriptId":"u61"},
    "036a199e69d04ea191a14ca1e33753a9":{
      "scriptId":"u62"},
    "02b5297507ec46b18b34114397ac2f7a":{
      "scriptId":"u63"},
    "de1e1aa8d0934103a946c92376f977c3":{
      "scriptId":"u64"},
    "b93a8637ac824663bcbd79754748258b":{
      "scriptId":"u65"},
    "2f0a24d6d45d4752bc6f7e689c736352":{
      "scriptId":"u66"},
    "199555105ff44b2ea0e13d2c321f79a5":{
      "scriptId":"u67"},
    "4f2f27212e4540a7a5ee1c72f07ac10e":{
      "scriptId":"u68"},
    "fb1824c29fa54a25b533a79655581cdd":{
      "scriptId":"u69"},
    "7c6999f2333646c8a41aedae2950834a":{
      "scriptId":"u70"},
    "cc4413e603fe4733bd5b0c1fc466ebfc":{
      "scriptId":"u71"},
    "8758b07eb7bb431283b6773e498b98bf":{
      "scriptId":"u72"},
    "5afee2197a724454acfd37c39e3dc86d":{
      "scriptId":"u73"},
    "e0321e02214848a6a33144117e109b7a":{
      "scriptId":"u74"},
    "53ffd55461ce4a82a22f6f87493cdf68":{
      "scriptId":"u75"},
    "f89b4d4eb5464b858267af6c37a91b45":{
      "scriptId":"u76"},
    "707969828a4745d699c99bcc5291dfa3":{
      "scriptId":"u77"},
    "e845230690a248c5802a9514036f6e07":{
      "scriptId":"u78"},
    "b640d11df7fd46a996aebc37a48132ef":{
      "scriptId":"u79"},
    "0f47fa034690438990ddc28a1fe28571":{
      "scriptId":"u80"},
    "23fc17b72a874433a84fe7055ba5df7c":{
      "scriptId":"u81"},
    "20f7f46a67384c5c82a27425cca6a2fa":{
      "scriptId":"u82"},
    "d98d4ac12cb34c4db469e4f4ca1bdc72":{
      "scriptId":"u83"},
    "4e6f4381c96b4befa25d1f7839b2e5db":{
      "scriptId":"u84"},
    "4dd6f412b2e14b139a2626662ad1b57f":{
      "scriptId":"u85"},
    "9bfe02431da6477395896a63c0d0ce6c":{
      "scriptId":"u86"},
    "159a965c36c84e1baaf7b6ed695df12f":{
      "scriptId":"u87"},
    "f61939acdb1d41c7be79306d3ac4a37e":{
      "scriptId":"u88"},
    "23f11942a66c4b22a657eca284b097e6":{
      "scriptId":"u89"},
    "f02fcd41471c49c28b2e1c3b54397532":{
      "scriptId":"u90"},
    "51ef5228f912494e9da5ee66d6cb67f6":{
      "scriptId":"u91"},
    "effd7d18fbc14bf291de5c1ed06a5b28":{
      "scriptId":"u92"},
    "d2346711eb414db1a8020a27897421d6":{
      "scriptId":"u93"},
    "e44eca76bd6e4df39d6def3cde1a1123":{
      "scriptId":"u94"},
    "3ec08dba69274a099bb80faf70f35882":{
      "scriptId":"u95"},
    "4a28c3ccb70540ca9b0ed6efe8bce528":{
      "scriptId":"u96"},
    "b24dd9ecfeba4fedb0e4cf3b8b191a62":{
      "scriptId":"u97"},
    "6f9e4bf9396d470e90ba1e509234c707":{
      "scriptId":"u98"},
    "cf092734daba453e8076c67183208b48":{
      "scriptId":"u99"},
    "0ca16514a2c2423e99b8be7415c0a444":{
      "scriptId":"u100"},
    "a61d10973fcb4829b17274c627db8193":{
      "scriptId":"u101"},
    "58d1ff63791c49269bb114f8aec0f128":{
      "scriptId":"u102"},
    "2b33488ed68d4d5db824b01720fb76e0":{
      "scriptId":"u103"},
    "9553e83f75054fcd8330865360ef2035":{
      "scriptId":"u104"},
    "844ec409ddcb407a870d926866926800":{
      "scriptId":"u105"},
    "37c8ce2440a54c9982949da8c7df7e55":{
      "scriptId":"u106"},
    "13bd425a77ff4cac9d9d5ebda9a60f02":{
      "scriptId":"u107"},
    "b1d3bec8cc504cc0b6de34f234febdd2":{
      "scriptId":"u108"}}});